Attribute VB_Name = "modkWabTags"
Option Explicit
Public Enum kPropTags
   PR_ACKNOWLEDGEMENT_MODE = &H10003
   PR_ALTERNATE_RECIPIENT_ALLOWED = &H2000B
   PR_AUTHORIZING_USERS = &H30102
   PR_AUTO_FORWARD_COMMENT_W = &H4001F
   PR_AUTO_FORWARD_COMMENT_A = &H4001E
   PR_AUTO_FORWARDED = &H5000B
   PR_CONTENT_CONFIDENTIALITY_ALGORITHM_ID = &H60102
   PR_CONTENT_CORRELATOR = &H70102
   PR_CONTENT_IDENTIFIER_W = &H8001F
   PR_CONTENT_IDENTIFIER_A = &H8001E
   PR_CONTENT_LENGTH = &H90003
   PR_CONTENT_RETURN_REQUESTED = &HA000B
   PR_CONVERSATION_KEY = &HB0102
   PR_CONVERSION_EITS = &HC0102
   PR_CONVERSION_WITH_LOSS_PROHIBITED = &HD000B
   PR_CONVERTED_EITS = &HE0102
   PR_DEFERRED_DELIVERY_TIME = &HF0040
   PR_DELIVER_TIME = &H100040
   PR_DISCARD_REASON = &H110003
   PR_DISCLOSURE_OF_RECIPIENTS = &H12000B
   PR_DL_EXPANSION_HISTORY = &H130102
   PR_DL_EXPANSION_PROHIBITED = &H14000B
   PR_EXPIRY_TIME = &H150040
   PR_IMPLICIT_CONVERSION_PROHIBITED = &H16000B
   PR_IMPORTANCE = &H170003
   PR_IPM_ID = &H180102
   PR_LATEST_DELIVERY_TIME = &H190040
   PR_MESSAGE_CLASS_W = &H1A001F
   PR_MESSAGE_CLASS_A = &H1A001E
   PR_MESSAGE_DELIVERY_ID = &H1B0102
   PR_MESSAGE_SECURITY_LABEL = &H1E0102
   PR_OBSOLETED_IPMS = &H1F0102
   PR_ORIGINALLY_INTENDED_RECIPIENT_NAME = &H200102
   PR_ORIGINAL_EITS = &H210102
   PR_ORIGINATOR_CERTIFICATE = &H220102
   PR_ORIGINATOR_DELIVERY_REPORT_REQUESTED = &H23000B
   PR_ORIGINATOR_RETURN_ADDRESS = &H240102
   PR_PARENT_KEY = &H250102
   PR_PRIORITY = &H260003
   PR_ORIGIN_CHECK = &H270102
   PR_PROOF_OF_SUBMISSION_REQUESTED = &H28000B
   PR_READ_RECEIPT_REQUESTED = &H29000B
   PR_RECEIPT_TIME = &H2A0040
   PR_RECIPIENT_REASSIGNMENT_PROHIBITED = &H2B000B
   PR_REDIRECTION_HISTORY = &H2C0102
   PR_RELATED_IPMS = &H2D0102
   PR_ORIGINAL_SENSITIVITY = &H2E0003
   PR_LANGUAGES_W = &H2F001F
   PR_LANGUAGES_A = &H2F001E
   PR_REPLY_TIME = &H300040
   PR_REPORT_TAG = &H310102
   PR_REPORT_TIME = &H320040
   PR_RETURNED_IPM = &H33000B
   PR_SECURITY = &H340003
   PR_INCOMPLETE_COPY = &H35000B
   PR_SENSITIVITY = &H360003
   PR_SUBJECT_W = &H37001F
   PR_SUBJECT_A = &H37001E
   PR_SUBJECT_IPM = &H380102
   PR_CLIENT_SUBMIT_TIME = &H390040
   PR_REPORT_NAME_W = &H3A001F
   PR_REPORT_NAME_A = &H3A001E
   PR_SENT_REPRESENTING_SEARCH_KEY = &H3B0102
   PR_X400_CONTENT_TYPE = &H3C0102
   PR_SUBJECT_PREFIX_W = &H3D001F
   PR_SUBJECT_PREFIX_A = &H3D001E
   PR_NON_RECEIPT_REASON = &H3E0003
   PR_RECEIVED_BY_ENTRYID = &H3F0102
   PR_RECEIVED_BY_NAME_W = &H40001F
   PR_RECEIVED_BY_NAME_A = &H40001E
   PR_SENT_REPRESENTING_ENTRYID = &H410102
   PR_SENT_REPRESENTING_NAME_W = &H42001F
   PR_SENT_REPRESENTING_NAME_A = &H42001E
   PR_RCVD_REPRESENTING_ENTRYID = &H430102
   PR_RCVD_REPRESENTING_NAME_W = &H44001F
   PR_RCVD_REPRESENTING_NAME_A = &H44001E
   PR_REPORT_ENTRYID = &H450102
   PR_READ_RECEIPT_ENTRYID = &H460102
   PR_MESSAGE_SUBMISSION_ID = &H470102
   PR_PROVIDER_SUBMIT_TIME = &H480040
   PR_ORIGINAL_SUBJECT_W = &H49001F
   PR_ORIGINAL_SUBJECT_A = &H49001E
   PR_DISC_VAL = &H4A000B
   PR_ORIG_MESSAGE_CLASS_W = &H4B001F
   PR_ORIG_MESSAGE_CLASS_A = &H4B001E
   PR_ORIGINAL_AUTHOR_ENTRYID = &H4C0102
   PR_ORIGINAL_AUTHOR_NAME_W = &H4D001F
   PR_ORIGINAL_AUTHOR_NAME_A = &H4D001E
   PR_ORIGINAL_SUBMIT_TIME = &H4E0040
   PR_REPLY_RECIPIENT_ENTRIES = &H4F0102
   PR_REPLY_RECIPIENT_NAMES_W = &H50001F
   PR_REPLY_RECIPIENT_NAMES_A = &H50001E
   PR_RECEIVED_BY_SEARCH_KEY = &H510102
   PR_RCVD_REPRESENTING_SEARCH_KEY = &H520102
   PR_READ_RECEIPT_SEARCH_KEY = &H530102
   PR_REPORT_SEARCH_KEY = &H540102
   PR_ORIGINAL_DELIVERY_TIME = &H550040
   PR_ORIGINAL_AUTHOR_SEARCH_KEY = &H560102
   PR_MESSAGE_TO_ME = &H57000B
   PR_MESSAGE_CC_ME = &H58000B
   PR_MESSAGE_RECIP_ME = &H59000B
   PR_ORIGINAL_SENDER_NAME_W = &H5A001F
   PR_ORIGINAL_SENDER_NAME_A = &H5A001E
   PR_ORIGINAL_SENDER_ENTRYID = &H5B0102
   PR_ORIGINAL_SENDER_SEARCH_KEY = &H5C0102
   PR_ORIGINAL_SENT_REPRESENTING_NAME_W = &H5D001F
   PR_ORIGINAL_SENT_REPRESENTING_NAME_A = &H5D001E
   PR_ORIGINAL_SENT_REPRESENTING_ENTRYID = &H5E0102
   PR_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY = &H5F0102
   PR_START_DATE = &H600040
   PR_END_DATE = &H610040
   PR_OWNER_APPT_ID = &H620003
   PR_RESPONSE_REQUESTED = &H63000B
   PR_SENT_REPRESENTING_ADDRTYPE_W = &H64001F
   PR_SENT_REPRESENTING_ADDRTYPE_A = &H64001E
   PR_SENT_REPRESENTING_EMAIL_ADDRESS_W = &H65001F
   PR_SENT_REPRESENTING_EMAIL_ADDRESS_A = &H65001E
   PR_ORIGINAL_SENDER_ADDRTYPE_W = &H66001F
   PR_ORIGINAL_SENDER_ADDRTYPE_A = &H66001E
   PR_ORIGINAL_SENDER_EMAIL_ADDRESS_W = &H67001F
   PR_ORIGINAL_SENDER_EMAIL_ADDRESS_A = &H67001E
   PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_W = &H68001F
   PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_A = &H68001E
   PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_W = &H69001F
   PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_A = &H69001E
   PR_CONVERSATION_TOPIC_W = &H70001F
   PR_CONVERSATION_TOPIC_A = &H70001E
   PR_CONVERSATION_INDEX = &H710102
   PR_ORIGINAL_DISPLAY_BCC_W = &H72001F
   PR_ORIGINAL_DISPLAY_BCC_A = &H72001E
   PR_ORIGINAL_DISPLAY_CC_W = &H73001F
   PR_ORIGINAL_DISPLAY_CC_A = &H73001E
   PR_ORIGINAL_DISPLAY_TO_W = &H74001F
   PR_ORIGINAL_DISPLAY_TO_A = &H74001E
   PR_RECEIVED_BY_ADDRTYPE_W = &H75001F
   PR_RECEIVED_BY_ADDRTYPE_A = &H75001E
   PR_RECEIVED_BY_EMAIL_ADDRESS_W = &H76001F
   PR_RECEIVED_BY_EMAIL_ADDRESS_A = &H76001E
   PR_RCVD_REPRESENTING_ADDRTYPE_W = &H77001F
   PR_RCVD_REPRESENTING_ADDRTYPE_A = &H77001E
   PR_RCVD_REPRESENTING_EMAIL_ADDRESS_W = &H78001F
   PR_RCVD_REPRESENTING_EMAIL_ADDRESS_A = &H78001E
   PR_ORIGINAL_AUTHOR_ADDRTYPE_W = &H79001F
   PR_ORIGINAL_AUTHOR_ADDRTYPE_A = &H79001E
   PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_W = &H7A001F
   PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_A = &H7A001E
   PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_W = &H7B001F
   PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_A = &H7B001E
   PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_W = &H7C001F
   PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_A = &H7C001E
   PR_TRANSPORT_MESSAGE_HEADERS_W = &H7D001F
   PR_TRANSPORT_MESSAGE_HEADERS_A = &H7D001E
   PR_DELEGATION = &H7E0102
   PR_TNEF_CORRELATION_KEY = &H7F0102
   PR_BODY_W = &H1000001F
   PR_BODY_A = &H1000001E
   PR_REPORT_TEXT_W = &H1001001F
   PR_REPORT_TEXT_A = &H1001001E
   PR_ORIGINATOR_AND_DL_EXPANSION_HISTORY = &H10020102
   PR_REPORTING_DL_NAME = &H10030102
   PR_REPORTING_MTA_CERTIFICATE = &H10040102
   PR_RTF_SYNC_BODY_CRC = &H10060003
   PR_RTF_SYNC_BODY_COUNT = &H10070003
   PR_RTF_SYNC_BODY_TAG_W = &H1008001F
   PR_RTF_SYNC_BODY_TAG_A = &H1008001E
   PR_RTF_COMPRESSED = &H10090102
   PR_RTF_SYNC_PREFIX_COUNT = &H10100003
   PR_RTF_SYNC_TRAILING_COUNT = &H10110003
   PR_ORIGINALLY_INTENDED_RECIP_ENTRYID = &H10120102
   PR_CONTENT_INTEGRITY_CHECK = &HC000102
   PR_EXPLICIT_CONVERSION = &HC010003
   PR_IPM_RETURN_REQUESTED = &HC02000B
   PR_MESSAGE_TOKEN = &HC030102
   PR_NDR_REASON_CODE = &HC040003
   PR_NDR_DIAG_CODE = &HC050003
   PR_NON_RECEIPT_NOTIFICATION_REQUESTED = &HC06000B
   PR_DELIVERY_POINT = &HC070003
   PR_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED = &HC08000B
   PR_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT = &HC090102
   PR_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY = &HC0A000B
   PR_PHYSICAL_DELIVERY_MODE = &HC0B0003
   PR_PHYSICAL_DELIVERY_REPORT_REQUEST = &HC0C0003
   PR_PHYSICAL_FORWARDING_ADDRESS = &HC0D0102
   PR_PHYSICAL_FORWARDING_ADDRESS_REQUESTED = &HC0E000B
   PR_PHYSICAL_FORWARDING_PROHIBITED = &HC0F000B
   PR_PHYSICAL_RENDITION_ATTRIBUTES = &HC100102
   PR_PROOF_OF_DELIVERY = &HC110102
   PR_PROOF_OF_DELIVERY_REQUESTED = &HC12000B
   PR_RECIPIENT_CERTIFICATE = &HC130102
   PR_RECIPIENT_NUMBER_FOR_ADVICE_W = &HC14001F
   PR_RECIPIENT_NUMBER_FOR_ADVICE_A = &HC14001E
   PR_RECIPIENT_TYPE = &HC150003
   PR_REGISTERED_MAIL_TYPE = &HC160003
   PR_REPLY_REQUESTED = &HC17000B
   PR_REQUESTED_DELIVERY_METHOD = &HC180003
   PR_SENDER_ENTRYID = &HC190102
   PR_SENDER_NAME_W = &HC1A001F
   PR_SENDER_NAME_A = &HC1A001E
   PR_SUPPLEMENTARY_INFO_W = &HC1B001F
   PR_SUPPLEMENTARY_INFO_A = &HC1B001E
   PR_TYPE_OF_MTS_USER = &HC1C0003
   PR_SENDER_SEARCH_KEY = &HC1D0102
   PR_SENDER_ADDRTYPE_W = &HC1E001F
   PR_SENDER_ADDRTYPE_A = &HC1E001E
   PR_SENDER_EMAIL_ADDRESS_W = &HC1F001F
   PR_SENDER_EMAIL_ADDRESS_A = &HC1F001E
   PR_CURRENT_VERSION = &HE000014
   PR_DELETE_AFTER_SUBMIT = &HE01000B
   PR_DISPLAY_BCC_W = &HE02001F
   PR_DISPLAY_BCC_A = &HE02001E
   PR_DISPLAY_CC_W = &HE03001F
   PR_DISPLAY_CC_A = &HE03001E
   PR_DISPLAY_TO_W = &HE04001F
   PR_DISPLAY_TO_A = &HE04001E
   PR_PARENT_DISPLAY_W = &HE05001F
   PR_PARENT_DISPLAY_A = &HE05001E
   PR_MESSAGE_DELIVERY_TIME = &HE060040
   PR_MESSAGE_FLAGS = &HE070003
   PR_MESSAGE_SIZE = &HE080003
   PR_PARENT_ENTRYID = &HE090102
   PR_SENTMAIL_ENTRYID = &HE0A0102
   PR_CORRELATE = &HE0C000B
   PR_CORRELATE_MTSID = &HE0D0102
   PR_DISCRETE_VALUES = &HE0E000B
   PR_RESPONSIBILITY = &HE0F000B
   PR_SPOOLER_STATUS = &HE100003
   PR_TRANSPORT_STATUS = &HE110003
   PR_MESSAGE_RECIPIENTS = &HE12000D
   PR_MESSAGE_ATTACHMENTS = &HE13000D
   PR_SUBMIT_FLAGS = &HE140003
   PR_RECIPIENT_STATUS = &HE150003
   PR_TRANSPORT_KEY = &HE160003
   PR_MSG_STATUS = &HE170003
   PR_MESSAGE_DOWNLOAD_TIME = &HE180003
   PR_CREATION_VERSION = &HE190014
   PR_MODIFY_VERSION = &HE1A0014
   PR_HASATTACH = &HE1B000B
   PR_BODY_CRC = &HE1C0003
   PR_NORMALIZED_SUBJECT_W = &HE1D001F
   PR_NORMALIZED_SUBJECT_A = &HE1D001E
   PR_RTF_IN_SYNC = &HE1F000B
   PR_ATTACH_SIZE = &HE200003
   PR_ATTACH_NUM = &HE210003
   PR_PREPROCESS = &HE22000B
   PR_ORIGINATING_MTA_CERTIFICATE = &HE250102
   PR_PROOF_OF_SUBMISSION = &HE260102
   PR_ENTRYID = &HFFF0102
   PR_OBJECT_TYPE = &HFFE0003
   PR_ICON = &HFFD0102
   PR_MINI_ICON = &HFFC0102
   PR_STORE_ENTRYID = &HFFB0102
   PR_STORE_RECORD_KEY = &HFFA0102
   PR_RECORD_KEY = &HFF90102
   PR_MAPPING_SIGNATURE = &HFF80102
   PR_ACCESS_LEVEL = &HFF70003
   PR_INSTANCE_KEY = &HFF60102
   PR_ROW_TYPE = &HFF50003
   PR_ACCESS = &HFF40003
   PR_ROWID = &H30000003
   PR_DISPLAY_NAME_W = &H3001001F
   PR_DISPLAY_NAME_A = &H3001001E
   PR_ADDRTYPE_W = &H3002001F
   PR_ADDRTYPE_A = &H3002001E
   PR_EMAIL_ADDRESS_W = &H3003001F
   PR_EMAIL_ADDRESS_A = &H3003001E
   PR_COMMENT_W = &H3004001F
   PR_COMMENT_A = &H3004001E
   PR_DEPTH = &H30050003
   PR_PROVIDER_DISPLAY_W = &H3006001F
   PR_PROVIDER_DISPLAY_A = &H3006001E
   PR_CREATION_TIME = &H30070040
   PR_LAST_MODIFICATION_TIME = &H30080040
   PR_RESOURCE_FLAGS = &H30090003
   PR_PROVIDER_DLL_NAME_W = &H300A001F
   PR_PROVIDER_DLL_NAME_A = &H300A001E
   PR_SEARCH_KEY = &H300B0102
   PR_PROVIDER_UID = &H300C0102
   PR_PROVIDER_ORDINAL = &H300D0003
   PR_FORM_VERSION_W = &H3301001F
   PR_FORM_VERSION_A = &H3301001E
   PR_FORM_CLSID = &H33020048
   PR_FORM_CONTACT_NAME_W = &H3303001F
   PR_FORM_CONTACT_NAME_A = &H3303001E
   PR_FORM_CATEGORY_W = &H3304001F
   PR_FORM_CATEGORY_A = &H3304001E
   PR_FORM_CATEGORY_SUB_W = &H3305001F
   PR_FORM_CATEGORY_SUB_A = &H3305001E
   PR_FORM_HOST_MAP = &H33061003
   PR_FORM_HIDDEN = &H3307000B
   PR_FORM_DESIGNER_NAME_W = &H3308001F
   PR_FORM_DESIGNER_NAME_A = &H3308001E
   PR_FORM_DESIGNER_GUID = &H33090048
   PR_FORM_MESSAGE_BEHAVIOR = &H330A0003
   PR_DEFAULT_STORE = &H3400000B
   PR_STORE_SUPPORT_MASK = &H340D0003
   PR_STORE_STATE = &H340E0003
   PR_IPM_SUBTREE_SEARCH_KEY = &H34100102
   PR_IPM_OUTBOX_SEARCH_KEY = &H34110102
   PR_IPM_WASTEBASKET_SEARCH_KEY = &H34120102
   PR_IPM_SENTMAIL_SEARCH_KEY = &H34130102
   PR_MDB_PROVIDER = &H34140102
   PR_RECEIVE_FOLDER_SETTINGS = &H3415000D
   PR_VALID_FOLDER_MASK = &H35DF0003
   PR_IPM_SUBTREE_ENTRYID = &H35E00102
   PR_IPM_OUTBOX_ENTRYID = &H35E20102
   PR_IPM_WASTEBASKET_ENTRYID = &H35E30102
   PR_IPM_SENTMAIL_ENTRYID = &H35E40102
   PR_VIEWS_ENTRYID = &H35E50102
   PR_COMMON_VIEWS_ENTRYID = &H35E60102
   PR_FINDER_ENTRYID = &H35E70102
   PR_CONTAINER_FLAGS = &H36000003
   PR_FOLDER_TYPE = &H36010003
   PR_CONTENT_COUNT = &H36020003
   PR_CONTENT_UNREAD = &H36030003
   PR_CREATE_TEMPLATES = &H3604000D
   PR_DETAILS_TABLE = &H3605000D
   PR_SEARCH = &H3607000D
   PR_SELECTABLE = &H3609000B
   PR_SUBFOLDERS = &H360A000B
   PR_STATUS = &H360B0003
   PR_ANR_W = &H360C001F
   PR_ANR_A = &H360C001E
   PR_CONTENTS_SORT_ORDER = &H360D1003
   PR_CONTAINER_HIERARCHY = &H360E000D
   PR_CONTAINER_CONTENTS = &H360F000D
   PR_FOLDER_ASSOCIATED_CONTENTS = &H3610000D
   PR_DEF_CREATE_DL = &H36110102
   PR_DEF_CREATE_MAILUSER = &H36120102
   PR_CONTAINER_CLASS_W = &H3613001F
   PR_CONTAINER_CLASS_A = &H3613001E
   PR_CONTAINER_MODIFY_VERSION = &H36140014
   PR_AB_PROVIDER_ID = &H36150102
   PR_DEFAULT_VIEW_ENTRYID = &H36160102
   PR_ASSOC_CONTENT_COUNT = &H36170003
   PR_ATTACHMENT_X400_PARAMETERS = &H37000102
   PR_ATTACH_DATA_OBJ = &H3701000D
   PR_ATTACH_DATA_BIN = &H37010102
   PR_ATTACH_ENCODING = &H37020102
   PR_ATTACH_EXTENSION_W = &H3703001F
   PR_ATTACH_EXTENSION_A = &H3703001E
   PR_ATTACH_FILENAME_W = &H3704001F
   PR_ATTACH_FILENAME_A = &H3704001E
   PR_ATTACH_METHOD = &H37050003
   PR_ATTACH_LONG_FILENAME_W = &H3707001F
   PR_ATTACH_LONG_FILENAME_A = &H3707001E
   PR_ATTACH_PATHNAME_W = &H3708001F
   PR_ATTACH_PATHNAME_A = &H3708001E
   PR_ATTACH_RENDERING = &H37090102
   PR_ATTACH_TAG = &H370A0102
   PR_RENDERING_POSITION = &H370B0003
   PR_ATTACH_TRANSPORT_NAME_W = &H370C001F
   PR_ATTACH_TRANSPORT_NAME_A = &H370C001E
   PR_ATTACH_LONG_PATHNAME_W = &H370D001F
   PR_ATTACH_LONG_PATHNAME_A = &H370D001E
   PR_ATTACH_MIME_TAG_W = &H370E001F
   PR_ATTACH_MIME_TAG_A = &H370E001E
   PR_ATTACH_ADDITIONAL_INFO = &H370F0102
   PR_DISPLAY_TYPE = &H39000003
   PR_TEMPLATEID = &H39020102
   PR_PRIMARY_CAPABILITY = &H39040102
   PR_7BIT_DISPLAY_NAME = &H39FF001E
   PR_ACCOUNT_W = &H3A00001F
   PR_ACCOUNT_A = &H3A00001E
   PR_ALTERNATE_RECIPIENT = &H3A010102
   PR_CALLBACK_TELEPHONE_NUMBER_W = &H3A02001F
   PR_CALLBACK_TELEPHONE_NUMBER_A = &H3A02001E
   PR_CONVERSION_PROHIBITED = &H3A03000B
   PR_DISCLOSE_RECIPIENTS = &H3A04000B
   PR_GENERATION_W = &H3A05001F
   PR_GENERATION_A = &H3A05001E
   PR_GIVEN_NAME_W = &H3A06001F
   PR_GIVEN_NAME_A = &H3A06001E
   PR_GOVERNMENT_ID_NUMBER_W = &H3A07001F
   PR_GOVERNMENT_ID_NUMBER_A = &H3A07001E
   PR_BUSINESS_TELEPHONE_NUMBER_W = &H3A08001F
   PR_BUSINESS_TELEPHONE_NUMBER_A = &H3A08001E
   PR_HOME_TELEPHONE_NUMBER_W = &H3A09001F
   PR_HOME_TELEPHONE_NUMBER_A = &H3A09001E
   PR_INITIALS_W = &H3A0A001F
   PR_INITIALS_A = &H3A0A001E
   PR_KEYWORD_W = &H3A0B001F
   PR_KEYWORD_A = &H3A0B001E
   PR_LANGUAGE_W = &H3A0C001F
   PR_LANGUAGE_A = &H3A0C001E
   PR_LOCATION_W = &H3A0D001F
   PR_LOCATION_A = &H3A0D001E
   PR_MAIL_PERMISSION = &H3A0E000B
   PR_MHS_COMMON_NAME_W = &H3A0F001F
   PR_MHS_COMMON_NAME_A = &H3A0F001E
   PR_ORGANIZATIONAL_ID_NUMBER_W = &H3A10001F
   PR_ORGANIZATIONAL_ID_NUMBER_A = &H3A10001E
   PR_SURNAME_W = &H3A11001F
   PR_SURNAME_A = &H3A11001E
   PR_ORIGINAL_ENTRYID = &H3A120102
   PR_ORIGINAL_DISPLAY_NAME_W = &H3A13001F
   PR_ORIGINAL_DISPLAY_NAME_A = &H3A13001E
   PR_ORIGINAL_SEARCH_KEY = &H3A140102
   PR_POSTAL_ADDRESS_W = &H3A15001F
   PR_POSTAL_ADDRESS_A = &H3A15001E
   PR_COMPANY_NAME_W = &H3A16001F
   PR_COMPANY_NAME_A = &H3A16001E
   PR_TITLE_W = &H3A17001F
   PR_TITLE_A = &H3A17001E
   PR_DEPARTMENT_NAME_W = &H3A18001F
   PR_DEPARTMENT_NAME_A = &H3A18001E
   PR_OFFICE_LOCATION_W = &H3A19001F
   PR_OFFICE_LOCATION_A = &H3A19001E
   PR_PRIMARY_TELEPHONE_NUMBER_W = &H3A1A001F
   PR_PRIMARY_TELEPHONE_NUMBER_A = &H3A1A001E
   PR_BUSINESS2_TELEPHONE_NUMBER_W = &H3A1B001F
   PR_BUSINESS2_TELEPHONE_NUMBER_A = &H3A1B001E
   PR_MOBILE_TELEPHONE_NUMBER_W = &H3A1C001F
   PR_MOBILE_TELEPHONE_NUMBER_A = &H3A1C001E
   PR_RADIO_TELEPHONE_NUMBER_W = &H3A1D001F
   PR_RADIO_TELEPHONE_NUMBER_A = &H3A1D001E
   PR_CAR_TELEPHONE_NUMBER_W = &H3A1E001F
   PR_CAR_TELEPHONE_NUMBER_A = &H3A1E001E
   PR_OTHER_TELEPHONE_NUMBER_W = &H3A1F001F
   PR_OTHER_TELEPHONE_NUMBER_A = &H3A1F001E
   PR_TRANSMITABLE_DISPLAY_NAME_W = &H3A20001F
   PR_TRANSMITABLE_DISPLAY_NAME_A = &H3A20001E
   PR_PAGER_TELEPHONE_NUMBER_W = &H3A21001F
   PR_PAGER_TELEPHONE_NUMBER_A = &H3A21001E
   PR_USER_CERTIFICATE = &H3A220102
   PR_PRIMARY_FAX_NUMBER_W = &H3A23001F
   PR_PRIMARY_FAX_NUMBER_A = &H3A23001E
   PR_BUSINESS_FAX_NUMBER_W = &H3A24001F
   PR_BUSINESS_FAX_NUMBER_A = &H3A24001E
   PR_HOME_FAX_NUMBER_W = &H3A25001F
   PR_HOME_FAX_NUMBER_A = &H3A25001E
   PR_COUNTRY_W = &H3A26001F
   PR_COUNTRY_A = &H3A26001E
   PR_LOCALITY_W = &H3A27001F
   PR_LOCALITY_A = &H3A27001E
   PR_STATE_OR_PROVINCE_W = &H3A28001F
   PR_STATE_OR_PROVINCE_A = &H3A28001E
   PR_STREET_ADDRESS_W = &H3A29001F
   PR_STREET_ADDRESS_A = &H3A29001E
   PR_POSTAL_CODE_W = &H3A2A001F
   PR_POSTAL_CODE_A = &H3A2A001E
   PR_POST_OFFICE_BOX_W = &H3A2B001F
   PR_POST_OFFICE_BOX_A = &H3A2B001E
   PR_TELEX_NUMBER_W = &H3A2C001F
   PR_TELEX_NUMBER_A = &H3A2C001E
   PR_ISDN_NUMBER_W = &H3A2D001F
   PR_ISDN_NUMBER_A = &H3A2D001E
   PR_ASSISTANT_TELEPHONE_NUMBER_W = &H3A2E001F
   PR_ASSISTANT_TELEPHONE_NUMBER_A = &H3A2E001E
   PR_HOME2_TELEPHONE_NUMBER_W = &H3A2F001F
   PR_HOME2_TELEPHONE_NUMBER_A = &H3A2F001E
   PR_ASSISTANT_W = &H3A30001F
   PR_ASSISTANT_A = &H3A30001E
   PR_SEND_RICH_INFO = &H3A40000B
   PR_WEDDING_ANNIVERSARY = &H3A410040
   PR_BIRTHDAY = &H3A420040
   PR_HOBBIES_W = &H3A43001F
   PR_HOBBIES_A = &H3A43001E
   PR_MIDDLE_NAME_W = &H3A44001F
   PR_MIDDLE_NAME_A = &H3A44001E
   PR_DISPLAY_NAME_PREFIX_W = &H3A45001F
   PR_DISPLAY_NAME_PREFIX_A = &H3A45001E
   PR_PROFESSION_W = &H3A46001F
   PR_PROFESSION_A = &H3A46001E
   PR_PREFERRED_BY_NAME_W = &H3A47001F
   PR_PREFERRED_BY_NAME_A = &H3A47001E
   PR_SPOUSE_NAME_W = &H3A48001F
   PR_SPOUSE_NAME_A = &H3A48001E
   PR_COMPUTER_NETWORK_NAME_W = &H3A49001F
   PR_COMPUTER_NETWORK_NAME_A = &H3A49001E
   PR_CUSTOMER_ID_W = &H3A4A001F
   PR_CUSTOMER_ID_A = &H3A4A001E
   PR_TTYTDD_PHONE_NUMBER_W = &H3A4B001F
   PR_TTYTDD_PHONE_NUMBER_A = &H3A4B001E
   PR_FTP_SITE_W = &H3A4C001F
   PR_FTP_SITE_A = &H3A4C001E
   PR_GENDER = &H3A4D0002
   PR_MANAGER_NAME_W = &H3A4E001F
   PR_MANAGER_NAME_A = &H3A4E001E
   PR_NICKNAME_W = &H3A4F001F
   PR_NICKNAME_A = &H3A4F001E
   PR_PERSONAL_HOME_PAGE_W = &H3A50001F
   PR_PERSONAL_HOME_PAGE_A = &H3A50001E
   PR_BUSINESS_HOME_PAGE_W = &H3A51001F
   PR_BUSINESS_HOME_PAGE_A = &H3A51001E
   PR_CONTACT_VERSION = &H3A520048
   PR_CONTACT_ENTRYIDS = &H3A531102
   PR_CONTACT_ADDRTYPES_W = &H3A54101F
   PR_CONTACT_ADDRTYPES_A = &H3A54101E
   PR_CONTACT_DEFAULT_ADDRESS_INDEX = &H3A550003
   PR_CONTACT_EMAIL_ADDRESSES_W = &H3A56101F
   PR_CONTACT_EMAIL_ADDRESSES_A = &H3A56101E
   PR_COMPANY_MAIN_PHONE_NUMBER_W = &H3A57001F
   PR_COMPANY_MAIN_PHONE_NUMBER_A = &H3A57001E
   PR_CHILDRENS_NAMES_W = &H3A58101F
   PR_CHILDRENS_NAMES_A = &H3A58101E
   PR_HOME_ADDRESS_CITY_W = &H3A59001F
   PR_HOME_ADDRESS_CITY_A = &H3A59001E
   PR_HOME_ADDRESS_COUNTRY_W = &H3A5A001F
   PR_HOME_ADDRESS_COUNTRY_A = &H3A5A001E
   PR_HOME_ADDRESS_POSTAL_CODE_W = &H3A5B001F
   PR_HOME_ADDRESS_POSTAL_CODE_A = &H3A5B001E
   PR_HOME_ADDRESS_STATE_OR_PROVINCE_W = &H3A5C001F
   PR_HOME_ADDRESS_STATE_OR_PROVINCE_A = &H3A5C001E
   PR_HOME_ADDRESS_STREET_W = &H3A5D001F
   PR_HOME_ADDRESS_STREET_A = &H3A5D001E
   PR_HOME_ADDRESS_POST_OFFICE_BOX_W = &H3A5E001F
   PR_HOME_ADDRESS_POST_OFFICE_BOX_A = &H3A5E001E
   PR_OTHER_ADDRESS_CITY_W = &H3A5F001F
   PR_OTHER_ADDRESS_CITY_A = &H3A5F001E
   PR_OTHER_ADDRESS_COUNTRY_W = &H3A60001F
   PR_OTHER_ADDRESS_COUNTRY_A = &H3A60001E
   PR_OTHER_ADDRESS_POSTAL_CODE_W = &H3A61001F
   PR_OTHER_ADDRESS_POSTAL_CODE_A = &H3A61001E
   PR_OTHER_ADDRESS_STATE_OR_PROVINCE_W = &H3A62001F
   PR_OTHER_ADDRESS_STATE_OR_PROVINCE_A = &H3A62001E
   PR_OTHER_ADDRESS_STREET_W = &H3A63001F
   PR_OTHER_ADDRESS_STREET_A = &H3A63001E
   PR_OTHER_ADDRESS_POST_OFFICE_BOX_W = &H3A64001F
   PR_OTHER_ADDRESS_POST_OFFICE_BOX_A = &H3A64001E
   PR_STORE_PROVIDERS = &H3D000102
   PR_AB_PROVIDERS = &H3D010102
   PR_TRANSPORT_PROVIDERS = &H3D020102
   PR_DEFAULT_PROFILE = &H3D04000B
   PR_AB_SEARCH_PATH = &H3D051102
   PR_AB_DEFAULT_DIR = &H3D060102
   PR_AB_DEFAULT_PAB = &H3D070102
   PR_FILTERING_HOOKS = &H3D080102
   PR_SERVICE_NAME_W = &H3D09001F
   PR_SERVICE_NAME_A = &H3D09001E
   PR_SERVICE_DLL_NAME_W = &H3D0A001F
   PR_SERVICE_DLL_NAME_A = &H3D0A001E
   PR_SERVICE_ENTRY_NAME = &H3D0B001E
   PR_SERVICE_UID = &H3D0C0102
   PR_SERVICE_EXTRA_UIDS = &H3D0D0102
   PR_SERVICES = &H3D0E0102
   PR_SERVICE_SUPPORT_FILES_W = &H3D0F101F
   PR_SERVICE_SUPPORT_FILES_A = &H3D0F101E
   PR_SERVICE_DELETE_FILES_W = &H3D10101F
   PR_SERVICE_DELETE_FILES_A = &H3D10101E
   PR_AB_SEARCH_PATH_UPDATE = &H3D110102
   PR_PROFILE_NAME_A = &H3D12001E
   PR_PROFILE_NAME_W = &H3D12001F
   PR_IDENTITY_DISPLAY_W = &H3E00001F
   PR_IDENTITY_DISPLAY_A = &H3E00001E
   PR_IDENTITY_ENTRYID = &H3E010102
   PR_RESOURCE_METHODS = &H3E020003
   PR_RESOURCE_TYPE = &H3E030003
   PR_STATUS_CODE = &H3E040003
   PR_IDENTITY_SEARCH_KEY = &H3E050102
   PR_OWN_STORE_ENTRYID = &H3E060102
   PR_RESOURCE_PATH_W = &H3E07001F
   PR_RESOURCE_PATH_A = &H3E07001E
   PR_STATUS_STRING_W = &H3E08001F
   PR_STATUS_STRING_A = &H3E08001E
   PR_X400_DEFERRED_DELIVERY_CANCEL = &H3E09000B
   PR_HEADER_FOLDER_ENTRYID = &H3E0A0102
   PR_REMOTE_PROGRESS = &H3E0B0003
   PR_REMOTE_PROGRESS_TEXT_W = &H3E0C001F
   PR_REMOTE_PROGRESS_TEXT_A = &H3E0C001E
   PR_REMOTE_VALIDATE_OK = &H3E0D000B
   PR_CONTROL_FLAGS = &H3F000003
   PR_CONTROL_STRUCTURE = &H3F010102
   PR_CONTROL_TYPE = &H3F020003
   PR_DELTAX = &H3F030003
   PR_DELTAY = &H3F040003
   PR_XPOS = &H3F050003
   PR_YPOS = &H3F060003
   PR_CONTROL_ID = &H3F070102
   PR_INITIAL_DETAILS_PANE = &H3F080003
   
   PR_SEND_INTERNET_ENCODING = &H3A710003
End Enum
Public Function kWabPropIDGroup(ByVal ID As Long) As String
   If ID < 1 Then
      kWabPropIDGroup = "<Invalid>"
   ElseIf ID <= &HBFF Then
      kWabPropIDGroup = "MAPI_defined envelope property"
   ElseIf ID <= &HDFF Then
      kWabPropIDGroup = "MAPI_defined per-recipient property"
   ElseIf ID <= &HFFF Then
      kWabPropIDGroup = "MAPI_defined non-transmittable property"
   ElseIf ID <= &H2FFF Then
      kWabPropIDGroup = "MAPI_defined message content property"
   ElseIf ID <= &H3FFF Then
      kWabPropIDGroup = "MAPI_defined property (usually not message or recipient)"
   ElseIf ID <= &H57FF Then
      kWabPropIDGroup = "Transport-defined envelope property"
   ElseIf ID <= &H5FFF Then
      kWabPropIDGroup = "Transport-defined per-recipient property"
   ElseIf ID <= &H65FF Then
      kWabPropIDGroup = "User-defined non-transmittable property"
   ElseIf ID <= &H67FF Then
      kWabPropIDGroup = "Provider-defined internal non-transmittable property"
   ElseIf ID <= &H7BFF Then
      kWabPropIDGroup = "Message class-defined content property"
   ElseIf ID <= &H7FFF Then
      kWabPropIDGroup = "Message class-defined non-transmittable property"
   Else
      kWabPropIDGroup = "User-defined Name-to-id mapped property"
   End If
End Function

Public Function kWabPropIDSubGroup(ByVal ID As Long) As String
   If ID < &H3000 Then
      kWabPropIDSubGroup = ""
   ElseIf ID < &H33FF Then
      kWabPropIDSubGroup = "Common property such as display name, entry ID"
   ElseIf ID < &H35FF Then
      kWabPropIDSubGroup = "Message store object"
   ElseIf ID < &H36FF Then
      kWabPropIDSubGroup = "Folder or AB container"
   ElseIf ID < &H38FF Then
      kWabPropIDSubGroup = "Attachment"
   ElseIf ID < &H39FF Then
      kWabPropIDSubGroup = "Address book object"
   ElseIf ID < &H3BFF Then
      kWabPropIDSubGroup = "Mail user"
   ElseIf ID < &H3CFF Then
      kWabPropIDSubGroup = "Distribution list"
   ElseIf ID < &H3DFF Then
      kWabPropIDSubGroup = "Profile section"
   ElseIf ID < &H3FFF Then
      kWabPropIDSubGroup = "Status object"
   Else
      kWabPropIDSubGroup = ""
   End If
End Function

Public Function kWabPropIsTransmittable(ByVal ID As Long) As Boolean
   kWabPropIsTransmittable = ID < &HE00&
   kWabPropIsTransmittable = kWabPropIsTransmittable Or (ID >= &H8000&)
   kWabPropIsTransmittable = kWabPropIsTransmittable Or ((ID >= &H1000&) And (ID < &H6000&))
   kWabPropIsTransmittable = kWabPropIsTransmittable Or ((ID >= &H6800&) And (ID < &H7C00&))
End Function

Public Function kWabPropTagName(ByVal Tag As kPropTags) As String
   Select Case Tag
      Case PR_ACKNOWLEDGEMENT_MODE
         kWabPropTagName = "ACKNOWLEDGEMENT_MODE"
      Case PR_ALTERNATE_RECIPIENT_ALLOWED
         kWabPropTagName = "ALTERNATE_RECIPIENT_ALLOWED"
      Case PR_AUTHORIZING_USERS
         kWabPropTagName = "AUTHORIZING_USERS"
      Case PR_AUTO_FORWARD_COMMENT_W
         kWabPropTagName = "AUTO_FORWARD_COMMENT_W"
      Case PR_AUTO_FORWARD_COMMENT_A
         kWabPropTagName = "AUTO_FORWARD_COMMENT_A"
      Case PR_AUTO_FORWARDED
         kWabPropTagName = "AUTO_FORWARDED"
      Case PR_CONTENT_CONFIDENTIALITY_ALGORITHM_ID
         kWabPropTagName = "CONTENT_CONFIDENTIALITY_ALGORITHM_ID"
      Case PR_CONTENT_CORRELATOR
         kWabPropTagName = "CONTENT_CORRELATOR"
      Case PR_CONTENT_IDENTIFIER_W
         kWabPropTagName = "CONTENT_IDENTIFIER_W"
      Case PR_CONTENT_IDENTIFIER_A
         kWabPropTagName = "CONTENT_IDENTIFIER_A"
      Case PR_CONTENT_LENGTH
         kWabPropTagName = "CONTENT_LENGTH"
      Case PR_CONTENT_RETURN_REQUESTED
         kWabPropTagName = "CONTENT_RETURN_REQUESTED"
      Case PR_CONVERSATION_KEY
         kWabPropTagName = "CONVERSATION_KEY"
      Case PR_CONVERSION_EITS
         kWabPropTagName = "CONVERSION_EITS"
      Case PR_CONVERSION_WITH_LOSS_PROHIBITED
         kWabPropTagName = "CONVERSION_WITH_LOSS_PROHIBITED"
      Case PR_CONVERTED_EITS
         kWabPropTagName = "CONVERTED_EITS"
      Case PR_DEFERRED_DELIVERY_TIME
         kWabPropTagName = "DEFERRED_DELIVERY_TIME"
      Case PR_DELIVER_TIME
         kWabPropTagName = "DELIVER_TIME"
      Case PR_DISCARD_REASON
         kWabPropTagName = "DISCARD_REASON"
      Case PR_DISCLOSURE_OF_RECIPIENTS
         kWabPropTagName = "DISCLOSURE_OF_RECIPIENTS"
      Case PR_DL_EXPANSION_HISTORY
         kWabPropTagName = "DL_EXPANSION_HISTORY"
      Case PR_DL_EXPANSION_PROHIBITED
         kWabPropTagName = "DL_EXPANSION_PROHIBITED"
      Case PR_EXPIRY_TIME
         kWabPropTagName = "EXPIRY_TIME"
      Case PR_IMPLICIT_CONVERSION_PROHIBITED
         kWabPropTagName = "IMPLICIT_CONVERSION_PROHIBITED"
      Case PR_IMPORTANCE
         kWabPropTagName = "IMPORTANCE"
      Case PR_IPM_ID
         kWabPropTagName = "IPM_ID"
      Case PR_LATEST_DELIVERY_TIME
         kWabPropTagName = "LATEST_DELIVERY_TIME"
      Case PR_MESSAGE_CLASS_W
         kWabPropTagName = "MESSAGE_CLASS_W"
      Case PR_MESSAGE_CLASS_A
         kWabPropTagName = "MESSAGE_CLASS_A"
      Case PR_MESSAGE_DELIVERY_ID
         kWabPropTagName = "MESSAGE_DELIVERY_ID"
      Case PR_MESSAGE_SECURITY_LABEL
         kWabPropTagName = "MESSAGE_SECURITY_LABEL"
      Case PR_OBSOLETED_IPMS
         kWabPropTagName = "OBSOLETED_IPMS"
      Case PR_ORIGINALLY_INTENDED_RECIPIENT_NAME
         kWabPropTagName = "ORIGINALLY_INTENDED_RECIPIENT_NAME"
      Case PR_ORIGINAL_EITS
         kWabPropTagName = "ORIGINAL_EITS"
      Case PR_ORIGINATOR_CERTIFICATE
         kWabPropTagName = "ORIGINATOR_CERTIFICATE"
      Case PR_ORIGINATOR_DELIVERY_REPORT_REQUESTED
         kWabPropTagName = "ORIGINATOR_DELIVERY_REPORT_REQUESTED"
      Case PR_ORIGINATOR_RETURN_ADDRESS
         kWabPropTagName = "ORIGINATOR_RETURN_ADDRESS"
      Case PR_PARENT_KEY
         kWabPropTagName = "PARENT_KEY"
      Case PR_PRIORITY
         kWabPropTagName = "PRIORITY"
      Case PR_ORIGIN_CHECK
         kWabPropTagName = "ORIGIN_CHECK"
      Case PR_PROOF_OF_SUBMISSION_REQUESTED
         kWabPropTagName = "PROOF_OF_SUBMISSION_REQUESTED"
      Case PR_READ_RECEIPT_REQUESTED
         kWabPropTagName = "READ_RECEIPT_REQUESTED"
      Case PR_RECEIPT_TIME
         kWabPropTagName = "RECEIPT_TIME"
      Case PR_RECIPIENT_REASSIGNMENT_PROHIBITED
         kWabPropTagName = "RECIPIENT_REASSIGNMENT_PROHIBITED"
      Case PR_REDIRECTION_HISTORY
         kWabPropTagName = "REDIRECTION_HISTORY"
      Case PR_RELATED_IPMS
         kWabPropTagName = "RELATED_IPMS"
      Case PR_ORIGINAL_SENSITIVITY
         kWabPropTagName = "ORIGINAL_SENSITIVITY"
      Case PR_LANGUAGES_W
         kWabPropTagName = "LANGUAGES_W"
      Case PR_LANGUAGES_A
         kWabPropTagName = "LANGUAGES_A"
      Case PR_REPLY_TIME
         kWabPropTagName = "REPLY_TIME"
      Case PR_REPORT_TAG
         kWabPropTagName = "REPORT_TAG"
      Case PR_REPORT_TIME
         kWabPropTagName = "REPORT_TIME"
      Case PR_RETURNED_IPM
         kWabPropTagName = "RETURNED_IPM"
      Case PR_SECURITY
         kWabPropTagName = "SECURITY"
      Case PR_INCOMPLETE_COPY
         kWabPropTagName = "INCOMPLETE_COPY"
      Case PR_SENSITIVITY
         kWabPropTagName = "SENSITIVITY"
      Case PR_SUBJECT_W
         kWabPropTagName = "SUBJECT_W"
      Case PR_SUBJECT_A
         kWabPropTagName = "SUBJECT_A"
      Case PR_SUBJECT_IPM
         kWabPropTagName = "SUBJECT_IPM"
      Case PR_CLIENT_SUBMIT_TIME
         kWabPropTagName = "CLIENT_SUBMIT_TIME"
      Case PR_REPORT_NAME_W
         kWabPropTagName = "REPORT_NAME_W"
      Case PR_REPORT_NAME_A
         kWabPropTagName = "REPORT_NAME_A"
      Case PR_SENT_REPRESENTING_SEARCH_KEY
         kWabPropTagName = "SENT_REPRESENTING_SEARCH_KEY"
      Case PR_X400_CONTENT_TYPE
         kWabPropTagName = "X400_CONTENT_TYPE"
      Case PR_SUBJECT_PREFIX_W
         kWabPropTagName = "SUBJECT_PREFIX_W"
      Case PR_SUBJECT_PREFIX_A
         kWabPropTagName = "SUBJECT_PREFIX_A"
      Case PR_NON_RECEIPT_REASON
         kWabPropTagName = "NON_RECEIPT_REASON"
      Case PR_RECEIVED_BY_ENTRYID
         kWabPropTagName = "RECEIVED_BY_ENTRYID"
      Case PR_RECEIVED_BY_NAME_W
         kWabPropTagName = "RECEIVED_BY_NAME_W"
      Case PR_RECEIVED_BY_NAME_A
         kWabPropTagName = "RECEIVED_BY_NAME_A"
      Case PR_SENT_REPRESENTING_ENTRYID
         kWabPropTagName = "SENT_REPRESENTING_ENTRYID"
      Case PR_SENT_REPRESENTING_NAME_W
         kWabPropTagName = "SENT_REPRESENTING_NAME_W"
      Case PR_SENT_REPRESENTING_NAME_A
         kWabPropTagName = "SENT_REPRESENTING_NAME_A"
      Case PR_RCVD_REPRESENTING_ENTRYID
         kWabPropTagName = "RCVD_REPRESENTING_ENTRYID"
      Case PR_RCVD_REPRESENTING_NAME_W
         kWabPropTagName = "RCVD_REPRESENTING_NAME_W"
      Case PR_RCVD_REPRESENTING_NAME_A
         kWabPropTagName = "RCVD_REPRESENTING_NAME_A"
      Case PR_REPORT_ENTRYID
         kWabPropTagName = "REPORT_ENTRYID"
      Case PR_READ_RECEIPT_ENTRYID
         kWabPropTagName = "READ_RECEIPT_ENTRYID"
      Case PR_MESSAGE_SUBMISSION_ID
         kWabPropTagName = "MESSAGE_SUBMISSION_ID"
      Case PR_PROVIDER_SUBMIT_TIME
         kWabPropTagName = "PROVIDER_SUBMIT_TIME"
      Case PR_ORIGINAL_SUBJECT_W
         kWabPropTagName = "ORIGINAL_SUBJECT_W"
      Case PR_ORIGINAL_SUBJECT_A
         kWabPropTagName = "ORIGINAL_SUBJECT_A"
      Case PR_DISC_VAL
         kWabPropTagName = "DISC_VAL"
      Case PR_ORIG_MESSAGE_CLASS_W
         kWabPropTagName = "ORIG_MESSAGE_CLASS_W"
      Case PR_ORIG_MESSAGE_CLASS_A
         kWabPropTagName = "ORIG_MESSAGE_CLASS_A"
      Case PR_ORIGINAL_AUTHOR_ENTRYID
         kWabPropTagName = "ORIGINAL_AUTHOR_ENTRYID"
      Case PR_ORIGINAL_AUTHOR_NAME_W
         kWabPropTagName = "ORIGINAL_AUTHOR_NAME_W"
      Case PR_ORIGINAL_AUTHOR_NAME_A
         kWabPropTagName = "ORIGINAL_AUTHOR_NAME_A"
      Case PR_ORIGINAL_SUBMIT_TIME
         kWabPropTagName = "ORIGINAL_SUBMIT_TIME"
      Case PR_REPLY_RECIPIENT_ENTRIES
         kWabPropTagName = "REPLY_RECIPIENT_ENTRIES"
      Case PR_REPLY_RECIPIENT_NAMES_W
         kWabPropTagName = "REPLY_RECIPIENT_NAMES_W"
      Case PR_REPLY_RECIPIENT_NAMES_A
         kWabPropTagName = "REPLY_RECIPIENT_NAMES_A"
      Case PR_RECEIVED_BY_SEARCH_KEY
         kWabPropTagName = "RECEIVED_BY_SEARCH_KEY"
      Case PR_RCVD_REPRESENTING_SEARCH_KEY
         kWabPropTagName = "RCVD_REPRESENTING_SEARCH_KEY"
      Case PR_READ_RECEIPT_SEARCH_KEY
         kWabPropTagName = "READ_RECEIPT_SEARCH_KEY"
      Case PR_REPORT_SEARCH_KEY
         kWabPropTagName = "REPORT_SEARCH_KEY"
      Case PR_ORIGINAL_DELIVERY_TIME
         kWabPropTagName = "ORIGINAL_DELIVERY_TIME"
      Case PR_ORIGINAL_AUTHOR_SEARCH_KEY
         kWabPropTagName = "ORIGINAL_AUTHOR_SEARCH_KEY"
      Case PR_MESSAGE_TO_ME
         kWabPropTagName = "MESSAGE_TO_ME"
      Case PR_MESSAGE_CC_ME
         kWabPropTagName = "MESSAGE_CC_ME"
      Case PR_MESSAGE_RECIP_ME
         kWabPropTagName = "MESSAGE_RECIP_ME"
      Case PR_ORIGINAL_SENDER_NAME_W
         kWabPropTagName = "ORIGINAL_SENDER_NAME_W"
      Case PR_ORIGINAL_SENDER_NAME_A
         kWabPropTagName = "ORIGINAL_SENDER_NAME_A"
      Case PR_ORIGINAL_SENDER_ENTRYID
         kWabPropTagName = "ORIGINAL_SENDER_ENTRYID"
      Case PR_ORIGINAL_SENDER_SEARCH_KEY
         kWabPropTagName = "ORIGINAL_SENDER_SEARCH_KEY"
      Case PR_ORIGINAL_SENT_REPRESENTING_NAME_W
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_NAME_W"
      Case PR_ORIGINAL_SENT_REPRESENTING_NAME_A
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_NAME_A"
      Case PR_ORIGINAL_SENT_REPRESENTING_ENTRYID
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_ENTRYID"
      Case PR_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_SEARCH_KEY"
      Case PR_START_DATE
         kWabPropTagName = "START_DATE"
      Case PR_END_DATE
         kWabPropTagName = "END_DATE"
      Case PR_OWNER_APPT_ID
         kWabPropTagName = "OWNER_APPT_ID"
      Case PR_RESPONSE_REQUESTED
         kWabPropTagName = "RESPONSE_REQUESTED"
      Case PR_SENT_REPRESENTING_ADDRTYPE_W
         kWabPropTagName = "SENT_REPRESENTING_ADDRTYPE_W"
      Case PR_SENT_REPRESENTING_ADDRTYPE_A
         kWabPropTagName = "SENT_REPRESENTING_ADDRTYPE_A"
      Case PR_SENT_REPRESENTING_EMAIL_ADDRESS_W
         kWabPropTagName = "SENT_REPRESENTING_EMAIL_ADDRESS_W"
      Case PR_SENT_REPRESENTING_EMAIL_ADDRESS_A
         kWabPropTagName = "SENT_REPRESENTING_EMAIL_ADDRESS_A"
      Case PR_ORIGINAL_SENDER_ADDRTYPE_W
         kWabPropTagName = "ORIGINAL_SENDER_ADDRTYPE_W"
      Case PR_ORIGINAL_SENDER_ADDRTYPE_A
         kWabPropTagName = "ORIGINAL_SENDER_ADDRTYPE_A"
      Case PR_ORIGINAL_SENDER_EMAIL_ADDRESS_W
         kWabPropTagName = "ORIGINAL_SENDER_EMAIL_ADDRESS_W"
      Case PR_ORIGINAL_SENDER_EMAIL_ADDRESS_A
         kWabPropTagName = "ORIGINAL_SENDER_EMAIL_ADDRESS_A"
      Case PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_W
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_ADDRTYPE_W"
      Case PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_A
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_ADDRTYPE_A"
      Case PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_W
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_W"
      Case PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_A
         kWabPropTagName = "ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_A"
      Case PR_CONVERSATION_TOPIC_W
         kWabPropTagName = "CONVERSATION_TOPIC_W"
      Case PR_CONVERSATION_TOPIC_A
         kWabPropTagName = "CONVERSATION_TOPIC_A"
      Case PR_CONVERSATION_INDEX
         kWabPropTagName = "CONVERSATION_INDEX"
      Case PR_ORIGINAL_DISPLAY_BCC_W
         kWabPropTagName = "ORIGINAL_DISPLAY_BCC_W"
      Case PR_ORIGINAL_DISPLAY_BCC_A
         kWabPropTagName = "ORIGINAL_DISPLAY_BCC_A"
      Case PR_ORIGINAL_DISPLAY_CC_W
         kWabPropTagName = "ORIGINAL_DISPLAY_CC_W"
      Case PR_ORIGINAL_DISPLAY_CC_A
         kWabPropTagName = "ORIGINAL_DISPLAY_CC_A"
      Case PR_ORIGINAL_DISPLAY_TO_W
         kWabPropTagName = "ORIGINAL_DISPLAY_TO_W"
      Case PR_ORIGINAL_DISPLAY_TO_A
         kWabPropTagName = "ORIGINAL_DISPLAY_TO_A"
      Case PR_RECEIVED_BY_ADDRTYPE_W
         kWabPropTagName = "RECEIVED_BY_ADDRTYPE_W"
      Case PR_RECEIVED_BY_ADDRTYPE_A
         kWabPropTagName = "RECEIVED_BY_ADDRTYPE_A"
      Case PR_RECEIVED_BY_EMAIL_ADDRESS_W
         kWabPropTagName = "RECEIVED_BY_EMAIL_ADDRESS_W"
      Case PR_RECEIVED_BY_EMAIL_ADDRESS_A
         kWabPropTagName = "RECEIVED_BY_EMAIL_ADDRESS_A"
      Case PR_RCVD_REPRESENTING_ADDRTYPE_W
         kWabPropTagName = "RCVD_REPRESENTING_ADDRTYPE_W"
      Case PR_RCVD_REPRESENTING_ADDRTYPE_A
         kWabPropTagName = "RCVD_REPRESENTING_ADDRTYPE_A"
      Case PR_RCVD_REPRESENTING_EMAIL_ADDRESS_W
         kWabPropTagName = "RCVD_REPRESENTING_EMAIL_ADDRESS_W"
      Case PR_RCVD_REPRESENTING_EMAIL_ADDRESS_A
         kWabPropTagName = "RCVD_REPRESENTING_EMAIL_ADDRESS_A"
      Case PR_ORIGINAL_AUTHOR_ADDRTYPE_W
         kWabPropTagName = "ORIGINAL_AUTHOR_ADDRTYPE_W"
      Case PR_ORIGINAL_AUTHOR_ADDRTYPE_A
         kWabPropTagName = "ORIGINAL_AUTHOR_ADDRTYPE_A"
      Case PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_W
         kWabPropTagName = "ORIGINAL_AUTHOR_EMAIL_ADDRESS_W"
      Case PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_A
         kWabPropTagName = "ORIGINAL_AUTHOR_EMAIL_ADDRESS_A"
      Case PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_W
         kWabPropTagName = "ORIGINALLY_INTENDED_RECIP_ADDRTYPE_W"
      Case PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_A
         kWabPropTagName = "ORIGINALLY_INTENDED_RECIP_ADDRTYPE_A"
      Case PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_W
         kWabPropTagName = "ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_W"
      Case PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_A
         kWabPropTagName = "ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_A"
      Case PR_TRANSPORT_MESSAGE_HEADERS_W
         kWabPropTagName = "TRANSPORT_MESSAGE_HEADERS_W"
      Case PR_TRANSPORT_MESSAGE_HEADERS_A
         kWabPropTagName = "TRANSPORT_MESSAGE_HEADERS_A"
      Case PR_DELEGATION
         kWabPropTagName = "DELEGATION"
      Case PR_TNEF_CORRELATION_KEY
         kWabPropTagName = "TNEF_CORRELATION_KEY"
      Case PR_BODY_W
         kWabPropTagName = "BODY_W"
      Case PR_BODY_A
         kWabPropTagName = "BODY_A"
      Case PR_REPORT_TEXT_W
         kWabPropTagName = "REPORT_TEXT_W"
      Case PR_REPORT_TEXT_A
         kWabPropTagName = "REPORT_TEXT_A"
      Case PR_ORIGINATOR_AND_DL_EXPANSION_HISTORY
         kWabPropTagName = "ORIGINATOR_AND_DL_EXPANSION_HISTORY"
      Case PR_REPORTING_DL_NAME
         kWabPropTagName = "REPORTING_DL_NAME"
      Case PR_REPORTING_MTA_CERTIFICATE
         kWabPropTagName = "REPORTING_MTA_CERTIFICATE"
      Case PR_RTF_SYNC_BODY_CRC
         kWabPropTagName = "RTF_SYNC_BODY_CRC"
      Case PR_RTF_SYNC_BODY_COUNT
         kWabPropTagName = "RTF_SYNC_BODY_COUNT"
      Case PR_RTF_SYNC_BODY_TAG_W
         kWabPropTagName = "RTF_SYNC_BODY_TAG_W"
      Case PR_RTF_SYNC_BODY_TAG_A
         kWabPropTagName = "RTF_SYNC_BODY_TAG_A"
      Case PR_RTF_COMPRESSED
         kWabPropTagName = "RTF_COMPRESSED"
      Case PR_RTF_SYNC_PREFIX_COUNT
         kWabPropTagName = "RTF_SYNC_PREFIX_COUNT"
      Case PR_RTF_SYNC_TRAILING_COUNT
         kWabPropTagName = "RTF_SYNC_TRAILING_COUNT"
      Case PR_ORIGINALLY_INTENDED_RECIP_ENTRYID
         kWabPropTagName = "ORIGINALLY_INTENDED_RECIP_ENTRYID"
      Case PR_CONTENT_INTEGRITY_CHECK
         kWabPropTagName = "CONTENT_INTEGRITY_CHECK"
      Case PR_EXPLICIT_CONVERSION
         kWabPropTagName = "EXPLICIT_CONVERSION"
      Case PR_IPM_RETURN_REQUESTED
         kWabPropTagName = "IPM_RETURN_REQUESTED"
      Case PR_MESSAGE_TOKEN
         kWabPropTagName = "MESSAGE_TOKEN"
      Case PR_NDR_REASON_CODE
         kWabPropTagName = "NDR_REASON_CODE"
      Case PR_NDR_DIAG_CODE
         kWabPropTagName = "NDR_DIAG_CODE"
      Case PR_NON_RECEIPT_NOTIFICATION_REQUESTED
         kWabPropTagName = "NON_RECEIPT_NOTIFICATION_REQUESTED"
      Case PR_DELIVERY_POINT
         kWabPropTagName = "DELIVERY_POINT"
      Case PR_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED
         kWabPropTagName = "ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED"
      Case PR_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT
         kWabPropTagName = "ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT"
      Case PR_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY
         kWabPropTagName = "PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY"
      Case PR_PHYSICAL_DELIVERY_MODE
         kWabPropTagName = "PHYSICAL_DELIVERY_MODE"
      Case PR_PHYSICAL_DELIVERY_REPORT_REQUEST
         kWabPropTagName = "PHYSICAL_DELIVERY_REPORT_REQUEST"
      Case PR_PHYSICAL_FORWARDING_ADDRESS
         kWabPropTagName = "PHYSICAL_FORWARDING_ADDRESS"
      Case PR_PHYSICAL_FORWARDING_ADDRESS_REQUESTED
         kWabPropTagName = "PHYSICAL_FORWARDING_ADDRESS_REQUESTED"
      Case PR_PHYSICAL_FORWARDING_PROHIBITED
         kWabPropTagName = "PHYSICAL_FORWARDING_PROHIBITED"
      Case PR_PHYSICAL_RENDITION_ATTRIBUTES
         kWabPropTagName = "PHYSICAL_RENDITION_ATTRIBUTES"
      Case PR_PROOF_OF_DELIVERY
         kWabPropTagName = "PROOF_OF_DELIVERY"
      Case PR_PROOF_OF_DELIVERY_REQUESTED
         kWabPropTagName = "PROOF_OF_DELIVERY_REQUESTED"
      Case PR_RECIPIENT_CERTIFICATE
         kWabPropTagName = "RECIPIENT_CERTIFICATE"
      Case PR_RECIPIENT_NUMBER_FOR_ADVICE_W
         kWabPropTagName = "RECIPIENT_NUMBER_FOR_ADVICE_W"
      Case PR_RECIPIENT_NUMBER_FOR_ADVICE_A
         kWabPropTagName = "RECIPIENT_NUMBER_FOR_ADVICE_A"
      Case PR_RECIPIENT_TYPE
         kWabPropTagName = "RECIPIENT_TYPE"
      Case PR_REGISTERED_MAIL_TYPE
         kWabPropTagName = "REGISTERED_MAIL_TYPE"
      Case PR_REPLY_REQUESTED
         kWabPropTagName = "REPLY_REQUESTED"
      Case PR_REQUESTED_DELIVERY_METHOD
         kWabPropTagName = "REQUESTED_DELIVERY_METHOD"
      Case PR_SENDER_ENTRYID
         kWabPropTagName = "SENDER_ENTRYID"
      Case PR_SENDER_NAME_W
         kWabPropTagName = "SENDER_NAME_W"
      Case PR_SENDER_NAME_A
         kWabPropTagName = "SENDER_NAME_A"
      Case PR_SUPPLEMENTARY_INFO_W
         kWabPropTagName = "SUPPLEMENTARY_INFO_W"
      Case PR_SUPPLEMENTARY_INFO_A
         kWabPropTagName = "SUPPLEMENTARY_INFO_A"
      Case PR_TYPE_OF_MTS_USER
         kWabPropTagName = "TYPE_OF_MTS_USER"
      Case PR_SENDER_SEARCH_KEY
         kWabPropTagName = "SENDER_SEARCH_KEY"
      Case PR_SENDER_ADDRTYPE_W
         kWabPropTagName = "SENDER_ADDRTYPE_W"
      Case PR_SENDER_ADDRTYPE_A
         kWabPropTagName = "SENDER_ADDRTYPE_A"
      Case PR_SENDER_EMAIL_ADDRESS_W
         kWabPropTagName = "SENDER_EMAIL_ADDRESS_W"
      Case PR_SENDER_EMAIL_ADDRESS_A
         kWabPropTagName = "SENDER_EMAIL_ADDRESS_A"
      Case PR_CURRENT_VERSION
         kWabPropTagName = "CURRENT_VERSION"
      Case PR_DELETE_AFTER_SUBMIT
         kWabPropTagName = "DELETE_AFTER_SUBMIT"
      Case PR_DISPLAY_BCC_W
         kWabPropTagName = "DISPLAY_BCC_W"
      Case PR_DISPLAY_BCC_A
         kWabPropTagName = "DISPLAY_BCC_A"
      Case PR_DISPLAY_CC_W
         kWabPropTagName = "DISPLAY_CC_W"
      Case PR_DISPLAY_CC_A
         kWabPropTagName = "DISPLAY_CC_A"
      Case PR_DISPLAY_TO_W
         kWabPropTagName = "DISPLAY_TO_W"
      Case PR_DISPLAY_TO_A
         kWabPropTagName = "DISPLAY_TO_A"
      Case PR_PARENT_DISPLAY_W
         kWabPropTagName = "PARENT_DISPLAY_W"
      Case PR_PARENT_DISPLAY_A
         kWabPropTagName = "PARENT_DISPLAY_A"
      Case PR_MESSAGE_DELIVERY_TIME
         kWabPropTagName = "MESSAGE_DELIVERY_TIME"
      Case PR_MESSAGE_FLAGS
         kWabPropTagName = "MESSAGE_FLAGS"
      Case PR_MESSAGE_SIZE
         kWabPropTagName = "MESSAGE_SIZE"
      Case PR_PARENT_ENTRYID
         kWabPropTagName = "PARENT_ENTRYID"
      Case PR_SENTMAIL_ENTRYID
         kWabPropTagName = "SENTMAIL_ENTRYID"
      Case PR_CORRELATE
         kWabPropTagName = "CORRELATE"
      Case PR_CORRELATE_MTSID
         kWabPropTagName = "CORRELATE_MTSID"
      Case PR_DISCRETE_VALUES
         kWabPropTagName = "DISCRETE_VALUES"
      Case PR_RESPONSIBILITY
         kWabPropTagName = "RESPONSIBILITY"
      Case PR_SPOOLER_STATUS
         kWabPropTagName = "SPOOLER_STATUS"
      Case PR_TRANSPORT_STATUS
         kWabPropTagName = "TRANSPORT_STATUS"
      Case PR_MESSAGE_RECIPIENTS
         kWabPropTagName = "MESSAGE_RECIPIENTS"
      Case PR_MESSAGE_ATTACHMENTS
         kWabPropTagName = "MESSAGE_ATTACHMENTS"
      Case PR_SUBMIT_FLAGS
         kWabPropTagName = "SUBMIT_FLAGS"
      Case PR_RECIPIENT_STATUS
         kWabPropTagName = "RECIPIENT_STATUS"
      Case PR_TRANSPORT_KEY
         kWabPropTagName = "TRANSPORT_KEY"
      Case PR_MSG_STATUS
         kWabPropTagName = "MSG_STATUS"
      Case PR_MESSAGE_DOWNLOAD_TIME
         kWabPropTagName = "MESSAGE_DOWNLOAD_TIME"
      Case PR_CREATION_VERSION
         kWabPropTagName = "CREATION_VERSION"
      Case PR_MODIFY_VERSION
         kWabPropTagName = "MODIFY_VERSION"
      Case PR_HASATTACH
         kWabPropTagName = "HASATTACH"
      Case PR_BODY_CRC
         kWabPropTagName = "BODY_CRC"
      Case PR_NORMALIZED_SUBJECT_W
         kWabPropTagName = "NORMALIZED_SUBJECT_W"
      Case PR_NORMALIZED_SUBJECT_A
         kWabPropTagName = "NORMALIZED_SUBJECT_A"
      Case PR_RTF_IN_SYNC
         kWabPropTagName = "RTF_IN_SYNC"
      Case PR_ATTACH_SIZE
         kWabPropTagName = "ATTACH_SIZE"
      Case PR_ATTACH_NUM
         kWabPropTagName = "ATTACH_NUM"
      Case PR_PREPROCESS
         kWabPropTagName = "PREPROCESS"
      Case PR_ORIGINATING_MTA_CERTIFICATE
         kWabPropTagName = "ORIGINATING_MTA_CERTIFICATE"
      Case PR_PROOF_OF_SUBMISSION
         kWabPropTagName = "PROOF_OF_SUBMISSION"
      Case PR_ENTRYID
         kWabPropTagName = "ENTRYID"
      Case PR_OBJECT_TYPE
         kWabPropTagName = "OBJECT_TYPE"
      Case PR_ICON
         kWabPropTagName = "ICON"
      Case PR_MINI_ICON
         kWabPropTagName = "MINI_ICON"
      Case PR_STORE_ENTRYID
         kWabPropTagName = "STORE_ENTRYID"
      Case PR_STORE_RECORD_KEY
         kWabPropTagName = "STORE_RECORD_KEY"
      Case PR_RECORD_KEY
         kWabPropTagName = "RECORD_KEY"
      Case PR_MAPPING_SIGNATURE
         kWabPropTagName = "MAPPING_SIGNATURE"
      Case PR_ACCESS_LEVEL
         kWabPropTagName = "ACCESS_LEVEL"
      Case PR_INSTANCE_KEY
         kWabPropTagName = "INSTANCE_KEY"
      Case PR_ROW_TYPE
         kWabPropTagName = "ROW_TYPE"
      Case PR_ACCESS
         kWabPropTagName = "ACCESS"
      Case PR_ROWID
         kWabPropTagName = "ROWID"
      Case PR_DISPLAY_NAME_W
         kWabPropTagName = "DISPLAY_NAME_W"
      Case PR_DISPLAY_NAME_A
         kWabPropTagName = "DISPLAY_NAME_A"
      Case PR_ADDRTYPE_W
         kWabPropTagName = "ADDRTYPE_W"
      Case PR_ADDRTYPE_A
         kWabPropTagName = "ADDRTYPE_A"
      Case PR_EMAIL_ADDRESS_W
         kWabPropTagName = "EMAIL_ADDRESS_W"
      Case PR_EMAIL_ADDRESS_A
         kWabPropTagName = "EMAIL_ADDRESS_A"
      Case PR_COMMENT_W
         kWabPropTagName = "COMMENT_W"
      Case PR_COMMENT_A
         kWabPropTagName = "COMMENT_A"
      Case PR_DEPTH
         kWabPropTagName = "DEPTH"
      Case PR_PROVIDER_DISPLAY_W
         kWabPropTagName = "PROVIDER_DISPLAY_W"
      Case PR_PROVIDER_DISPLAY_A
         kWabPropTagName = "PROVIDER_DISPLAY_A"
      Case PR_CREATION_TIME
         kWabPropTagName = "CREATION_TIME"
      Case PR_LAST_MODIFICATION_TIME
         kWabPropTagName = "LAST_MODIFICATION_TIME"
      Case PR_RESOURCE_FLAGS
         kWabPropTagName = "RESOURCE_FLAGS"
      Case PR_PROVIDER_DLL_NAME_W
         kWabPropTagName = "PROVIDER_DLL_NAME_W"
      Case PR_PROVIDER_DLL_NAME_A
         kWabPropTagName = "PROVIDER_DLL_NAME_A"
      Case PR_SEARCH_KEY
         kWabPropTagName = "SEARCH_KEY"
      Case PR_PROVIDER_UID
         kWabPropTagName = "PROVIDER_UID"
      Case PR_PROVIDER_ORDINAL
         kWabPropTagName = "PROVIDER_ORDINAL"
      Case PR_FORM_VERSION_W
         kWabPropTagName = "FORM_VERSION_W"
      Case PR_FORM_VERSION_A
         kWabPropTagName = "FORM_VERSION_A"
      Case PR_FORM_CLSID
         kWabPropTagName = "FORM_CLSID"
      Case PR_FORM_CONTACT_NAME_W
         kWabPropTagName = "FORM_CONTACT_NAME_W"
      Case PR_FORM_CONTACT_NAME_A
         kWabPropTagName = "FORM_CONTACT_NAME_A"
      Case PR_FORM_CATEGORY_W
         kWabPropTagName = "FORM_CATEGORY_W"
      Case PR_FORM_CATEGORY_A
         kWabPropTagName = "FORM_CATEGORY_A"
      Case PR_FORM_CATEGORY_SUB_W
         kWabPropTagName = "FORM_CATEGORY_SUB_W"
      Case PR_FORM_CATEGORY_SUB_A
         kWabPropTagName = "FORM_CATEGORY_SUB_A"
      Case PR_FORM_HOST_MAP
         kWabPropTagName = "FORM_HOST_MAP"
      Case PR_FORM_HIDDEN
         kWabPropTagName = "FORM_HIDDEN"
      Case PR_FORM_DESIGNER_NAME_W
         kWabPropTagName = "FORM_DESIGNER_NAME_W"
      Case PR_FORM_DESIGNER_NAME_A
         kWabPropTagName = "FORM_DESIGNER_NAME_A"
      Case PR_FORM_DESIGNER_GUID
         kWabPropTagName = "FORM_DESIGNER_GUID"
      Case PR_FORM_MESSAGE_BEHAVIOR
         kWabPropTagName = "FORM_MESSAGE_BEHAVIOR"
      Case PR_DEFAULT_STORE
         kWabPropTagName = "DEFAULT_STORE"
      Case PR_STORE_SUPPORT_MASK
         kWabPropTagName = "STORE_SUPPORT_MASK"
      Case PR_STORE_STATE
         kWabPropTagName = "STORE_STATE"
      Case PR_IPM_SUBTREE_SEARCH_KEY
         kWabPropTagName = "IPM_SUBTREE_SEARCH_KEY"
      Case PR_IPM_OUTBOX_SEARCH_KEY
         kWabPropTagName = "IPM_OUTBOX_SEARCH_KEY"
      Case PR_IPM_WASTEBASKET_SEARCH_KEY
         kWabPropTagName = "IPM_WASTEBASKET_SEARCH_KEY"
      Case PR_IPM_SENTMAIL_SEARCH_KEY
         kWabPropTagName = "IPM_SENTMAIL_SEARCH_KEY"
      Case PR_MDB_PROVIDER
         kWabPropTagName = "MDB_PROVIDER"
      Case PR_RECEIVE_FOLDER_SETTINGS
         kWabPropTagName = "RECEIVE_FOLDER_SETTINGS"
      Case PR_VALID_FOLDER_MASK
         kWabPropTagName = "VALID_FOLDER_MASK"
      Case PR_IPM_SUBTREE_ENTRYID
         kWabPropTagName = "IPM_SUBTREE_ENTRYID"
      Case PR_IPM_OUTBOX_ENTRYID
         kWabPropTagName = "IPM_OUTBOX_ENTRYID"
      Case PR_IPM_WASTEBASKET_ENTRYID
         kWabPropTagName = "IPM_WASTEBASKET_ENTRYID"
      Case PR_IPM_SENTMAIL_ENTRYID
         kWabPropTagName = "IPM_SENTMAIL_ENTRYID"
      Case PR_VIEWS_ENTRYID
         kWabPropTagName = "VIEWS_ENTRYID"
      Case PR_COMMON_VIEWS_ENTRYID
         kWabPropTagName = "COMMON_VIEWS_ENTRYID"
      Case PR_FINDER_ENTRYID
         kWabPropTagName = "FINDER_ENTRYID"
      Case PR_CONTAINER_FLAGS
         kWabPropTagName = "CONTAINER_FLAGS"
      Case PR_FOLDER_TYPE
         kWabPropTagName = "FOLDER_TYPE"
      Case PR_CONTENT_COUNT
         kWabPropTagName = "CONTENT_COUNT"
      Case PR_CONTENT_UNREAD
         kWabPropTagName = "CONTENT_UNREAD"
      Case PR_CREATE_TEMPLATES
         kWabPropTagName = "CREATE_TEMPLATES"
      Case PR_DETAILS_TABLE
         kWabPropTagName = "DETAILS_TABLE"
      Case PR_SEARCH
         kWabPropTagName = "SEARCH"
      Case PR_SELECTABLE
         kWabPropTagName = "SELECTABLE"
      Case PR_SUBFOLDERS
         kWabPropTagName = "SUBFOLDERS"
      Case PR_STATUS
         kWabPropTagName = "STATUS"
      Case PR_ANR_W
         kWabPropTagName = "ANR_W"
      Case PR_ANR_A
         kWabPropTagName = "ANR_A"
      Case PR_CONTENTS_SORT_ORDER
         kWabPropTagName = "CONTENTS_SORT_ORDER"
      Case PR_CONTAINER_HIERARCHY
         kWabPropTagName = "CONTAINER_HIERARCHY"
      Case PR_CONTAINER_CONTENTS
         kWabPropTagName = "CONTAINER_CONTENTS"
      Case PR_FOLDER_ASSOCIATED_CONTENTS
         kWabPropTagName = "FOLDER_ASSOCIATED_CONTENTS"
      Case PR_DEF_CREATE_DL
         kWabPropTagName = "DEF_CREATE_DL"
      Case PR_DEF_CREATE_MAILUSER
         kWabPropTagName = "DEF_CREATE_MAILUSER"
      Case PR_CONTAINER_CLASS_W
         kWabPropTagName = "CONTAINER_CLASS_W"
      Case PR_CONTAINER_CLASS_A
         kWabPropTagName = "CONTAINER_CLASS_A"
      Case PR_CONTAINER_MODIFY_VERSION
         kWabPropTagName = "CONTAINER_MODIFY_VERSION"
      Case PR_AB_PROVIDER_ID
         kWabPropTagName = "AB_PROVIDER_ID"
      Case PR_DEFAULT_VIEW_ENTRYID
         kWabPropTagName = "DEFAULT_VIEW_ENTRYID"
      Case PR_ASSOC_CONTENT_COUNT
         kWabPropTagName = "ASSOC_CONTENT_COUNT"
      Case PR_ATTACHMENT_X400_PARAMETERS
         kWabPropTagName = "ATTACHMENT_X400_PARAMETERS"
      Case PR_ATTACH_DATA_OBJ
         kWabPropTagName = "ATTACH_DATA_OBJ"
      Case PR_ATTACH_DATA_BIN
         kWabPropTagName = "ATTACH_DATA_BIN"
      Case PR_ATTACH_ENCODING
         kWabPropTagName = "ATTACH_ENCODING"
      Case PR_ATTACH_EXTENSION_W
         kWabPropTagName = "ATTACH_EXTENSION_W"
      Case PR_ATTACH_EXTENSION_A
         kWabPropTagName = "ATTACH_EXTENSION_A"
      Case PR_ATTACH_FILENAME_W
         kWabPropTagName = "ATTACH_FILENAME_W"
      Case PR_ATTACH_FILENAME_A
         kWabPropTagName = "ATTACH_FILENAME_A"
      Case PR_ATTACH_METHOD
         kWabPropTagName = "ATTACH_METHOD"
      Case PR_ATTACH_LONG_FILENAME_W
         kWabPropTagName = "ATTACH_LONG_FILENAME_W"
      Case PR_ATTACH_LONG_FILENAME_A
         kWabPropTagName = "ATTACH_LONG_FILENAME_A"
      Case PR_ATTACH_PATHNAME_W
         kWabPropTagName = "ATTACH_PATHNAME_W"
      Case PR_ATTACH_PATHNAME_A
         kWabPropTagName = "ATTACH_PATHNAME_A"
      Case PR_ATTACH_RENDERING
         kWabPropTagName = "ATTACH_RENDERING"
      Case PR_ATTACH_TAG
         kWabPropTagName = "ATTACH_TAG"
      Case PR_RENDERING_POSITION
         kWabPropTagName = "RENDERING_POSITION"
      Case PR_ATTACH_TRANSPORT_NAME_W
         kWabPropTagName = "ATTACH_TRANSPORT_NAME_W"
      Case PR_ATTACH_TRANSPORT_NAME_A
         kWabPropTagName = "ATTACH_TRANSPORT_NAME_A"
      Case PR_ATTACH_LONG_PATHNAME_W
         kWabPropTagName = "ATTACH_LONG_PATHNAME_W"
      Case PR_ATTACH_LONG_PATHNAME_A
         kWabPropTagName = "ATTACH_LONG_PATHNAME_A"
      Case PR_ATTACH_MIME_TAG_W
         kWabPropTagName = "ATTACH_MIME_TAG_W"
      Case PR_ATTACH_MIME_TAG_A
         kWabPropTagName = "ATTACH_MIME_TAG_A"
      Case PR_ATTACH_ADDITIONAL_INFO
         kWabPropTagName = "ATTACH_ADDITIONAL_INFO"
      Case PR_DISPLAY_TYPE
         kWabPropTagName = "DISPLAY_TYPE"
      Case PR_TEMPLATEID
         kWabPropTagName = "TEMPLATEID"
      Case PR_PRIMARY_CAPABILITY
         kWabPropTagName = "PRIMARY_CAPABILITY"
      Case PR_7BIT_DISPLAY_NAME
         kWabPropTagName = "7BIT_DISPLAY_NAME"
      Case PR_ACCOUNT_W
         kWabPropTagName = "ACCOUNT_W"
      Case PR_ACCOUNT_A
         kWabPropTagName = "ACCOUNT_A"
      Case PR_ALTERNATE_RECIPIENT
         kWabPropTagName = "ALTERNATE_RECIPIENT"
      Case PR_CALLBACK_TELEPHONE_NUMBER_W
         kWabPropTagName = "CALLBACK_TELEPHONE_NUMBER_W"
      Case PR_CALLBACK_TELEPHONE_NUMBER_A
         kWabPropTagName = "CALLBACK_TELEPHONE_NUMBER_A"
      Case PR_CONVERSION_PROHIBITED
         kWabPropTagName = "CONVERSION_PROHIBITED"
      Case PR_DISCLOSE_RECIPIENTS
         kWabPropTagName = "DISCLOSE_RECIPIENTS"
      Case PR_GENERATION_W
         kWabPropTagName = "GENERATION_W"
      Case PR_GENERATION_A
         kWabPropTagName = "GENERATION_A"
      Case PR_GIVEN_NAME_W
         kWabPropTagName = "GIVEN_NAME_W"
      Case PR_GIVEN_NAME_A
         kWabPropTagName = "GIVEN_NAME_A"
      Case PR_GOVERNMENT_ID_NUMBER_W
         kWabPropTagName = "GOVERNMENT_ID_NUMBER_W"
      Case PR_GOVERNMENT_ID_NUMBER_A
         kWabPropTagName = "GOVERNMENT_ID_NUMBER_A"
      Case PR_BUSINESS_TELEPHONE_NUMBER_W
         kWabPropTagName = "BUSINESS_TELEPHONE_NUMBER_W"
      Case PR_BUSINESS_TELEPHONE_NUMBER_A
         kWabPropTagName = "BUSINESS_TELEPHONE_NUMBER_A"
      Case PR_HOME_TELEPHONE_NUMBER_W
         kWabPropTagName = "HOME_TELEPHONE_NUMBER_W"
      Case PR_HOME_TELEPHONE_NUMBER_A
         kWabPropTagName = "HOME_TELEPHONE_NUMBER_A"
      Case PR_INITIALS_W
         kWabPropTagName = "INITIALS_W"
      Case PR_INITIALS_A
         kWabPropTagName = "INITIALS_A"
      Case PR_KEYWORD_W
         kWabPropTagName = "KEYWORD_W"
      Case PR_KEYWORD_A
         kWabPropTagName = "KEYWORD_A"
      Case PR_LANGUAGE_W
         kWabPropTagName = "LANGUAGE_W"
      Case PR_LANGUAGE_A
         kWabPropTagName = "LANGUAGE_A"
      Case PR_LOCATION_W
         kWabPropTagName = "LOCATION_W"
      Case PR_LOCATION_A
         kWabPropTagName = "LOCATION_A"
      Case PR_MAIL_PERMISSION
         kWabPropTagName = "MAIL_PERMISSION"
      Case PR_MHS_COMMON_NAME_W
         kWabPropTagName = "MHS_COMMON_NAME_W"
      Case PR_MHS_COMMON_NAME_A
         kWabPropTagName = "MHS_COMMON_NAME_A"
      Case PR_ORGANIZATIONAL_ID_NUMBER_W
         kWabPropTagName = "ORGANIZATIONAL_ID_NUMBER_W"
      Case PR_ORGANIZATIONAL_ID_NUMBER_A
         kWabPropTagName = "ORGANIZATIONAL_ID_NUMBER_A"
      Case PR_SURNAME_W
         kWabPropTagName = "SURNAME_W"
      Case PR_SURNAME_A
         kWabPropTagName = "SURNAME_A"
      Case PR_ORIGINAL_ENTRYID
         kWabPropTagName = "ORIGINAL_ENTRYID"
      Case PR_ORIGINAL_DISPLAY_NAME_W
         kWabPropTagName = "ORIGINAL_DISPLAY_NAME_W"
      Case PR_ORIGINAL_DISPLAY_NAME_A
         kWabPropTagName = "ORIGINAL_DISPLAY_NAME_A"
      Case PR_ORIGINAL_SEARCH_KEY
         kWabPropTagName = "ORIGINAL_SEARCH_KEY"
      Case PR_POSTAL_ADDRESS_W
         kWabPropTagName = "POSTAL_ADDRESS_W"
      Case PR_POSTAL_ADDRESS_A
         kWabPropTagName = "POSTAL_ADDRESS_A"
      Case PR_COMPANY_NAME_W
         kWabPropTagName = "COMPANY_NAME_W"
      Case PR_COMPANY_NAME_A
         kWabPropTagName = "COMPANY_NAME_A"
      Case PR_TITLE_W
         kWabPropTagName = "TITLE_W"
      Case PR_TITLE_A
         kWabPropTagName = "TITLE_A"
      Case PR_DEPARTMENT_NAME_W
         kWabPropTagName = "DEPARTMENT_NAME_W"
      Case PR_DEPARTMENT_NAME_A
         kWabPropTagName = "DEPARTMENT_NAME_A"
      Case PR_OFFICE_LOCATION_W
         kWabPropTagName = "OFFICE_LOCATION_W"
      Case PR_OFFICE_LOCATION_A
         kWabPropTagName = "OFFICE_LOCATION_A"
      Case PR_PRIMARY_TELEPHONE_NUMBER_W
         kWabPropTagName = "PRIMARY_TELEPHONE_NUMBER_W"
      Case PR_PRIMARY_TELEPHONE_NUMBER_A
         kWabPropTagName = "PRIMARY_TELEPHONE_NUMBER_A"
      Case PR_BUSINESS2_TELEPHONE_NUMBER_W
         kWabPropTagName = "BUSINESS2_TELEPHONE_NUMBER_W"
      Case PR_BUSINESS2_TELEPHONE_NUMBER_A
         kWabPropTagName = "BUSINESS2_TELEPHONE_NUMBER_A"
      Case PR_MOBILE_TELEPHONE_NUMBER_W
         kWabPropTagName = "MOBILE_TELEPHONE_NUMBER_W"
      Case PR_MOBILE_TELEPHONE_NUMBER_A
         kWabPropTagName = "MOBILE_TELEPHONE_NUMBER_A"
      Case PR_RADIO_TELEPHONE_NUMBER_W
         kWabPropTagName = "RADIO_TELEPHONE_NUMBER_W"
      Case PR_RADIO_TELEPHONE_NUMBER_A
         kWabPropTagName = "RADIO_TELEPHONE_NUMBER_A"
      Case PR_CAR_TELEPHONE_NUMBER_W
         kWabPropTagName = "CAR_TELEPHONE_NUMBER_W"
      Case PR_CAR_TELEPHONE_NUMBER_A
         kWabPropTagName = "CAR_TELEPHONE_NUMBER_A"
      Case PR_OTHER_TELEPHONE_NUMBER_W
         kWabPropTagName = "OTHER_TELEPHONE_NUMBER_W"
      Case PR_OTHER_TELEPHONE_NUMBER_A
         kWabPropTagName = "OTHER_TELEPHONE_NUMBER_A"
      Case PR_TRANSMITABLE_DISPLAY_NAME_W
         kWabPropTagName = "TRANSMITABLE_DISPLAY_NAME_W"
      Case PR_TRANSMITABLE_DISPLAY_NAME_A
         kWabPropTagName = "TRANSMITABLE_DISPLAY_NAME_A"
      Case PR_PAGER_TELEPHONE_NUMBER_W
         kWabPropTagName = "PAGER_TELEPHONE_NUMBER_W"
      Case PR_PAGER_TELEPHONE_NUMBER_A
         kWabPropTagName = "PAGER_TELEPHONE_NUMBER_A"
      Case PR_USER_CERTIFICATE
         kWabPropTagName = "USER_CERTIFICATE"
      Case PR_PRIMARY_FAX_NUMBER_W
         kWabPropTagName = "PRIMARY_FAX_NUMBER_W"
      Case PR_PRIMARY_FAX_NUMBER_A
         kWabPropTagName = "PRIMARY_FAX_NUMBER_A"
      Case PR_BUSINESS_FAX_NUMBER_W
         kWabPropTagName = "BUSINESS_FAX_NUMBER_W"
      Case PR_BUSINESS_FAX_NUMBER_A
         kWabPropTagName = "BUSINESS_FAX_NUMBER_A"
      Case PR_HOME_FAX_NUMBER_W
         kWabPropTagName = "HOME_FAX_NUMBER_W"
      Case PR_HOME_FAX_NUMBER_A
         kWabPropTagName = "HOME_FAX_NUMBER_A"
      Case PR_COUNTRY_W
         kWabPropTagName = "COUNTRY_W"
      Case PR_COUNTRY_A
         kWabPropTagName = "COUNTRY_A"
      Case PR_LOCALITY_W
         kWabPropTagName = "LOCALITY_W"
      Case PR_LOCALITY_A
         kWabPropTagName = "LOCALITY_A"
      Case PR_STATE_OR_PROVINCE_W
         kWabPropTagName = "STATE_OR_PROVINCE_W"
      Case PR_STATE_OR_PROVINCE_A
         kWabPropTagName = "STATE_OR_PROVINCE_A"
      Case PR_STREET_ADDRESS_W
         kWabPropTagName = "STREET_ADDRESS_W"
      Case PR_STREET_ADDRESS_A
         kWabPropTagName = "STREET_ADDRESS_A"
      Case PR_POSTAL_CODE_W
         kWabPropTagName = "POSTAL_CODE_W"
      Case PR_POSTAL_CODE_A
         kWabPropTagName = "POSTAL_CODE_A"
      Case PR_POST_OFFICE_BOX_W
         kWabPropTagName = "POST_OFFICE_BOX_W"
      Case PR_POST_OFFICE_BOX_A
         kWabPropTagName = "POST_OFFICE_BOX_A"
      Case PR_TELEX_NUMBER_W
         kWabPropTagName = "TELEX_NUMBER_W"
      Case PR_TELEX_NUMBER_A
         kWabPropTagName = "TELEX_NUMBER_A"
      Case PR_ISDN_NUMBER_W
         kWabPropTagName = "ISDN_NUMBER_W"
      Case PR_ISDN_NUMBER_A
         kWabPropTagName = "ISDN_NUMBER_A"
      Case PR_ASSISTANT_TELEPHONE_NUMBER_W
         kWabPropTagName = "ASSISTANT_TELEPHONE_NUMBER_W"
      Case PR_ASSISTANT_TELEPHONE_NUMBER_A
         kWabPropTagName = "ASSISTANT_TELEPHONE_NUMBER_A"
      Case PR_HOME2_TELEPHONE_NUMBER_W
         kWabPropTagName = "HOME2_TELEPHONE_NUMBER_W"
      Case PR_HOME2_TELEPHONE_NUMBER_A
         kWabPropTagName = "HOME2_TELEPHONE_NUMBER_A"
      Case PR_ASSISTANT_W
         kWabPropTagName = "ASSISTANT_W"
      Case PR_ASSISTANT_A
         kWabPropTagName = "ASSISTANT_A"
      Case PR_SEND_RICH_INFO
         kWabPropTagName = "SEND_RICH_INFO"
      Case PR_WEDDING_ANNIVERSARY
         kWabPropTagName = "WEDDING_ANNIVERSARY"
      Case PR_BIRTHDAY
         kWabPropTagName = "BIRTHDAY"
      Case PR_HOBBIES_W
         kWabPropTagName = "HOBBIES_W"
      Case PR_HOBBIES_A
         kWabPropTagName = "HOBBIES_A"
      Case PR_MIDDLE_NAME_W
         kWabPropTagName = "MIDDLE_NAME_W"
      Case PR_MIDDLE_NAME_A
         kWabPropTagName = "MIDDLE_NAME_A"
      Case PR_DISPLAY_NAME_PREFIX_W
         kWabPropTagName = "DISPLAY_NAME_PREFIX_W"
      Case PR_DISPLAY_NAME_PREFIX_A
         kWabPropTagName = "DISPLAY_NAME_PREFIX_A"
      Case PR_PROFESSION_W
         kWabPropTagName = "PROFESSION_W"
      Case PR_PROFESSION_A
         kWabPropTagName = "PROFESSION_A"
      Case PR_PREFERRED_BY_NAME_W
         kWabPropTagName = "PREFERRED_BY_NAME_W"
      Case PR_PREFERRED_BY_NAME_A
         kWabPropTagName = "PREFERRED_BY_NAME_A"
      Case PR_SPOUSE_NAME_W
         kWabPropTagName = "SPOUSE_NAME_W"
      Case PR_SPOUSE_NAME_A
         kWabPropTagName = "SPOUSE_NAME_A"
      Case PR_COMPUTER_NETWORK_NAME_W
         kWabPropTagName = "COMPUTER_NETWORK_NAME_W"
      Case PR_COMPUTER_NETWORK_NAME_A
         kWabPropTagName = "COMPUTER_NETWORK_NAME_A"
      Case PR_CUSTOMER_ID_W
         kWabPropTagName = "CUSTOMER_ID_W"
      Case PR_CUSTOMER_ID_A
         kWabPropTagName = "CUSTOMER_ID_A"
      Case PR_TTYTDD_PHONE_NUMBER_W
         kWabPropTagName = "TTYTDD_PHONE_NUMBER_W"
      Case PR_TTYTDD_PHONE_NUMBER_A
         kWabPropTagName = "TTYTDD_PHONE_NUMBER_A"
      Case PR_FTP_SITE_W
         kWabPropTagName = "FTP_SITE_W"
      Case PR_FTP_SITE_A
         kWabPropTagName = "FTP_SITE_A"
      Case PR_GENDER
         kWabPropTagName = "GENDER"
      Case PR_MANAGER_NAME_W
         kWabPropTagName = "MANAGER_NAME_W"
      Case PR_MANAGER_NAME_A
         kWabPropTagName = "MANAGER_NAME_A"
      Case PR_NICKNAME_W
         kWabPropTagName = "NICKNAME_W"
      Case PR_NICKNAME_A
         kWabPropTagName = "NICKNAME_A"
      Case PR_PERSONAL_HOME_PAGE_W
         kWabPropTagName = "PERSONAL_HOME_PAGE_W"
      Case PR_PERSONAL_HOME_PAGE_A
         kWabPropTagName = "PERSONAL_HOME_PAGE_A"
      Case PR_BUSINESS_HOME_PAGE_W
         kWabPropTagName = "BUSINESS_HOME_PAGE_W"
      Case PR_BUSINESS_HOME_PAGE_A
         kWabPropTagName = "BUSINESS_HOME_PAGE_A"
      Case PR_CONTACT_VERSION
         kWabPropTagName = "CONTACT_VERSION"
      Case PR_CONTACT_ENTRYIDS
         kWabPropTagName = "CONTACT_ENTRYIDS"
      Case PR_CONTACT_ADDRTYPES_W
         kWabPropTagName = "CONTACT_ADDRTYPES_W"
      Case PR_CONTACT_ADDRTYPES_A
         kWabPropTagName = "CONTACT_ADDRTYPES_A"
      Case PR_CONTACT_DEFAULT_ADDRESS_INDEX
         kWabPropTagName = "CONTACT_DEFAULT_ADDRESS_INDEX"
      Case PR_CONTACT_EMAIL_ADDRESSES_W
         kWabPropTagName = "CONTACT_EMAIL_ADDRESSES_W"
      Case PR_CONTACT_EMAIL_ADDRESSES_A
         kWabPropTagName = "CONTACT_EMAIL_ADDRESSES_A"
      Case PR_COMPANY_MAIN_PHONE_NUMBER_W
         kWabPropTagName = "COMPANY_MAIN_PHONE_NUMBER_W"
      Case PR_COMPANY_MAIN_PHONE_NUMBER_A
         kWabPropTagName = "COMPANY_MAIN_PHONE_NUMBER_A"
      Case PR_CHILDRENS_NAMES_W
         kWabPropTagName = "CHILDRENS_NAMES_W"
      Case PR_CHILDRENS_NAMES_A
         kWabPropTagName = "CHILDRENS_NAMES_A"
      Case PR_HOME_ADDRESS_CITY_W
         kWabPropTagName = "HOME_ADDRESS_CITY_W"
      Case PR_HOME_ADDRESS_CITY_A
         kWabPropTagName = "HOME_ADDRESS_CITY_A"
      Case PR_HOME_ADDRESS_COUNTRY_W
         kWabPropTagName = "HOME_ADDRESS_COUNTRY_W"
      Case PR_HOME_ADDRESS_COUNTRY_A
         kWabPropTagName = "HOME_ADDRESS_COUNTRY_A"
      Case PR_HOME_ADDRESS_POSTAL_CODE_W
         kWabPropTagName = "HOME_ADDRESS_POSTAL_CODE_W"
      Case PR_HOME_ADDRESS_POSTAL_CODE_A
         kWabPropTagName = "HOME_ADDRESS_POSTAL_CODE_A"
      Case PR_HOME_ADDRESS_STATE_OR_PROVINCE_W
         kWabPropTagName = "HOME_ADDRESS_STATE_OR_PROVINCE_W"
      Case PR_HOME_ADDRESS_STATE_OR_PROVINCE_A
         kWabPropTagName = "HOME_ADDRESS_STATE_OR_PROVINCE_A"
      Case PR_HOME_ADDRESS_STREET_W
         kWabPropTagName = "HOME_ADDRESS_STREET_W"
      Case PR_HOME_ADDRESS_STREET_A
         kWabPropTagName = "HOME_ADDRESS_STREET_A"
      Case PR_HOME_ADDRESS_POST_OFFICE_BOX_W
         kWabPropTagName = "HOME_ADDRESS_POST_OFFICE_BOX_W"
      Case PR_HOME_ADDRESS_POST_OFFICE_BOX_A
         kWabPropTagName = "HOME_ADDRESS_POST_OFFICE_BOX_A"
      Case PR_OTHER_ADDRESS_CITY_W
         kWabPropTagName = "OTHER_ADDRESS_CITY_W"
      Case PR_OTHER_ADDRESS_CITY_A
         kWabPropTagName = "OTHER_ADDRESS_CITY_A"
      Case PR_OTHER_ADDRESS_COUNTRY_W
         kWabPropTagName = "OTHER_ADDRESS_COUNTRY_W"
      Case PR_OTHER_ADDRESS_COUNTRY_A
         kWabPropTagName = "OTHER_ADDRESS_COUNTRY_A"
      Case PR_OTHER_ADDRESS_POSTAL_CODE_W
         kWabPropTagName = "OTHER_ADDRESS_POSTAL_CODE_W"
      Case PR_OTHER_ADDRESS_POSTAL_CODE_A
         kWabPropTagName = "OTHER_ADDRESS_POSTAL_CODE_A"
      Case PR_OTHER_ADDRESS_STATE_OR_PROVINCE_W
         kWabPropTagName = "OTHER_ADDRESS_STATE_OR_PROVINCE_W"
      Case PR_OTHER_ADDRESS_STATE_OR_PROVINCE_A
         kWabPropTagName = "OTHER_ADDRESS_STATE_OR_PROVINCE_A"
      Case PR_OTHER_ADDRESS_STREET_W
         kWabPropTagName = "OTHER_ADDRESS_STREET_W"
      Case PR_OTHER_ADDRESS_STREET_A
         kWabPropTagName = "OTHER_ADDRESS_STREET_A"
      Case PR_OTHER_ADDRESS_POST_OFFICE_BOX_W
         kWabPropTagName = "OTHER_ADDRESS_POST_OFFICE_BOX_W"
      Case PR_OTHER_ADDRESS_POST_OFFICE_BOX_A
         kWabPropTagName = "OTHER_ADDRESS_POST_OFFICE_BOX_A"
      Case PR_STORE_PROVIDERS
         kWabPropTagName = "STORE_PROVIDERS"
      Case PR_AB_PROVIDERS
         kWabPropTagName = "AB_PROVIDERS"
      Case PR_TRANSPORT_PROVIDERS
         kWabPropTagName = "TRANSPORT_PROVIDERS"
      Case PR_DEFAULT_PROFILE
         kWabPropTagName = "DEFAULT_PROFILE"
      Case PR_AB_SEARCH_PATH
         kWabPropTagName = "AB_SEARCH_PATH"
      Case PR_AB_DEFAULT_DIR
         kWabPropTagName = "AB_DEFAULT_DIR"
      Case PR_AB_DEFAULT_PAB
         kWabPropTagName = "AB_DEFAULT_PAB"
      Case PR_FILTERING_HOOKS
         kWabPropTagName = "FILTERING_HOOKS"
      Case PR_SERVICE_NAME_W
         kWabPropTagName = "SERVICE_NAME_W"
      Case PR_SERVICE_NAME_A
         kWabPropTagName = "SERVICE_NAME_A"
      Case PR_SERVICE_DLL_NAME_W
         kWabPropTagName = "SERVICE_DLL_NAME_W"
      Case PR_SERVICE_DLL_NAME_A
         kWabPropTagName = "SERVICE_DLL_NAME_A"
      Case PR_SERVICE_ENTRY_NAME
         kWabPropTagName = "SERVICE_ENTRY_NAME"
      Case PR_SERVICE_UID
         kWabPropTagName = "SERVICE_UID"
      Case PR_SERVICE_EXTRA_UIDS
         kWabPropTagName = "SERVICE_EXTRA_UIDS"
      Case PR_SERVICES
         kWabPropTagName = "SERVICES"
      Case PR_SERVICE_SUPPORT_FILES_W
         kWabPropTagName = "SERVICE_SUPPORT_FILES_W"
      Case PR_SERVICE_SUPPORT_FILES_A
         kWabPropTagName = "SERVICE_SUPPORT_FILES_A"
      Case PR_SERVICE_DELETE_FILES_W
         kWabPropTagName = "SERVICE_DELETE_FILES_W"
      Case PR_SERVICE_DELETE_FILES_A
         kWabPropTagName = "SERVICE_DELETE_FILES_A"
      Case PR_AB_SEARCH_PATH_UPDATE
         kWabPropTagName = "AB_SEARCH_PATH_UPDATE"
      Case PR_PROFILE_NAME_A
         kWabPropTagName = "PROFILE_NAME_A"
      Case PR_PROFILE_NAME_W
         kWabPropTagName = "PROFILE_NAME_W"
      Case PR_IDENTITY_DISPLAY_W
         kWabPropTagName = "IDENTITY_DISPLAY_W"
      Case PR_IDENTITY_DISPLAY_A
         kWabPropTagName = "IDENTITY_DISPLAY_A"
      Case PR_IDENTITY_ENTRYID
         kWabPropTagName = "IDENTITY_ENTRYID"
      Case PR_RESOURCE_METHODS
         kWabPropTagName = "RESOURCE_METHODS"
      Case PR_RESOURCE_TYPE
         kWabPropTagName = "RESOURCE_TYPE"
      Case PR_STATUS_CODE
         kWabPropTagName = "STATUS_CODE"
      Case PR_IDENTITY_SEARCH_KEY
         kWabPropTagName = "IDENTITY_SEARCH_KEY"
      Case PR_OWN_STORE_ENTRYID
         kWabPropTagName = "OWN_STORE_ENTRYID"
      Case PR_RESOURCE_PATH_W
         kWabPropTagName = "RESOURCE_PATH_W"
      Case PR_RESOURCE_PATH_A
         kWabPropTagName = "RESOURCE_PATH_A"
      Case PR_STATUS_STRING_W
         kWabPropTagName = "STATUS_STRING_W"
      Case PR_STATUS_STRING_A
         kWabPropTagName = "STATUS_STRING_A"
      Case PR_X400_DEFERRED_DELIVERY_CANCEL
         kWabPropTagName = "X400_DEFERRED_DELIVERY_CANCEL"
      Case PR_HEADER_FOLDER_ENTRYID
         kWabPropTagName = "HEADER_FOLDER_ENTRYID"
      Case PR_REMOTE_PROGRESS
         kWabPropTagName = "REMOTE_PROGRESS"
      Case PR_REMOTE_PROGRESS_TEXT_W
         kWabPropTagName = "REMOTE_PROGRESS_TEXT_W"
      Case PR_REMOTE_PROGRESS_TEXT_A
         kWabPropTagName = "REMOTE_PROGRESS_TEXT_A"
      Case PR_REMOTE_VALIDATE_OK
         kWabPropTagName = "REMOTE_VALIDATE_OK"
      Case PR_CONTROL_FLAGS
         kWabPropTagName = "CONTROL_FLAGS"
      Case PR_CONTROL_STRUCTURE
         kWabPropTagName = "CONTROL_STRUCTURE"
      Case PR_CONTROL_TYPE
         kWabPropTagName = "CONTROL_TYPE"
      Case PR_DELTAX
         kWabPropTagName = "DELTAX"
      Case PR_DELTAY
         kWabPropTagName = "DELTAY"
      Case PR_XPOS
         kWabPropTagName = "XPOS"
      Case PR_YPOS
         kWabPropTagName = "YPOS"
      Case PR_CONTROL_ID
         kWabPropTagName = "CONTROL_ID"
      Case PR_INITIAL_DETAILS_PANE
         kWabPropTagName = "INITIAL_DETAILS_PANE"
      Case PR_SEND_INTERNET_ENCODING
         kWabPropTagName = "SEND_INTERNET_ENCODING"
      Case Else
         Dim propID As Long
         propID = modkWab.kWabGetPropID(Tag)
         If (propID >= &H1100&) And (propID <= &H1200&) Then
            kWabPropTagName = "<reserved>"
         Else
            kWabPropTagName = "<unknown tag>"
         End If
   End Select
   If Right(kWabPropTagName, 2) = "_A" Then
      kWabPropTagName = Left(kWabPropTagName, Len(kWabPropTagName) - 2) & " (ANSI)"
   ElseIf Right(kWabPropTagName, 2) = "_W" Then
      kWabPropTagName = Left(kWabPropTagName, Len(kWabPropTagName) - 2) & " (Unicode)"
   End If
   kWabPropTagName = UCase(Left(kWabPropTagName, 1)) & LCase(Mid(Replace(kWabPropTagName, "_", " "), 2))
End Function
