@REM OPTIONAL PARAMETER ---- /autoclose 
@REM -------------------------------------------------
@REM ---- "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V -- VB-VB-NT--  EXE -- AT BOOT.fsf" /autoexec /autoclose 

GOTO ENDER_SUB

@REM -- ViceVersa Pro - [VICE V -- VB-VB-NT--  EXE -- AT BOOT.fsf] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V -- VB-VB-NT--  EXE -- AT BOOT.fsf" /autoexec /autoclose 

GOTO ENDER_SUB

@REM --- Q TO I:\Q -- DESTINATION D DRIVE DATA -- ADATA DRIVE
@REM -- ViceVersa Pro - [C:\SCRIPTER\...\VICE V --ADATA HDD.fsf] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V --ADATA HDD.fsf" /autoexec 

@REM -- SAMSUNG PEN DRIVE 32G 
@REM -- ViceVersa Pro - [VICE V --ADATA HDD -- USB_32_G_.fsf] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V --ADATA HDD -- USB_32_G_.fsf" /autocompare

@REM -- ViceVersa Pro - [VICE V -- HDD USB32 TO MC_GRUB4DOS_32G.fsf *] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V -- HDD USB32 TO MC_GRUB4DOS_32G.fsf" /autocompare

@REM -- ViceVersa Pro - [VICE V -- HDD USB32 TO MC_GRUB4DOS_32G.fsf] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V -- HDD USB32 TO MC_GRUB4DOS_32G.fsf" /autocompare

@REM -- ViceVersa Pro - [C:\SCRIPTER\...\VICE V --ADATA HDD -- FAT_32__.fsf] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V --ADATA HDD -- FAT_32__.fsf" /autocompare

@REM --ViceVersa Pro - [VICE V -- C DRIVE TO HARDCORE SOME SORT OF PEN DRIVE LOT OF FILTER.fsf] - (Registered)
START "" "C:\Program Files\ViceVersa Pro\ViceVersa.exe" "C:\SCRIPTER\SCRIPTER -- ViceVersa PRO\VICE V -- C DRIVE TO HARDCORE SOME SORT OF PEN DRIVE LOT OF FILTER.fsf" /autocompare

ENDER_SUB:
EXIT