verify on
xcopy g:\coolcid\*.* g:\coolcidx\*.* /d/s/f
xcopy g:\coolcid\*.* j:\coolcidx\*.* /d/s/f
xcopy c:\coolcid\*.* c:\coolcid2\*.* /d/s/f
xcopy c:\coolcid\*.* d:\coolcid2\*.* /d/s/f
xcopy c:\coolcid\*.* e:\coolcid\*.*  /d/s/f
xcopy c:\coolcid\*.* f:\coolcid\*.*  /d/s/f
xcopy c:\coolcid\*.* e:\coolcid2\*.* /d/s/f
xcopy c:\coolcid\*.* f:\coolcid2\*.* /d/s/f
xcopy c:\coolcid\*.* g:\coolcid\*.*  /d/s/f
xcopy c:\coolcid\*.* j:\coolcid\*.*  /d/s/f
