<?php

///////////////////// FYI /////////////////////
// Set 1 to enable and 0 to disable settings //
///////////////////////////////////////////////

$cfg['thumbs_per_row'] = 5;
/* thumbnails to show per row  on gallery pages */

$cfg['thumbs_per_page'] = 25;
/* total thumbnails to show per page on gallery pages
   should be a multiple of $cfg['thumbs_per_row'] */

$cfg['parse_captions'] = 0;
/* If enabled the text files used to display captions
   with the images will be parsed as php code. */

$cfg['addnocacheheaders'] = 1;
/* Adds HTTP headers which instruct visitors browsers
   not to cache the page. Disable if you dont plan to
   update much. */

$cfg['gzcompress'] = 1;
/* Activates gzip page compression for browsers which
   support it. Results in smaller pages being sent to
   clients. */

$cfg['open_photos_in_new_window'] = 0;
/* If enabled, clicking on thumbnails in the gallery
   will cause a new window to be opened. */

$cfg['use_thumbnails'] = 0;
/* If enabled, the thumbnail list will be generated by
   looking for files with the same name as those found
   in a gallery in the /thumbnails/ directory. If
   disabled, $cfg['override_thumb_size'] should be set
   to 1 and the large sized images will be used as
   thumbnails. */

$cfg['override_thumb_size'] = 1;
/* If enabled, thumbnail size will be defined to the
   values specified in $cfg['force_thumb_height'] and
   $cfg['force_thumb_width']. Otherwise, thumbnail
   size will be automatic */

$cfg['force_thumb_height'] = 80;
$cfg['force_thumb_width'] = 80;

$cfg['version'] = '1.0.5';
/* Not much point changing this unless you want to
   mess with people. Not that there's anything wrong
   with that. */

// layout variables
$cfg['largefont'] = '<font size="5" face="Tahoma">';
$cfg['cl'] = '</font>';

$cfg['normalfont'] = '<span style="font-size: 11px; font-family: tahoma;">';
$cfg['cn'] = '</span>';

$cfg['smallfont'] = '<font size="-2" face="Verdana">';
$cfg['cs'] = '</font>';

$cfg['tablebordercolor'] = '#ffffff';
$cfg['tableheadbgcolor'] = '#c0d0e0';
$cfg['tablecellbgcolor'] = '#dae3ef';

?>