@REM ----------------------------------------------------------------
@REM __ MATTHEW LANCASTER 
@REM __ MATT.LAN@BTINTERNET.COM
@REM ----------------------------------------------------------------
@REM __ FROM ---- --- 12-Jun-2018 11:29:00 Created Time
@REM __ TO   ---- Sun 07-Oct-2018 04:45:37 Last Editor _ Update Time+Header Info
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- RATHER USELESS CODE TO WANT TO HAVE REQUIRE AGAIN
@REM ----------------------------------------------------------------

MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\C DRIVE ROOT"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\C DRIVE ROOT NOT WANT"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\CAPTURE"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\DOWNLOAD ____ INFO"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\DOWNLOADS"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\drv"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\GoodSync"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\GOODSYNC CHIME"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\HBCD"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\IMAGES"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\ISO"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\JOYPAD"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\MAKE_PE3"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\MINIPE"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\MSDOS6.22"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\NST"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\PROGRAM FILES ROOT"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\PStart"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\RF"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\RoboForm"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\SCRIPTER"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\SxS_Fix_Win7PE"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\TEMP"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\TEMP ROOT"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\Users_BAK"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\UTILS"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\WIN_10_PRO_________£189.99_2016-11-13 -- GRUB_4_DOS"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\WIN_XP_PRO_SP2____£92.25__2006-10-30"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\WINDOW98"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\x86"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\0 00 LOGGERS TEXT"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\0 00 SETTING INI SYNC-ER"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\BAT"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\BOOT_EFI_BAK1"
MKDIR "\\8-msi-gp62m-7rd\8_msi_gp62m_7rd_04_2_samsung_4tb_c\BOOT_EFI_BAK2"