@ECHO OFF
REM ---- [ Wednesday 20:40:00 Pm_07 November 2018 ]
REM ---- MATTHEW LANCASTER PUT THIS IN HARDCORE
REM ---- MATT.LAN@BTINTERNET.COM
REM ---- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 58-GET SYSTEM UPTIME.BAT

CD \

TITLE C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 58-GET SYSTEM UPTIME.BAT

ECHO ----------------------------------------------------------------
ECHO GET SYSTEM BEGIN UPTIME TIME
ECHO ----------------------------------------------------------------
ECHO NET STATISTICS SERVER
ECHO ----------------------------------------------------------------
@ECHO ON
NET STATISTICS SERVER
@ECHO OFF
ECHO ----------------------------------------------------------------
ECHO.
PAUSE

REM ----
REM DOS COMMAND GET SYSTEM UPTIME - Google Search
REM https://www.google.co.uk/search?num=50&safe=active&ei=TEvjW5ToHurUgAb_hq-YDA&q=DOS+COMMAND+GET+SYSTEM+UPTIME&oq=DOS+COMMAND+GET+SYSTEM+UPTIME&gs_l=psy-ab.12..0i22i30k1l2.285342.285342.0.287354.1.1.0.0.0.0.101.101.0j1.1.0....0...1c.2.64.psy-ab..0.1.100....0.irqCYoxSwg0
REM --------
REM Checking windows server uptime - Public Cloud Forum - Solutions & Questions - The Rackspace Community
REM https://community.rackspace.com/products/f/public-cloud-forum/479/checking-windows-server-uptime
REM ----

