





CD /D F:\DSC--2018+CCSE_HIKVISION\2018+CCSE_HIKVISION_DS-7204H_____CH03_M\2020_CCSE_HIKVISION_DS-7204H\2020-02-22--ME GARDEN IVY OUT THE WAY\


FFMPEG : -i "file1" -strict experimental -y -ar 44100 -vcodec msmpeg4 "file2.mp4"
FFMPEG : -i "file1" -strict experimental -y -ar 44100 -vcodec mpeg4 -b 1280K "file2.mp4"
exit with code 1 good ar



the maxiunm bit rate is a bit low
1280K




"C:\PStart\# NOT INSTALL REQUIRED\FFMPEG\ffmpeg.exe"

for %%i in (*.mp4) do ECHO -err_detect ignore_err -i %%i -c copy %%~ni_fixed.mp4
pause





EXIT


for %%i in (*.mp4) do ffmpeg -err_detect ignore_err -i %%i -c copy %%~ni_fixed.mp4
pause




REM ----
REM Converting HikVision MP4 to standard MP4 or other format | IP Cam Talk 
REM https://ipcamtalk.com/threads/converting-hikvision-mp4-to-standard-mp4-or-other-format.30315/
REM ----
