@REM __ http://www.eassos.com/how-to/fix-error-code-0x80070005.php

@REM __ UNINSTALLED OFFICE 2007 

@REM __ BAT 35-0x80070005 WINDOWS UPDATE FIXER.BAT

@REM __ SET FOLDER ACCESS EVEYONE
@REM __ Step 1
@REM __ Launch Run box by pressing Windows key together with R key. 
@REM __ Type C:\Users\ \AppData\Local in the searching box. 
@REM __ Please replace with user account name and C with the drive that installs Windows.

@REM __ Step 2
@REM __ The Local folder will be opened and locate Packages folder by scrolling scrollbar with mouse. 
@REM __ When you find the folder, please right-click it and select Properties.

@REM __ Step 3
@REM __ Give permission to everyone in the usernames as full control and click "Advanced" button. 
@REM __ On the pop-up windows make sure that all users are given full control. If not, click Add.


@REM __ https://neosmart.net/wiki/0x80070005/

@REM __ FULL CONTROL EVERYONE

@REM __ C:\Users\MATT 01\AppData
@REM __ C:\Users\MATT 03\AppData


@REM __ Run
@REM __ C:\Windows10Upgrade\Windows10UpgraderApp.exe
@REM __ GET
@REM __ 0xc0000005