@REM ----------------------------------------------------------------
@REM __ C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-SCRIPT RUN GOOD OLE GOODSYNC SCRIPTOR FOLDER.BAT
@REM __
@REM __ BAT 59-SCRIPT RUN GOOD OLE GOODSYNC SCRIPTOR FOLDER.BAT
@REM __
@REM __ MATTHEW LANCASTER
@REM __ MATT.LAN@BTINTERNET.COM
@REM ----------------------------------------------------------------
@REM __ FROM ---- Fri 19-Oct-2018 15:05:42 Created Time _ Original Creation for GITHUB
@REM __ TO   ---- Fri 19-Oct-2018 17:30:00 Last Editor #1   1ST CREATE
@REM __
@REM __ FROM ---- Wed 07-Nov-2018 20:30:19 Last Editor #002 CHANGE USE HERE
@REM __ TO   ---- Wed 07-Nov-2018 23:34:00 Last Editor #002
@REM ----------------------------------------------------------------

@REM -- COPY FROM BROTHER BATCH FILE NOW A TWIN

@REM ----------------------------------------------------------------
@REM -- 001 SESSION
@REM -- CODER ADD -- MAKE GOODSYNC RUN THE JOB BY COMMAND-LINE
@REM -- MY FIRST COMMAND-LINE FOR GOODSYNC WORKING WELL
@REM -- GOODSYNC OUTPUT BY COMMANDLINE WAS IN A UNICODE CODEPAGE HAD
@REM -- TO BE DISCOVERED AND CONVERT FORM UNICODE INTO ASCII
@REM -- NOTEPAD++ HELP IN END WHAT TYPE CONVERSION DETECTED IN
@REM -- USUAL CODE THE RUN GOODSYNC AND THEN CHECK THE OUTPUT FOR
@REM -- THE PROCESS RAN
@REM ----------------------------------------------------------------
@REM __ FROM  Fri 19-Oct-2018 15:05:42
@REM __ TO    Fri 19-Oct-2018 17:30:00
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 002 SESSION
@REM -- LINK TO HERE _ MAKE CODE BECAUSE WAS GOING TO SHUTDOWN RESTART REBOOT ON ANOTHER COMPUTER
@REM -- AND WANTED A QUICKER SYNC-ER OF SCRIPT FOLDER BEFORE SHUT DOWN WITHOUT GOING TO GOODSYNC
@REM -- CODE ADDER
@REM -- LOT OF CHANGES AS USE __ SETLOCAL EnableDelayedExpansion
@REM -- MEAN A LOT OF VARIABLE FORMAT HAS TO CHANGE
@REM -- AND ALSO THE FIND OF STRING WASN'T WORKING TO LOOK UP IN UNICODE OUT
@REM -- THAT VERY EASY USE NEW COMMAND TO CHANGE TO ANSI FOR SEARCH HERE REQUIRE
@REM -- NOW MY OTHER CODE HAS TO BE UPDATED SAME AS HERE
@REM --
@REM -- THE BEGINNER OF VERY GOOD CODE
@REM -- ADD CODE _ EXTRA ARRAY PAIR WITH END OF OPERATION INFO STATUS
@REM -- NOT TAKE LONG WORKED FIRST TIME
@REM ----------------------------------------------------------------
@REM __ FROM  Wed 07-Nov-2018 20:30:19
@REM __ TO    Wed 07-Nov-2018 22:54:00
@REM __ TO    Wed 07-Nov-2018 23:34:00
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 003 SESSION
@REM -- ADD CAMERA BACKUP MODE
@REM -- OTHER DAY START AND THEN THIS PART TO DO
@REM ----------------------------------------------------------------
@REM __ FROM  Sun 21-Jul-2019 17:54:45
@REM __ TO    Sun 21-Jul-2019 18:10:00 -- 15 MINUTE
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 004 SESSION
@REM -- WORK TODAY
@REM ----------------------------------------------------------------
@REM AN END POINT AND MASSIVE CHANGE TO ENDER
@REM MUCH NEATER CODER AND LESS
@REM REMOVE END BLOCK TEXT WITH LOAD OF IF CONDITION AND MAKE IT SIMPLE
@REM WITH MAKE RESULT SHOW MORE EACH JOB
@REM AND EASIER UPDATE MORE ERROR RESULT FROM GOODSYNC
@REM Mon 03-Feb-2020 06:48:20
@REM Mon 03-Feb-2020 08:38:00 -- 1 HOUR 50 MINUTE
@REM -- BEEN SOME PREVIOUS WORK DAY BEFORE
@REM -- UPDATE END RESULT GOODSYNC
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 005 SESSION
@REM WORK TODAY
@REM ----------------------------------------------------------------
@REM MODIFY UP -- AND OTHER PROJECT
@REM -- 
@REM Tue 04-Feb-2020 10:12:00
@REM Tue 04-Feb-2020 23:56:00 -- 13 HOUR 44 MINUTE
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 00* SESSION SIXTH
@REM WORK TODAY
@REM ----------------------------------------------------------------
@REM ADD ROUTINE TO CHECK IF THIS PROJECT IS ALREADY RUN 
@REM BY ISSUE A AUTOHOTKEYS FIND WINDOW ROUTINE THAT PASS BY PARAMETER
@REM TAKE A SPECIAL TRICK PASS THE PARAMETER LINE WITH * FILL WHERE SPACE
@REM EXTRACT OTHER END -- LIKE CONCENTRATE ORANGE -- TETRA
@REM USELESS OTHERWISE
@REM ----------------------------------------------------------------
@REM A TON OF CODER AND LITTLE ROUTINE SIZE AFTER COMPACTOR 
@REM OF LEFT AFTER 
@REM NOT FIRST TIME DISCOVER THE OPERATION 
@REM FIRST TIME MAYBE FROM DOS TO AUTOHOTKEYS AND BACK AGAIN 
@REM EXIT CODE ERRORLEVEL AND PASS PARAMETER 
@REM ALWAYS PASS PARAMETER WITH * NOT ANY OTHER CHARACTER LIKE DASH -
@REM OR YOUR HEADACHE HURTING
@REM ----------------------------------------------------------------
@REM Sat 08-Feb-2020 12:00:22
@REM Sat 08-Feb-2020 14:25:00 -- 2 HOUR 25 MINUTE
@REM ----------------------------------------------------------------



@REM ----------------------------------------------------------------
@REM -- Located in Sync Location 1.. 2..
@REM ----------------------------------------------------------------
@REM -- 1..
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\
@REM ----------------------------------------------------------------
@REM -- 2..
@REM -- C:\SCRIPTER\SCRIPTER CODE -- GITHUB\
@REM ----------------------------------------------------------------
@REM -- 3.. AND HERE
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
@REM -- 4.. AND HERE PAIR SYNC-ER BOTH HAPPEN
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB - GOODSYNC.BAT
@REM -- C:\SCRIPTOR GITHUB\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB - GOODSYNC.BAT
@REM ----------------------------------------------------------------
@REM -- ALL SYNC-ER NOW ANY MINUTE _ NOW A UNIVERSAL CODE PROGRAM
@REM ----------------------------------------------------------------
@GOTO JUMP_REMMER
REM -----------------------------------------------------------------
REM THE CODE
REM ON THE HOUR
REM 1..
REM C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB.exe
REM THIS CODE WILL EITHER RUN --
REM 2..
REM GITHUB - ONLY
REM WHICH IS HERE RUN
REM BAT 45-SCRIPT RUN GITHUB.BAT
REM ..
REM OR WILL RUN
REM 3..
REM GOODSYNC SYNC SET AND THEN GITHUB
REM 4..
REM ON THE HOUR IT WILL BE BOTH
REM ..
REM IF IT RUN GOODSYNC SET JOB IT WILL RUN HERE ITSELF ME
REM BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM 5..
REM -----------------------------------------------------------------
REM ON THE HOUR
REM 1..
REM C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB.exe
REM IS RUN BY HERE
REM Autokey -- 19-SCRIPT_TIMER_UTIL_1.ahk
REM SUBROUTINE
REM GITHUB_MIDNIGHT_AND_MIDDAY_TIMER:
REM THIS WILL NOT ACTOR IF GOODSYNC2GO IS RUN BY THE D DRIVE PROCESS
REM -----------------------------------------------------------------
REM Mon 02-Sep-2019 11:45:40
REM -----------------------------------------------------------------
:JUMP_REMMER


@REM ----------------------------------------------------------------
@REM __ SET ADMIN A SAFE DOUBLE CHECKER WAY NOT A LOOPY ONE
@REM __ IF CAN'T GET IT TO GO ADMIN DOESN'T RSI INJURY ITSELF AND YOU
@REM ----------------------------------------------------------------

@ECHO OFF

ECHO THE ALL THE COMMAND LINE PARAMETER --  ENV VARS
IF NOT "%*"=="" ECHO %*
IF "%*"==""     ECHO -- NONE COMMANDLINE  PARAMETER --  ENV VARS WERE GIVE ----------
ECHO.

ECHO %* | FIND "/ADMIN" >NUL
IF %errorlevel% EQU 0 SET ADMIN_REQUEST=/ADMIN

IF '%ADMIN_REQUEST%'=='/ADMIN' (
	@REM :: Check for ADMIN Privileges Again
	>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
	@IF '%errorlevel%' GTR '2' SET NOT_GOT_ADMIN=TRUE
)

@IF "%NOT_GOT_ADMIN%"=="TRUE" (
	ECHO AN ATTEMPT WAS MADE TO SET ADMIN BUT NOT SUCCESSFUL
	ECHO YOUR USER MUST BE A STANDARD USER OR SOMETHING LIKE HER
	ECHO SAVES GET STUCK IN A LOOP ASKING OR ALSO DELAY REQUIRING
	ECHO END
	PAUSE
	GOTO ENDE
	EXIT /B 1
)

@REM :: Check for ADMIN Privileges
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
@IF '%errorlevel%' GTR '2' (
	@REM Get ADMIN Privileges
	@ECHO Set UAC = CreateObject^("Shell.Application"^) >> "%temp%\getadmin.vbs"
	@ECHO UAC.ShellExecute "%~s0", "/ADMIN %*", "", "runas", 1 >> "%temp%\getadmin.vbs"

	"%temp%\getadmin.vbs"
	@DEL "%temp%\getadmin.vbs"
	GOTO ENDE
	@EXIT /B
)

IF '%ADMIN_REQUEST%'=='/ADMIN'     @ECHO Got ADMIN Privileges -- By Push For Them
IF NOT '%ADMIN_REQUEST%'=='/ADMIN' @ECHO Got ADMIN Privileges -- By Natural


@ECHO OFF



ECHO ----------------------------------------------------------------

@REM SET AT TOP
@REM SETLOCAL EnableDelayedExpansion
@REM SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
SETLOCAL EnableDelayedExpansion

REM ---- FILENAME WITHOUT EXTENSION
@SET TITLE_VAR=%~n0
REM ---- FILENAME WITH   EXTENSION
@SET TITLE_VAR=%~n0%~x0
REM ---- FULL SCRIPT PATH
@SET TITLE_VAR=%~f0


REM ----
REM How can I echo a newline in a batch file? - Stack Overflow
REM https://stackoverflow.com/questions/132799/how-can-i-echo-a-newline-in-a-batch-file
REM ----
REM ---- EXAMPLE ---- ECHO READY!\n!STEADY!\n!GO
REM ----
(set \n=^
%=Do not remove this line=%
)

@TITLE !TITLE_VAR!

REM TITLE TO FINDER -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT 
SET MYSCRIPT_AHK=C:\SCRIPTER\SCRIPTER CODE -- AUTOHOTKEY\AUTOKEY -- 89-WIN EXIST RETURN EXIT CODE.AHK
set PARAM_PASS=%~N0
set PARAM_PASS=%PARAM_PASS: =*%
ECHO.
ECHO ----------------------------------------------------------------
ECHO COMMAND RUN ----------------------------------------------------
SET MYSCRIPT_AHK_STRIPPER=%MYSCRIPT_AHK%
SET MYSCRIPT_AHK_STRIPPER=%~NX1
ECHO @START /WAIT "" "%MYSCRIPT_AHK_STRIPPER%" %PARAM_PASS%
START /WAIT "" "%MYSCRIPT_AHK%" %PARAM_PASS%
ECHO.
IF NOT %ERRORLEVEL%==0 ECHO SCRIPT ALREADY RUN __ EXITCODE

IF %ERRORLEVEL%==0 GOTO OPERATION_AHEAD_GOOD
ECHO ----------------------------------------------------------------
ECHO -- SCRIPT HERE ALREADY RUN -------------------------------------
ECHO.
ECHO %~N0%~X0
ECHO.
ECHO %~F0
ECHO.
ECHO -- EXIT DECISION -----------------------------------------------
ECHO ----------------------------------------------------------------
TIMEOUT /T 40
GOTO ENDE 

:OPERATION_AHEAD_GOOD
 
ECHO READY STEADY GO
ECHO READY!\n!STEADY!\n!GO

ECHO %* | FIND "GOODSYNC_MODE" >NUL
IF %errorlevel% EQU 0 (
REM ECHO !TITLE_VAR! | FIND "BAT 59-RUN GOODSYNC SET SCRIPTOR" >NUL
REM @if !errorlevel!==0 (
	SET MODE_RUN=GOODSYNC
	REM @CD /D "C:\SCRIPTER"
	GOTO START
)

ECHO %* | FIND "CAMERA_BACKUP_MODE" >NUL
IF %errorlevel% EQU 0 (
	SET MODE_RUN=CAMERA_BACKUP
	GOTO START
)

ECHO %* | FIND "CAMERA_BACKUP_CLOUD" >NUL
IF %errorlevel% EQU 0 (
	SET MODE_RUN=CAMERA_BACKUP_CLOUD
	GOTO START
)

ECHO %* | FIND "D_DRIVE_GOODSYNC_JOB_SET" >NUL
IF %errorlevel% EQU 0 (
	SET MODE_RUN=D_DRIVE_GOODSYNC_JOB_SET
	GOTO START
)

ECHO %* | FIND "GITHUB_MODE" >NUL
IF %errorlevel% EQU 0 (
	SET MODE_RUN=GITHUB
	REM @CD /D "C:\SCRIPTOR GITHUB"
	GOTO START
)


@REM -- COMMAND LINE DEMO
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT CAMERA_BACKUP_MODE


REM SET MODE_RUN=CAMERA_BACKUP
REM GOTO START


IF "!MODE_RUN!"=="" (

	SET MODE_RUN=CAMERA_BACKUP
	SET MODE_RUN=GITHUB
	REM @CD /D "C:\SCRIPTER"
	GOTO START
)


:START




ECHO %* | FIND "WITH_GITHUB_MODE" >NUL
IF %errorlevel% EQU 0 SET MODE_RUN_WITH_GITHUB=TRUE

REM SET TITLE_RUN_MODE=BAT 45-SCRIPT RUN GITHUB - GOODSYNC
REM SET MODE_RUN=GITHUB

ECHO RUN MODE -- !MODE_RUN!
REM ECHO !TITLE_RUN_MODE!

@SET PATH_GIT="C:\Program Files\Git\bin"
@SET GoodSync_GSync="C:\Program Files\Siber Systems\GoodSync\gsync.exe"

@REM ----
@REM CONVERTCP download | SourceForge.net
@REM https://sourceforge.net/projects/convertcp/
@REM ----
@SET ConvertCP="C:\SCRIPTER\SCRIPTER -- APP TOOL SET\ConvertCP\convertcp.exe"

@REM WELL IT TOOK A WHILE TO FIND CODE PAGE OF TEXT DOCUMENT
@REM ANSWER CAME FROM A PAG THAT GIVE IT NOTEPAD++ IN BOTTOM RIGHT CORNER TELL THE ANSWER
@REM AND FOUND FROM THERE
@REM ----
@REM text files - Notepad++ can recognize encoding? - Stack Overflow
@REM https://stackoverflow.com/questions/14246956/notepad-can-recognize-encoding/14247070#14247070
@REM ----

@ECHO OFF


@IF NOT EXIST "%~dp0#NFS-%COMPUTERNAME%\" MKDIR "%~dp0#NFS-%COMPUTERNAME%\"

REM Write %~n0 to get the filename without the extension.
SET FILENAME_ER="%~dp0#NFS-%COMPUTERNAME%\%~n0_GOODSYNC_OUTPUT_#NFS_EX.TXT"
SET FILENAME_ER_2="%~dp0#NFS-%COMPUTERNAME%\%~n0_GOODSYNC_OUTPUT_#NFS_EX.TXT.TMP"
SET FILENAME_ER_4="%~n0_GOODSYNC_OUTPUT_#NFS_EX.TXT"
@REM ------------------------------------------------------------
@REM EXAMPLE WITHOUT VARIABLE
@REM ------------------------------------------------------------
@REM CMD /A /C "%GoodSync_GSync% sync "C SCRIPTOR __ y _ 7G __ GITHUB"      >! !"

SET LDA=0

IF !MODE_RUN!==GOODSYNC                  GOTO GOODSYNC________________SET_ARRRAY
IF !MODE_RUN!==GITHUB                    GOTO GITHUB__________________SET_ARRRAY
IF !MODE_RUN!==CAMERA_BACKUP             GOTO CAMERA__________________SET_ARRRAY
IF !MODE_RUN!==D_DRIVE_GOODSYNC_JOB_SET  GOTO D_DRIVE_GOODSYNC_JOB____SET_ARRRAY
IF !MODE_RUN!==CAMERA_BACKUP_CLOUD       GOTO CAMERA_TO_CLOUD_LONGER__SET_ARRRAY


ECHO INFO----RAR
ECHO MUST BE AN ERROR ESCAPE FROM RUN PRESS CLOSE WINDOW -- CONTROL C
PAUSE
GOTO ENDE

:GOODSYNC________________SET_ARRRAY
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 1X"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 2E"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 3L"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 4G_ GSD"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 5P"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 8M_ GSD"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 00 C SCRIPTER FOLDER"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 00 SCRIPT RUN"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 1X"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 2E"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 3L"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 4G"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 5P"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C C DRIVE ROOT CROSS 8M _ GSD"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C ISO __ 7G TO 1X"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C ISO __ 7G TO 2E"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C ISO __ 7G TO 3L"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C ISO __ 7G TO 4G"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C ISO __ 7G TO 5P"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C ISO __ 7G TO 8M"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C GOODSYNC __ 7G TO 1X"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C GOODSYNC __ 7G TO 2E"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C GOODSYNC __ 7G TO 3L"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C GOODSYNC __ 7G TO 4G"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C GOODSYNC __ 7G TO 5P"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C GOODSYNC __ 7G TO 8M"
SET /A LDA=LDA+1
SET Sources[!LDA!]="D # MY DOC __ 7G TO 4G_1"
SET /A LDA=LDA+1
SET Sources[!LDA!]="D BT Cloud Sync _ 00 _ Caller ID"
SET /A LDA=LDA+1
SET Sources[!LDA!]="D #0 1 INSTALL 7G 4G_1"
SET /A LDA=LDA+1
SET Sources[!LDA!]="D #0 1 INSTALL 7G 8M_1"
SET /A LDA=LDA+1
SET Sources[!LDA!]="VB G7 VB-NT 8M _3_ LONGER"
SET /A LDA=LDA+1
SET Sources[!LDA!]="VB G7 VB-NT 5P _3_ LONGER GSD"
SET /A LDA=LDA+1
SET Sources[!LDA!]="VB G7 VB-NT 4G _3_ LONGER"
SET /A LDA=LDA+1
SET Sources[!LDA!]=""

REM GOTO NEXT_CONTINUE

:GITHUB__________________SET_ARRRAY

GOTO JUMPER

SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 4G INCL"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 4G_"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00 VB6 VB-NT -- ROOT 0 COMP_NAMER"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_01 -- ROOT 1"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_01 02 SCRIPTER CODE -- GITHUB"
REM SET /A LDA=LDA+1
REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_01 ELITESPY"
REM SET /A LDA=LDA+1
REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_01 VB_KEEP_RUNNER"
REM SET /A LDA=LDA+1
REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_05_COMMON"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 02 BAT 59-RUN GOODSYNC SET SCRIPTOR -- VB WANT QUICK CHANGER"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 02 BAT 59-RUN GOODSYNC SET SCRIPTOR--VB -- 00_Best_VB_01"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ MY WEB 01 MAIN"
SET /A LDA=LDA+1
SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ MY WEB 02 WORD SET"

:JUMPER

REM -----------------------------------------------------------------
REM -- VAR LINE HERE GO AT END AS GOT SCRIPT WITHIN 
REM -- GOODSYNC TO RUN WHEN DONE

REM -----------------------------------------------------------------
REM -- ALSO HERE IS REM OUT -- ONLY TO SHOW
REM -- BUTTY GITHUB HAS ABILITY RUN ON OWN WITH ONE FOLDER NONE MULTIPLE
REM -- AND THAT WILL BE AT THE END -- SEARCH IF WANTED TO
REM -----------------------------------------------------------------
REM -- Sat 29-Feb-2020 11:58:00
REM -----------------------------------------------------------------
REM -- SET /A LDA=LDA+1
REM -- SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB"
REM -----------------------------------------------------------------


REM SET /A LDA=LDA+1
REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_#_1_2"
REM GOTO JUMP
	REM SET /A LDA=LDA+1
	REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_001_PAIR_01_BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT"
	REM SET /A LDA=LDA+1
	REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_001_PAIR_02_BAT 45-SCRIPT RUN GITHUB - GOODSYNC.BAT"
REM :JUMP
REM SET /A LDA=LDA+1
REM SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_Multiple_Thread Port Scanner 02 CON"
SET /A LDA=LDA+1
SET Sources[!LDA!]=""
SET /A LDA=LDA+1
SET Sources[!LDA!]=""
SET /A LDA=LDA+1
SET Sources[!LDA!]=""
SET /A LDA=LDA+1
SET Sources[!LDA!]=""

REM -----------------------------------------------------------------
REM -- LEAVE UNTIL END AND THEN THE GITHUB SCRIPT WILL RUN FROM GOODSYNC CALL SCRIPT THE
REM -- BAT 45-SCRIPT RUN GITHUB.BAT
REM -----------------------------------------------------------------
REM -- MAYBE WE DON'T WANT GITHUB UPDATE WHILE GOODSYNC MODE WORKER
REM -----------------------------------------------------------------

IF !MODE_RUN_WITH_GITHUB!==TRUE GOTO WANT_GITHUB
IF !MODE_RUN!==GITHUB           GOTO WANT_GITHUB
GOTO NEXT_CONTINUE

:WANT_GITHUB
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB"


:NEXT_CONTINUE
GOTO NEXT_CONTINUE
:D_DRIVE_GOODSYNC_JOB____SET_ARRRAY
	SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 4G _ JOB SET"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 8G _ JOB SET"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 4G GSD"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 8M GSD"
	
:NEXT_CONTINUE
GOTO NEXT_CONTINUE
:CAMERA__________________SET_ARRRAY

	REM  ALL JOB FROM ASUS-7 COMPUTER
	SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"

	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V1"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G SHARE"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G GSD"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC __ 7G 8M #GSD"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC __ 7G 4G #GSD"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 4G_SAMSUNG 1TB_2020 #GSD"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 7G 4G"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 400 DAY 7G 4G __ 2019 CyberShot HX60V"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 400 DAY 7G 4G __ 2020 CyberShot HX60V"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 01"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 02 4G"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 03 - VIDEO MINE 2020"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 04 - VIDEO MINE 02 4G 7G"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 05 - VIDEO MINE 01 _ SAM 1TB 2020"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 07 - VIDEO MINE 01"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G 5P"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G 8M"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 1 1 MM"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 1 1 MM 5P"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 1 1 MM 8G"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 1 HC"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 1 HC 2 BUNKER"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X2 2 HC ROOT"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 3 ROOT 1"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 3 ROOT 2"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 3 ROOT 3 DATE ALPHA"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 4 AUTO"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 4 VIRTUAL 1"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 4 VIRTUAL 2"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X1 5 LITT"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X2 2 HC ROOT"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X2 2 HC__FOR PHOTO GD 1 7G"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X2 2 HC__FOR PHOTO GD 2 7G"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X2 2 HC__FOR PHOTO GD 3 5P"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X2 2 HC__FOR PHOTO GD 3 8M"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X3 1 MM IM1 & VI1"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X3 2 HC"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X3 3 HC ROOT"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X3 4 AUTO"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MORPHEUS X3 5 LITT"
	
	@REM ---- PRE CLOUD
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE #8 4G-F-HDD TO 7G-SAMSUNG-3-HDD"
	@REM ---- ITEM COVER BY ON BEFORE
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE #8 D-HDD 4K ULTRA 4G 7G" 
	
	@REM ---- ALL CLOUD BEGIN
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER GOOGLE 2020+ #1 DSC CYBERSHOT 2020"
	
	REM BETTER FILTER REQUIRE NOT +2020 NIT MORE LIKE EXCLUDE 2019 2018 
	REM SET /A LDA=LDA+1
	REM SET Sources[!LDA!]="D DSC EVER ONE DRIVE #7 +2020 --"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #1 DSC CYBERSHOT 2019"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #2 DSC 2019+SCREENCASTIFY"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 DSC CYBERSHOT 2020 D-HDD -- IMAGE"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 DSC CYBERSHOT 2020 SAM-F-HDD 1_TB -- MP4"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 F-HDD DSC--2018+CCTV HIKVISION"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #4 D-HDD 2019+4K ULTRA"
	
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 03 OD MATT4"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 08 - VIDEO MINE 01 4G_F TO 7G_SUMSUNG_3"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 09 - VIDEO MINE 01 OD-MATT4"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 10 - VIDEO MINE 2020 OD-MATT4"
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""

	
	REM ---------------------
REM Count = 025 -- Thu 13-Feb-2020 14:42:20
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Waiting for 8(120) sec on verb GET: Server says: Forbidden (status code 403): Rate Limit Exceeded
REM ---------------------
REM ---------------------
REM Count = 026 -- Thu 13-Feb-2020 14:43:18
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Server Account not found
REM ---------------------
REM ---------------------
REM Count = 027 -- Thu 13-Feb-2020 14:45:19
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Error locking folder: downloading lock file: Skip Close on Disconnected/Stopped file system
REM ---------------------
REM ---------------------
REM Count = 028 -- Thu 13-Feb-2020 14:45:54
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Error locking folder: checking for lock file: no reply after 120(90)-sec timeout on verb GetInfo:9: Recv: Server says: ServerPipe Receiver is still computing response (status code 518)
REM ---------------------
REM ---------------------
REM Count = 029 -- Thu 13-Feb-2020 14:47:10
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM SSL: Cannot load trusted root certificates from system: error:0B084009:x509 certificate routines:X509_load_cert_crl_file:PEM lib[b084009]
REM ---------------------
REM ---------------------
REM Count = 030 -- Thu 13-Feb-2020 14:47:33
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Checking root folder: GetInfo: The device is not ready.  (error 21)


REM files have changed (excluding renames), more than a threshold of 20%. So the job will not synchronize automatically.	
	
REM Error analyzing C:\SCRIPTOR GITHUB: Cannot parse state file, delete it if it became corrupted: C:/SCRIPTOR GITHUB: End of file at pos 491520

	
	
	
	
:NEXT_CONTINUE
GOTO NEXT_CONTINUE
:CAMERA_TO_CLOUD_LONGER__SET_ARRRAY

	REM ALL JOB FROM ASUS-7 COMPUTER
	SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"

	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	SET /A LDA=LDA+1
	SET Sources[!LDA!]=""
	
:NEXT_CONTINUE



REM -----------------------------------------------------------------
REM -- SORT THE EMPTY ARRAY FOR VOID VALUE
REM -----------------------------------------------------------------
SET LDB=0
for /L %%a in (1,1,!LDA!) do (
	IF NOT !sources[%%a]!=="" (
		SET /A LDB=LDB+1
		SET Sources_02[!LDB!]=!sources[%%a]!
	)
)

SET LDA=%LDB%

REM -- TEST DEBUG
REM SET LDA=1

REM -----------------------------------------------------------------
REM TEST ONLY RUN 1 JOB QUICKER DEBUGGING
REM SET LDA=1
REM -----------------------------------------------------------------

for /L %%a in (1,1,!LDA!) do (
	ECHO %%a -- !sources_02[%%a]!
)


SET "ANOTHER_JOB_COUNTER=0"
SET "ERROR_COUNT=0"
SET "X=0"
SET "FAULT_COUNTER=0"
SET "Sync_Runner_FAULT_TOTAL=TRUE"

REM -----------------------------------------------------------------
REM -- DON'T REQUIRE HERE AS LONG AS RUN GITHUB SYNC JOB
REM -- IT HAS SCRIPT THAT DOES IT ALSO
REM -----------------------------------------------------------------
REM "%~dp0\BAT 59-RUN GOODSYNC SET SCRIPTOR-AHK_MINIMIZE.ahk" !TITLE_VAR!  /QUICK_INTRO_DUMMY_RUN
REM -----------------------------------------------------------------
ECHO ----------------------------------------------------------------

@ECHO OFF
@ECHO ON
@ECHO OFF
SET LDG=0
SET LDM=
SET LDR=0

FOR /L %%a in (1,1,!LDA!) DO (

	ECHO.
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO %%a of !LDA! -- START
	ECHO ----------------------------------------------------------------

	REM STRIP QUOTES THIS BIT BEFORE END :"=
	REM NORMAL VAR BE LIKE !Sources_02[%%a]!
	REM CREDIT FINDER AT END OF CODE

	ECHO !Sources_02[%%a]:"=!

	ECHO ----------------------------------------------------------------
	ECHO RUN COMMAND
	ECHO ----------------------------------------------------------------

	ECHO.
	ECHO %GoodSync_GSync% sync !Sources_02[%%a]!^>!FILENAME_ER!
	ECHO.
	%GoodSync_GSync% sync !Sources_02[%%a]!>!FILENAME_ER!
	ECHO ----------------------------------------------------------------

	REM ----------------------------------------------------------------
	REM ------ 1200 UCS-2 (UTF-16 Little Endian Byte Order)
	REM ----------------------------------------------------------------
	REM SEND OUTPUT FILE FROM GOODSYNC RUN TO COMMAND CONSOLE WINDOW
	REM ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	%ConvertCP% 1200 0 /i !FILENAME_ER! /o !FILENAME_ER_2!
	DEL !FILENAME_ER! >NUL 2>NUL
	RENAME !FILENAME_ER_2! !FILENAME_ER_4!
	TYPE !FILENAME_ER!

	SET Analysis_Complete=FALSE
	SET Sync_Runner=FALSE
	SET Sync_Runner_ONE=FALSE
	
	SET Another_Job=FALSE
	SET Unresolved_Conflicts=FALSE
	SET Computer_Is_Offline=FALSE
	SET Change_Happen=TRUE
	SET JOB_NOT_FOUND=FALSE
	SET NONE_TO_DO_______=FALSE
	SET JOB_IS_USE_BY_ANOTHER_PROCESS=FALSE
	SET NONE_TO_DO_______=FALSE
	SET NET_PATH_NOT_FIND=FALSE
	SET VOLUME_NOT_FOUND=FALSE
	SET SYNC_FOLDER_NOT_EXIST=FALSE
	SET DELETE_IT_IF_IT_BECAME_CORRUPTED=FALSE
	SET SPECIFIED_NETWORK_NAME_IS_NOT_FINDAR=FALSE
	SET OPERATION_HIDE_ERROR=FALSE
	SET FILE_HAVE_CHANGE_MORE_THAN_THRESHOLD=FALSE
	
	REM Cannot parse state file, delete it if it became corrupted
	
	REM ------------------------------------------------------------
	REM ------------------------------------------------------------
	REM ------------------------------------------------------------
	REM ------------------------------------------------------------

	REM -- ALBION VS WATFORD
	REM -- Sat 08-Feb-2020 17:30:00
	REM -- Sat 08-Feb-2020 20:00:00 -- 2 HOUR 30 MINUTE
	
	find "-- Analysis Complete" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Analysis_Complete=TRUE
	find "Sync: Running:" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Analysis_Complete=TRUE
	find "== Sync Complete." !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Analysis_Complete=TRUE
	if !errorlevel!==0 SET Sync_Runner_ONE=TRUE

	REM NOT USER UET
	REM find "Changes: 0," !FILENAME_ER!>NUL
	REM if !errorlevel!==0 SET Change_Happen=FALSE
	find "Changes: 0, Conflicts: 0, CopyTime: 0, FixState: 0, Errors: 0" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Analysis_Complete=TRUE
	if !errorlevel!==0 SET NONE_TO_DO_______=TRUE
	
	find "Another job is Syncing in folder" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET /A ANOTHER_JOB_COUNTER=!ANOTHER_JOB_COUNTER!+1
	if !errorlevel!==0 SET Another_Job=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "unresolved conflits" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Unresolved_Conflicts=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "Analyze has finished with Conflicts" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Unresolved_Conflicts=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "Computer is offline or turned off" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET Computer_Is_Offline=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "Error parsing command line: Job" !FILENAME_ER!>NUL     & REM -- JOB_NOT_FOUND
	if !errorlevel!==0 SET JOB_NOT_FOUND=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "The process cannot access the file because it is being used by another process" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET JOB_IS_USE_BY_ANOTHER_PROCESS=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "The network name cannot be found" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET NET_PATH_NOT_FIND=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "Sync folder does not exist" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET SYNC_FOLDER_NOT_EXIST=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "delete it if it became corrupted" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET DELETE_IT_IF_IT_BECAME_CORRUPTED=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "The specified network name is no longer available" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET SPECIFIED_NETWORK_NAME_IS_NOT_FINDAR=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	find "files have changed (excluding renames), more than a threshold of" !FILENAME_ER!>NUL
	if !errorlevel!==0 SET FILE_HAVE_CHANGE_MORE_THAN_THRESHOLD=TRUE
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	
	
	FIND "volume not found" !FILENAME_ER!>NUL
	IF !errorlevel!==0 SET VOLUME_NOT_FOUND=TRUE
	REM -- THE MEDIA CARD FOR CAMERA SOMETIME NOT PLUG IN AND THEN 
	REM -- NOT WANT ERROR ABOUT IT ON THERE
	ECHO !Sources_02[%%a]! | FIND "D DSC __ MC CARD V0 _____" >NUL
	if NOT !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if NOT !errorlevel!==0 SET Sync_Runner_ONE=FALSE

	
	REM -------------------------------------------------------------
	if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	REM -------------------------------------------------------------
	REM -- NOT JOB WORK NUMBER [ #1 ] AS THAT THE CAMERA MEDIA CARD QUITE OFTEN NOT PLUG IN 
	REM -- NOT COUNT AS ERROR THEN HIDE RESULT
	REM -- OPERATION ARCHIVE WHEN = VOLUME_NOT_FOUND=TRUE
	REM -------------------------------------------------------------
	IF "%%a"=="1" SET OPERATION_HIDE_ERROR=TRUE
	
	REM ----------------------------------------------------------------
	REM ----------------------------------------------------------------
	SET ANALYSIS_AND_SYNC_NOT_RUN=FALSE
	SET ANALYSIS_AND_SYNC_NOT_RUN_1=01
	SET ANALYSIS_AND_SYNC_NOT_RUN_2=02
	IF NOT !OPERATION_HIDE_ERROR!==TRUE (
		IF !Analysis_Complete!==FALSE     SET ANALYSIS_AND_SYNC_NOT_RUN_1=FALSE
		IF !Sync_Runner_ONE!==FALSE       SET ANALYSIS_AND_SYNC_NOT_RUN_2=FALSE
	)
	
	IF !ANALYSIS_AND_SYNC_NOT_RUN_1!==!ANALYSIS_AND_SYNC_NOT_RUN_2! SET ANALYSIS_AND_SYNC_NOT_RUN=TRUE
	
	IF !ANALYSIS_AND_SYNC_NOT_RUN!==TRUE                            SET STATUS_84[%%a]=ERROR
	
	SET STATUS_TT[%%a]=AT OPERATION %%a _of_ !LDA!
	
	IF NOT !ANALYSIS_AND_SYNC_NOT_RUN!==TRUE                        SET STATUS_84[%%a]=GOOD-SYNC

	IF !Sync_Runner_ONE!==FALSE                                     SET /A FAULT_COUNTER=!FAULT_COUNTER!+1
	IF !ANALYSIS_AND_SYNC_NOT_RUN!==TRUE                            SET /A ERROR_COUNT=!ERROR_COUNT!+1
	SET STATUS_88[%%a]=!ERROR_COUNT!

	REM ----------------------------------------------------------------
	REM PROBLEM OF CONFLICT OF THIS FILE
	REM ONLY WAY NOW IS TO EXCLUDE IN GOODSYNC
	REM ----------------------------------------------------------------
	DEL !FILENAME_ER! >NUL 2>NUL
	REM ----------------------------------------------------------------

	REM ACCUMULATOR
	SET L=
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=%%a of !LDA! -- COMPLETE
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=!Sources_02[%%a]:"=!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=Analysis_Complete             !Analysis_Complete!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=Sync_Runner                   !Sync_Runner_ONE!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=NONE_TO_DO                    !NONE_TO_DO_______!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=Conflicts                     !Unresolved_Conflicts!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=Another_Running               !Another_Job!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=Computer_Is_Offline           !Computer_Is_Offline!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=Job Not Found                 !JOB_NOT_FOUND!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=JOB_IS_USE_BY_ANOTHER_PROCESS !JOB_IS_USE_BY_ANOTHER_PROCESS!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=NET_PATH_NOT_FIND             !NET_PATH_NOT_FIND!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=SYNC_FOLDER_NOT_EXIST         !SYNC_FOLDER_NOT_EXIST!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=SPECIFIED_NETWORK_NOT_FINDAR  !SPECIFIED_NETWORK_NAME_IS_NOT_FINDAR!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=STATE_FILE_CORRUPTED_DELETE   !DELETE_IT_IF_IT_BECAME_CORRUPTED!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=VOLUME_NOT_FOUND              !VOLUME_NOT_FOUND!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=FILE_HAVE_CHANGE_THRESHOLD    !FILE_HAVE_CHANGE_MORE_THAN_THRESHOLD!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=RESULT FIND                   !STATUS_84[%%a]!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=RESULT OVERALL ERROR COUNT    !STATUS_88[%%a]! OF %%a -- !STATUS_TT[%%a]!
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=ANOTHER_JOB_COUNTER           !ANOTHER_JOB_COUNTER!
	IF !OPERATION_HIDE_ERROR!==TRUE (
		SET /A L=L+1 & SET MSGBOX[!L!,%%a]=OPERATION_HIDE_ERROR          !OPERATION_HIDE_ERROR!
	)
	SET /A L=L+1 & SET MSGBOX[!L!,%%a]=----------------------------------------------------------------

	SET LDM=%%a
	
	REM FOR /L %%parameter IN (start,step,end) DO command  -- REM ---- SHOW JOB ARRAY -- MSGBOX

	ECHO. 
	FOR /L %%F IN (1,1,!L!) DO (
		ECHO !MSGBOX[%%F,%%a]!
	)

	IF !L! GTR !LDL! SET LDL=!L!

	REM ---- PUT IN THE ERROR ARRAY -- MSGBOXER
	IF !Sync_Runner_FAULT_TOTAL!==FALSE (
		FOR /L %%F IN (1,1,!LDL!) DO (
			SET MSGBOXER[%%F,%%a]=!MSGBOX[%%F,%%a]!
			REM ECHO XXAAA  %%a FFF  %%F LDL  !LDL!   "MSGBOXER"  !MSGBOXER[%%F,%%a]!
		)
	)
	
	
	REM ECHO ERROR__WORKER --------------------------------------------------
	REM -- AFTER HERE NOT WORK GOOD
	
	REM ---- PUT MINIMAL ERROR ARRAY -- MSGBOXER
	IF !Sync_Runner_FAULT_TOTAL!==FALSE (
		FOR /L %%v IN (1,1,%%a) DO (
			REM ECHO "RRRR " !MSGBOXER[%%v,%%a]!
			SET VAR=!MSGBOXER[%%v,%%a]!
			REM ECHO "AAA "  %%a   "VVV " %%v " 444 VAR " !VAR!    
			IF %%V==2                 SET MSGBOXERB[%%v,%%a]=!VAR!
			IF %%V==4                 SET MSGBOXERB[%%V,%%a]=!VAR!
			ECHO !VAR! | FINDSTR /I /C:"Analysis_Complete">NUL
			If !errorlevel!==0        SET MSGBOXERB[%%V,%%a]=!VAR!
			ECHO !VAR! | FINDSTR /I /C:"Sync_Runner">NUL
			If !errorlevel!==0        SET MSGBOXERB[%%V,%%a]=!VAR!
			ECHO !VAR! | FINDSTR /I /C:"Another_Running">NUL
			If !errorlevel!==0        SET START_LINE=TRUE
			IF !START_LINE!==TRUE (
				ECHO !VAR! | FINDSTR /I /C:"TRUE">NUL
				If !errorlevel!==0    SET MSGBOXERB[%%V,%%a]=!VAR!
				ECHO !VAR! | FINDSTR /I /C:"RESULT OVERALL ERROR COUNT">NUL
				If !errorlevel!==0    SET MSGBOXERB[%%V,%%a]=!VAR!
			)
			REM SET VAR_2=!MSGBOXERB[%%V,%%a]!
			REM ECHO "LDM "  %%a   "VVV " %%V "11111 VAR_2 " !VAR!    
			REM ---------------------------------------------------------
			REM -- FIND THE START LINE WHERE ALL TRUE FLAG FOR ERROR BEGINNER
			REM -- AFTER COMPOSE EDITOR HAPPEN
			REM -- FINDSTR /I /C:"TRUE" -- WITHOUT QUOTE OR NOT 
			REM -- POSSIBLE SPACE IN LINE MAKE CHANGE
			REM ---------------------------------------------------------
			REM OPERATION FIND HAPPEN -- DISPLAY RESULT SAME AS /X MUST BE DEFAULT
			REM ---------------------------------------------------------
		)
		)

		REM ECHO SHOW MINIMAL ERROR ARRAY ---------------------------------------------
		REM REM ---- SHOW BRIEF ERROR ARRAY -- MSGBOXER
		REM FOR /L %%F IN (1,1,%%a) DO (
		REM FOR /L %%V IN (1,1,!LDL!) DO (
			REM REM ECHO VVV  %%V   FFF  %%F
			REM REM SET VAR=!MSGBOXERB[%%V,%%F]! 
			REM REM ECHO !VAR!
			REM REM IF NOT "!VAR!"=="" ECHO !VAR!
		REM )
		REM )


		REM TIMEOUT /T 4
	)

	REM -------------------------------------------------------------
	REM FOR /L %%parameter IN (start,step,end) DO command 
	REM tokens=2,4,6 will cause the second, fourth and sixth items on each line to be processed
	REM tokens=2-6 will cause the second, third, fourth, fifth and sixth items on each line to be processed
	REM tokens=* will cause all items on each line to be processed
	REM tokens=3* will process the third token and the 4th + all subsequent items, this can also be written as tokens=3,*
	REM -------------------------------------------------------------
	
	REM IF !Sync_Runner_FAULT_TOTAL!==FALSE (
		REM ECHO ERROR__WORKER --------------------------------------------------
		REM REM -- LOOP ALL ERROR JOB SO FAR AND DISPLAY THEM -----------
		REM REM ---------------------------------------------------------
		REM FOR /L %%V IN (1,1,!LDR!) DO (
			REM SET START_LINE=FALSE
			REM FOR /L %%F IN (1,1,!LDD!) DO (
				REM SET VAR=!MSGBOXER[%%F,%%V]!
			REM FOR /L %%F IN (1,1,!LDL!) DO (
				REM SET /A LDG=LDG+1 & SET MSGBOXER[%%F,!LDR!]=!MSGBOX[%%F,%%a]!
			REM )
				REM REM ---------------------------------------------------------
				REM REM -- FIND THE START LINE WHERE ALL TRUE FLAG FOR ERROR BEGINNER
				REM REM -- AFTER COMPOSE EDITOR HAPPEN
				REM REM -- FINDSTR /I /C:"TRUE" -- WITHOUT QUOTE OR NOT 
				REM REM -- POSSIBLE SPACE IN LINE MAKE CHANGE
				REM REM ---------------------------------------------------------
				REM REM OPERATION FIND HAPPEN -- DISPLAY RESULT SAME AS /X MUST BE DEFAULT
				REM REM ---------------------------------------------------------
			REM )
		REM )
	REM )
)

	REM ECHO JOB__SET -------------------------------------------------------------

	REM FOR /L %%F IN (1,1,!LDL!) DO (
		REM ECHO !MSGBOXER[%%F,%%a]:"=!
	REM )



@REM ----------------------------------------------------------------
@REM FALSE FALL FOOLE - STUNT MAN - FALL GUY - SCRIPTING GUY - HEY GUYS
@REM WEEK-DAY - WEAK-DAY
@REM MONTH-DAY
@REM ----------------------------------------------------------------

REM ECHO.
REM ECHO ----------------------------------------------------------------
REM for /L %%a in (1,1,!LDA!) do (
	REM ECHO %%a of !LDA!
	REM ECHO !Sources_02[%%a]:"=!
	REM ECHO !STATUS_4[%%a]:"=!
	REM ECHO !STATUS_5[%%a]:"=!
	REM ECHO !STATUS_6[%%a]:"=!
	REM ECHO !STATUS_7[%%a]:"=!
	REM ECHO !STATUS_8[%%a]:"=!
	REM ECHO !STATUS_9[%%a]:"=!
	REM ECHO !STATUS_10[%%a]:"=!
	REM ECHO !STATUS_11[%%a]:"=!
	REM ECHO !STATUS_12[%%a]:"=!
	REM ECHO !STATUS_13[%%a]:"=!
	REM ECHO ----------------------------------------------------------------
REM )

REM IF NOT "!COMP_1!"=="!COMP_2!" (
	REM IF "!Sync_Runner_FAULT_TOTAL!"=="FALSE" (
		REM ECHO CONFLICT ERROR FOUND OVERALL _ COUNT = !FAULT_COUNTER!  ---- X-X-X-X-X-X-X-X-X
		REM ECHO ----------------------------------------------------------------
		REM REM for /L %%a in (1,1,!X!) do (
			REM REM IF 	!STATUS_84![%%a]=="ERROR" (
				REM REM ECHO !STATUS_1[%%a]:"=!
				REM REM ECHO !STATUS_3[%%a]:"=!
				REM REM ECHO !STATUS_2[%%a]:"=!
				REM REM ECHO !STATUS_84[%%a]:"=!
				REM REM ECHO ----------------------------------------------------------------
			REM REM )
		REM REM )
		REM REM TIMEOUT /T 4
	REM )


	
IF NOT !ERROR_COUNT!==0 (
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO NOT SUCCESSFUL ATTENTION                  ---- X-X-X-X-X-X-X-X-X
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
)

IF !ERROR_COUNT!==0 (
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO END RUNNER                                ---- *****************
	ECHO SYNC COMPLETE SUCCESSFUL                  ---- *****************
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
)

IF !MODE_RUN!==GITHUB  GOTO GITHUB_SUB
GOTO NEXT_PART

:GITHUB_SUB
	REM -----------------------------------------------------------------
	REM -- NOT REQUIRE
	REM -- THE LAST JOB OF GITHUB SCRIPT HERE WOULD DO THEM
	REM -----------------------------------------------------------------
	REM -- BUT USEFUL BUT NOT RUN TWO SAME TIME
	REM -- SOMETIME THERE CHANGE BUT NOT GET UPDATE IF CHANGE BEFORE
	REM -----------------------------------------------------------------
	REM -- NOW HAS ABLE TO CHECK IF ALREADY RUNNER
	REM -----------------------------------------------------------------
	REM -----------------------------------------------------------------
	ECHO 

	IF NOT !MODE_RUN!==GITHUB GOTO JUMP_OVER_GITHUB
	START "" "C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB.BAT"
	
	:JUMP_OVER_GITHUB
	REM ECHO.
	REM ECHO ------------------------------------------------------------
	REM ECHO RUN COMMAND 
	REM REM ECHO %~dp0
	REM ECHO ----------------------------------------------------------------
	REM TIMEOUT /T 8
TIMEOUT /T 30
GOTO ENDE

:NEXT_PART

ECHO.
TIMEOUT /T 300
REM ------------- 300 = 5 MINUTE

IF NOT !ERROR_COUNT!==0   PAUSE
:ENDER


@REM ----------------------------------------------------------------
@REM --- ECHO DE-STUPID-POO
@REM --- ECHO 
@REM --- ECHO DE-STUPID-POO
@REM --- DE-STUPID-POO
@REM --- DE-STUPID-POO OR POO
@REM ----------------------------------------------------------------
@REM FALSE FALL FOOLE - STUNT MAN - FALL GUY - SCRIPTING GUY - HEY GUYS
@REM WEEK-DAY - WEAK-DAY
@REM MONTH-DAY
@REM ----------------------------------------------------------------

ECHO.
ECHO ----------------------------------------------------------------

:ENDE
EXIT

@REM ----------------------------------------------------------------
@REM -- NOT WORKING ODD SOD'S -- UNABLE TO CONVERT THE CODEPAGE 
@REM -- USING DOS COMMANDING
@REM ----------------------------------------------------------------
@REM chcp 1200 >nul & cmd /a /c type "%~dp0GOODSYNC_ER_OUTPUT.TXT" >"%~dp0GOODSYNC_ER_OUTPUT_2.TXT"
@REM cmd /a /c type "%~dp0GOODSYNC_ER_OUTPUT.TXT" >"%~dp0GOODSYNC_ER_OUTPUT_2.TXT"
@REM cmd /a /c TYPE "%~dp0GOODSYNC_ER_OUTPUT_2.TXT"

@REM @echo off
@REM >%~dp0GOODSYNC_ER_OUTPUT.TXT (for /F "tokens=1* delims=:" %%G in ('findstr "^" "Sync: Running:"') do echo %%G = "%%H")

REM -----------------------------------------------------------------
REM CREDIT FIND BUT ONLY HELP TO LOCATE IN OWN CODE
REM ----
REM BATCH STRIP %~0 - Google Search
REM https://www.google.com/search?safe=active&ei=YZt7XJTWAdme1fAPo52CmA0&q=BATCH+STRIP+%25%7E0&oq=BATCH+STRIP+%25%7E0&gs_l=psy-ab.3...7068.8831..9110...0.0..0.65.340.6......0....1..gws-wiz.......0i71j0i8i7i30.X6lNLPYEc7I
REM ----
REM ----
REM How do you strip quotes out of an ECHO'ed string in a Windows batch file? - Stack Overflow
REM https://stackoverflow.com/questions/804646/how-do-you-strip-quotes-out-of-an-echoed-string-in-a-windows-batch-file
REM ----
REM -----------------------------------------------------------------

REM USING ARRAYS IN BATCH DOS COMMAND PROMPT LEVEL
REM ----
REM How to loop through array in batch? - Stack Overflow
REM https://stackoverflow.com/questions/18462169/how-to-loop-through-array-in-batch
REM ----

REM ----
REM Batch Script Variables
REM https://www.tutorialspoint.com/batch_script/batch_script_variables.htm
REM ----
REM Example
REM @echo off 
REM set globalvar = 5
REM SETLOCAL
REM set var = 13145
REM set /A var = %var% + 5
REM echo %var%
REM echo %globalvar%
REM ENDLOCAL
REM Few key things to note about the above program.

REM The ‘globalvar’ is defined with a global scope and is available throughout the entire script.

REM The ‘var‘ variable is defined in a local scope because it is enclosed between a ‘SETLOCAL’ and ‘ENDLOCAL’ block. Hence, this variable will be destroyed as soon the ‘ENDLOCAL’ statement is executed.

