@ECHO OFF
REM ---- [ Wednesday 20:40:00 Pm_07 November 2018 ]
REM ---- MATTHEW LANCASTER PUT THIS IN HARDCORE
REM ---- MATT.LAN@BTINTERNET.COM
REM ---- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 62-CHANGE IP ADDRESS.BAT

REM CD \

REM C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 62-CHANGE IP ADDRESS.BAT

ECHO ----------------------------------------------------------------
@ECHO ON
ipconfig /release
@ECHO.
@ECHO ----------------------------------------------------------------
@ECHO.
ipconfig /renew 
@ECHO.
@ECHO OFF
ECHO ----------------------------------------------------------------
ECHO.
PAUSE

REM -- https://www.tp-link.com/us/support/faq/840/