@REM ----------------------------------------------------------------
@REM __ C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-SCRIPT RUN GOOD OLE GOODSYNC SCRIPTOR FOLDER.BAT
@REM __
@REM __ BAT 59-SCRIPT RUN GOOD OLE GOODSYNC SCRIPTOR FOLDER.BAT
@REM __
@REM __ MATTHEW LANCASTER
@REM __ MATT.LAN@BTINTERNET.COM
@REM ----------------------------------------------------------------
@REM __ FROM ---- Fri 19-Oct-2018 15:05:42 Created Time _ Original Creation for GITHUB
@REM __ TO   ---- Fri 19-Oct-2018 17:30:00 Last Editor #1   1ST CREATE
@REM __
@REM __ FROM ---- Wed 07-Nov-2018 20:30:19 Last Editor #002 CHANGE USE HERE
@REM __ TO   ---- Wed 07-Nov-2018 23:34:00 Last Editor #002
@REM ----------------------------------------------------------------

@REM -- COPY FROM BROTHER BATCH FILE NOW A TWIN

@REM ----------------------------------------------------------------
@REM -- 001 SESSION
@REM -- CODER ADD -- MAKE GOODSYNC RUN THE JOB BY COMMAND-LINE
@REM -- MY FIRST COMMAND-LINE FOR GOODSYNC WORKING WELL
@REM -- GOODSYNC OUTPUT BY COMMANDLINE WAS IN A UNICODE CODEPAGE HAD
@REM -- TO BE DISCOVERED AND CONVERT FORM UNICODE INTO ASCII
@REM -- NOTEPAD++ HELP IN END WHAT TYPE CONVERSION DETECTED IN
@REM -- USUAL CODE THE RUN GOODSYNC AND THEN CHECK THE OUTPUT FOR
@REM -- THE PROCESS RAN
@REM ----------------------------------------------------------------
@REM __ FROM  Fri 19-Oct-2018 15:05:42
@REM __ TO    Fri 19-Oct-2018 17:30:00
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 002 SESSION
@REM -- LINK TO HERE _ MAKE CODE BECAUSE WAS GOING TO SHUTDOWN RESTART REBOOT ON ANOTHER COMPUTER
@REM -- AND WANTED A QUICKER SYNC-ER OF SCRIPT FOLDER BEFORE SHUT DOWN WITHOUT GOING TO GOODSYNC
@REM -- CODE ADDER
@REM -- LOT OF CHANGES AS USE __ SETLOCAL EnableDelayedExpansion
@REM -- MEAN A LOT OF VARIABLE FORMAT HAS TO CHANGE
@REM -- AND ALSO THE FIND OF STRING WASN'T WORKING TO LOOK UP IN UNICODE OUT
@REM -- THAT VERY EASY USE NEW COMMAND TO CHANGE TO ANSI FOR SEARCH HERE REQUIRE
@REM -- NOW MY OTHER CODE HAS TO BE UPDATED SAME AS HERE
@REM --
@REM -- THE BEGINNER OF VERY GOOD CODE
@REM -- ADD CODE _ EXTRA ARRAY PAIR WITH END OF OPERATION INFO STATUS
@REM -- NOT TAKE LONG WORKED FIRST TIME
@REM ----------------------------------------------------------------
@REM __ FROM  Wed 07-Nov-2018 20:30:19
@REM __ TO    Wed 07-Nov-2018 22:54:00
@REM __ TO    Wed 07-Nov-2018 23:34:00
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 003 SESSION
@REM -- ADD CAMERA BACKUP MODE
@REM -- OTHER DAY START AND THEN THIS PART TO DO
@REM ----------------------------------------------------------------
@REM __ FROM  Sun 21-Jul-2019 17:54:45
@REM __ TO    Sun 21-Jul-2019 18:10:00 -- 15 MINUTE
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 004 SESSION
@REM -- WORK TODAY
@REM ----------------------------------------------------------------
@REM AN END POINT AND MASSIVE CHANGE TO ENDER
@REM MUCH NEATER CODER AND LESS
@REM REMOVE END BLOCK TEXT WITH LOAD OF IF CONDITION AND MAKE IT SIMPLE
@REM WITH MAKE RESULT SHOW MORE EACH JOB
@REM AND EASIER UPDATE MORE ERROR RESULT FROM GOODSYNC
@REM Mon 03-Feb-2020 06:48:20
@REM Mon 03-Feb-2020 08:38:00 -- 1 HOUR 50 MINUTE
@REM -- BEEN SOME PREVIOUS WORK DAY BEFORE
@REM -- UPDATE END RESULT GOODSYNC
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 005 SESSION
@REM WORK TODAY
@REM ----------------------------------------------------------------
@REM MODIFY UP -- AND OTHER PROJECT
@REM -- 
@REM Tue 04-Feb-2020 10:12:00
@REM Tue 04-Feb-2020 23:56:00 -- 13 HOUR 44 MINUTE
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 00* SESSION SIXTH
@REM WORK TODAY
@REM ----------------------------------------------------------------
@REM ADD ROUTINE TO CHECK IF THIS PROJECT IS ALREADY RUN 
@REM BY ISSUE A AUTOHOTKEYS FIND WINDOW ROUTINE THAT PASS BY PARAMETER
@REM TAKE A SPECIAL TRICK PASS THE PARAMETER LINE WITH * FILL WHERE SPACE
@REM EXTRACT OTHER END -- LIKE CONCENTRATE ORANGE -- TETRA
@REM USELESS OTHERWISE
@REM ----------------------------------------------------------------
@REM A TON OF CODER AND LITTLE ROUTINE SIZE AFTER COMPACTOR 
@REM OF LEFT AFTER 
@REM NOT FIRST TIME DISCOVER THE OPERATION 
@REM FIRST TIME MAYBE FROM DOS TO AUTOHOTKEYS AND BACK AGAIN 
@REM EXIT CODE errorlevel AND PASS PARAMETER 
@REM ALWAYS PASS PARAMETER WITH * NOT ANY OTHER CHARACTER LIKE DASH -
@REM OR YOUR HEADACHE HURTING
@REM ----------------------------------------------------------------
@REM Sat 08-Feb-2020 12:00:22
@REM Sat 08-Feb-2020 14:25:00 -- 2 HOUR 25 MINUTE
@REM ----------------------------------------------------------------



@REM ----------------------------------------------------------------
@REM -- Located in Sync Location 1.. 2..
@REM ----------------------------------------------------------------
@REM -- 1..
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\
@REM ----------------------------------------------------------------
@REM -- 2..
@REM -- C:\SCRIPTER\SCRIPTER CODE -- GITHUB\
@REM ----------------------------------------------------------------
@REM -- 3.. AND HERE
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
@REM -- 4.. AND HERE PAIR SYNC-ER BOTH HAPPEN
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB - GOODSYNC.BAT
@REM -- C:\SCRIPTOR GITHUB\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB - GOODSYNC.BAT
@REM ----------------------------------------------------------------
@REM -- ALL SYNC-ER NOW ANY MINUTE _ NOW A UNIVERSAL CODE PROGRAM
@REM ----------------------------------------------------------------
@GOTO JUMP_REMMER
REM -----------------------------------------------------------------
REM THE CODE
REM ON THE HOUR
REM 1..
REM C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB.exe
REM THIS CODE WILL EITHER RUN --
REM 2..
REM GITHUB - ONLY
REM WHICH IS HERE RUN
REM BAT 45-SCRIPT RUN GITHUB.BAT
REM ..
REM OR WILL RUN
REM 3..
REM GOODSYNC SYNC SET AND THEN GITHUB
REM 4..
REM ON THE HOUR IT WILL BE BOTH
REM ..
REM IF IT RUN GOODSYNC SET JOB IT WILL RUN HERE ITSELF ME
REM BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM 5..
REM -----------------------------------------------------------------
REM ON THE HOUR
REM 1..
REM C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB.exe
REM IS RUN BY HERE
REM Autokey -- 19-SCRIPT_TIMER_UTIL_1.ahk
REM SUBROUTINE
REM GITHUB_MIDNIGHT_AND_MIDDAY_TIMER:
REM THIS WILL NOT ACTOR IF GOODSYNC2GO IS RUN BY THE D DRIVE PROCESS
REM -----------------------------------------------------------------
REM Mon 02-Sep-2019 11:45:40
REM -----------------------------------------------------------------
:JUMP_REMMER


@REM ----------------------------------------------------------------
@REM __ SET ADMIN A SAFE DOUBLE CHECKER WAY NOT A LOOPY ONE
@REM __ IF CAN'T GET IT TO GO ADMIN DOESN'T RSI INJURY ITSELF AND YOU
@REM ----------------------------------------------------------------

@ECHO OFF

ECHO THE ALL THE COMMAND LINE PARAMETER --  ENV VARS
IF NOT "%*"=="" ECHO %*
IF "%*"==""     ECHO -- NONE COMMANDLINE  PARAMETER --  ENV VARS WERE GIVE ----------
ECHO.

ECHO %* | FIND /i "/ADMIN" >nul
IF %errorlevel% EQU 0 SET ADMIN_REQUEST=/ADMIN

IF '%ADMIN_REQUEST%'=='/ADMIN' (
	@REM :: Check for ADMIN Privileges Again
	>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
	@IF '%errorlevel%' GTR '2' SET NOT_GOT_ADMIN=TRUE
)

@IF "%NOT_GOT_ADMIN%"=="TRUE" (
	ECHO AN ATTEMPT WAS MADE TO SET ADMIN BUT NOT SUCCESSFUL
	ECHO YOUR USER MUST BE A STANDARD USER OR SOMETHING LIKE HER
	ECHO SAVES GET STUCK IN A LOOP ASKING OR ALSO DELAY REQUIRING
	ECHO END
	PAUSE
	GOTO ENDE
	EXIT /B 1
)

@REM :: Check for ADMIN Privileges
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
@IF '%errorlevel%' GTR '2' (
	@REM Get ADMIN Privileges
	@ECHO Set UAC = CreateObject^("Shell.Application"^) >> "%temp%\getadmin.vbs"
	@ECHO UAC.ShellExecute "%~s0", "/ADMIN %*", "", "runas", 1 >> "%temp%\getadmin.vbs"

	"%temp%\getadmin.vbs"
	@DEL "%temp%\getadmin.vbs"
	GOTO ENDE
	@EXIT /B
)

IF '%ADMIN_REQUEST%'=='/ADMIN'     @ECHO GOT ADMIN PRIVILEGES -- BY PUSH FOR THEM
IF NOT '%ADMIN_REQUEST%'=='/ADMIN' @ECHO GOT ADMIN PRIVILEGES -- BY NATURAL


@ECHO OFF



ECHO ----------------------------------------------------------------

@REM SET AT TOP
@REM SETLOCAL EnableDelayedExpansion
@REM SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
SETLOCAL EnableDelayedExpansion

REM ---- FILENAME WITHOUT EXTENSION
@SET TITLE_VAR=%~n0
REM ---- FILENAME WITH   EXTENSION
@SET TITLE_VAR=%~n0%~x0
REM ---- FULL SCRIPT PATH
@SET TITLE_VAR=%~f0


REM ----
REM How can I echo a newline in a batch file? - Stack Overflow
REM https://stackoverflow.com/questions/132799/how-can-i-echo-a-newline-in-a-batch-file
REM ----
REM ---- EXAMPLE ---- ECHO READY!\n!STEADY!\n!GO
REM ----
(set \n=^
%=Do not remove this line=%
)

@TITLE !TITLE_VAR!

REM TITLE TO FINDER -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT 
SET MYSCRIPT_AHK=C:\SCRIPTER\SCRIPTER CODE -- AUTOHOTKEY\AUTOKEY -- 89-WIN EXIST RETURN EXIT CODE.AHK
set PARAM_PASS=%~N0
set PARAM_PASS=%PARAM_PASS: =*%
ECHO.
ECHO ----------------------------------------------------------------
ECHO COMMAND RUN ----------------------------------------------------
SET MYSCRIPT_AHK_STRIPPER=%MYSCRIPT_AHK%
SET MYSCRIPT_AHK_STRIPPER=%~NX1
ECHO @START /WAIT "" "%MYSCRIPT_AHK_STRIPPER%" %PARAM_PASS%
START /WAIT "" "%MYSCRIPT_AHK%" %PARAM_PASS%
ECHO.
IF NOT %errorlevel%==0 ECHO SCRIPT ALREADY RUN __ EXITCODE

IF %errorlevel%==0 GOTO OPERATION_AHEAD_GOOD
ECHO ----------------------------------------------------------------
ECHO -- SCRIPT HERE ALREADY RUN -------------------------------------
ECHO.
ECHO %~N0%~X0
ECHO.
ECHO %~F0
ECHO.
ECHO -- EXIT DECISION -----------------------------------------------
ECHO ----------------------------------------------------------------
TIMEOUT /T 40
GOTO ENDE 

:OPERATION_AHEAD_GOOD
 
ECHO READY STEADY GO
ECHO READY!\n!STEADY!\n!GO
ECHO.


ECHO %* | FIND /i "GOODSYNC_MODE" >nul
IF %errorlevel% EQU 0 (
REM ECHO !TITLE_VAR! | FIND /i "BAT 59-RUN GOODSYNC SET SCRIPTOR" >nul
REM @if !errorlevel!==0 (
	SET MODE_RUN=GOODSYNC
	REM @CD /D "C:\SCRIPTER"
	GOTO START
)

ECHO %* | FIND /i "CAMERA_BACKUP_MODE" >nul
IF %errorlevel% EQU 0 (
	SET MODE_RUN=CAMERA_BACKUP
	GOTO START
)

	REM TEMP REMMER
	REM ---------------------------------------------------------------------
	REM SET MODE_RUN=CAMERA_BACKUP
	REM GOTO START
	REM ---------------------------------------------------------------------

ECHO %* | FIND /i "CAMERA_BACKUP_CLOUD" >nul
IF %errorlevel% EQU 0 (
	SET MODE_RUN=CAMERA_BACKUP_CLOUD
	GOTO START
)



ECHO %* | FIND /i "D_DRIVE_GOODSYNC_JOB_SET" >nul
IF %errorlevel% EQU 0 (
	SET MODE_RUN=D_DRIVE_GOODSYNC_JOB_SET
	GOTO START
)

ECHO %* | FIND /i "GITHUB_MODE" >nul
IF %errorlevel% EQU 0 (
	SET MODE_RUN=GITHUB
	REM @CD /D "C:\SCRIPTOR GITHUB"
	GOTO START
)


@REM -- COMMAND LINE DEMO
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT CAMERA_BACKUP_MODE


REM SET MODE_RUN=CAMERA_BACKUP
REM GOTO START


IF "!MODE_RUN!"=="" (
	SET MODE_RUN=CAMERA_BACKUP
	SET MODE_RUN=GITHUB
	REM @CD /D "C:\SCRIPTER"
	GOTO START
)


:START


ECHO %* | FIND /i "WITH_GITHUB_MODE" >nul
IF %errorlevel% EQU 0 SET MODE_RUN_WITH_GITHUB=TRUE

REM SET TITLE_RUN_MODE=BAT 45-SCRIPT RUN GITHUB - GOODSYNC
REM SET MODE_RUN=GITHUB

REM ECHO.
ECHO RUN MODE -- !MODE_RUN!

REM ECHO !TITLE_RUN_MODE!

SET PATH_GIT="C:\Program Files\Git\bin"
SET GoodSync_GSync="C:\Program Files\Siber Systems\GoodSync\gsync.exe"

REM ----
REM CONVERTCP download | SourceForge.net
REM https://sourceforge.net/projects/convertcp/
REM ----
REM -----------------------------------------------------------------
REM STRIP QUOTE THIS BIT BEFORE END :"=
REM -----------------------------------------------------------------
REM EXAMPLE !VAR:"=!
REM EXAMPLE !Sources_02[%%a]!
REM -----------------------------------------------------------------

ECHO.
IF EXIST=="%~dp0ConvertCP\convertcp.exe" GOTO JUMP
	ECHO ------------------------------------------------------------------------
	ECHO THE EXE NAME REQUIRE TO CONVERT UNICODE OUTPUT FROM GOODSYNC IS NOT HERE
	ECHO %~dp0ConvertCP\convertcp.exe
	ECHO ------------------------------------------------------------------------
	ECHO IDEAL LOCATE WITH SCRIPT DIR
	ECHO %~dp0
	ECHO \CONVERTCP\CONVERTCP.EXE
	ECHO ------------------------------------------------------------------------
	ECHO EXIT WANT TO
	ECHO GOODSYNC WILL RUN AND NOT ANY RESULT_ DISPLAY
	ECHO ------------------------------------------------------------------------
	PAUSE
:JUMP

@SET ConvertCP="%~dp0ConvertCP\convertcp.exe"
IF EXIST==!ConvertCP! (
	ECHO ------------------------------------------------------------------------
	ECHO THE EXE REQUIRE TO CONVERT UNICODE OUTPUT FROM GOODSYNC IS LOCATE FINE
	ECHO ------------------------------------------------------------------------
	ECHO !ConvertCP:"=!
	ECHO ------------------------------------------------------------------------
)



@REM WELL IT TOOK A WHILE TO FIND CODE PAGE OF TEXT DOCUMENT
@REM ANSWER CAME FROM A PAG THAT GIVE IT NOTEPAD++ IN BOTTOM RIGHT CORNER TELL THE ANSWER
@REM AND FOUND FROM THERE
@REM ----
@REM text files - Notepad++ can recognize encoding? - Stack Overflow
@REM https://stackoverflow.com/questions/14246956/notepad-can-recognize-encoding/14247070#14247070
@REM ----

@ECHO OFF


@IF NOT EXIST "%~dp0#NFS-%COMPUTERNAME%\" MKDIR "%~dp0#NFS-%COMPUTERNAME%\"

REM Write %~n0 to get the filename without the extension.
SET FILENAME_ER="%~dp0#NFS-%COMPUTERNAME%\%~n0_GOODSYNC_OUTPUT_#NFS_EX.TXT"
SET FILENAME_ER_2="%~dp0#NFS-%COMPUTERNAME%\%~n0_GOODSYNC_OUTPUT_#NFS_EX.TXT.TMP"
SET FILENAME_ER_4="%~n0_GOODSYNC_OUTPUT_#NFS_EX.TXT"
@REM ------------------------------------------------------------
@REM EXAMPLE WITHOUT VARIABLE
@REM ------------------------------------------------------------
@REM CMD /A /C "%GoodSync_GSync% sync "C SCRIPTOR __ y _ 7G __ GITHUB"      >! !"

SET LDA=0

IF !MODE_RUN!==GOODSYNC                  GOTO GOODSYNC________________SET_ARRRAY
IF !MODE_RUN!==GITHUB                    GOTO GITHUB__________________SET_ARRRAY
IF !MODE_RUN!==CAMERA_BACKUP             GOTO CAMERA__________________SET_ARRRAY
IF !MODE_RUN!==D_DRIVE_GOODSYNC_JOB_SET  GOTO D_DRIVE_GOODSYNC_JOB____SET_ARRRAY
IF !MODE_RUN!==CAMERA_BACKUP_CLOUD       GOTO CAMERA_TO_CLOUD_LONGER__SET_ARRRAY


ECHO INFO----RAR
ECHO MUST BE AN ERROR ESCAPE FROM RUN PRESS CLOSE WINDOW -- CONTROL C
PAUSE
GOTO ENDE

:GOODSYNC________________SET_ARRRAY

SET GoodSync_GSync="C:\Program Files\Siber Systems\GoodSync\gsync.exe"
SET AI=SET /A LDA=LDA+1

!AI! && SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 1X"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 2E"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 3L"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 4G_ GSD"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 5P"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ x _ 7G TO 8M_ GSD"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 00 C SCRIPTER FOLDER"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 00 SCRIPT RUN"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 1X"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 2E"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 3L"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 4G"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 5P"
!AI! && SET Sources[!LDA!]="C C DRIVE ROOT CROSS 8M _ GSD"
!AI! && SET Sources[!LDA!]="C ISO __ 7G TO 1X"
!AI! && SET Sources[!LDA!]="C ISO __ 7G TO 2E"
!AI! && SET Sources[!LDA!]="C ISO __ 7G TO 3L"
!AI! && SET Sources[!LDA!]="C ISO __ 7G TO 4G"
!AI! && SET Sources[!LDA!]="C ISO __ 7G TO 5P"
!AI! && SET Sources[!LDA!]="C ISO __ 7G TO 8M"
!AI! && SET Sources[!LDA!]="C GOODSYNC __ 7G TO 1X"
!AI! && SET Sources[!LDA!]="C GOODSYNC __ 7G TO 2E"
!AI! && SET Sources[!LDA!]="C GOODSYNC __ 7G TO 3L"
!AI! && SET Sources[!LDA!]="C GOODSYNC __ 7G TO 4G"
!AI! && SET Sources[!LDA!]="C GOODSYNC __ 7G TO 5P"
!AI! && SET Sources[!LDA!]="C GOODSYNC __ 7G TO 8M"
!AI! && SET Sources[!LDA!]="D # MY DOC __ 7G TO 4G_1"
!AI! && SET Sources[!LDA!]="D BT Cloud Sync _ 00 _ Caller ID"
!AI! && SET Sources[!LDA!]="D #0 1 INSTALL 7G 4G_1"
!AI! && SET Sources[!LDA!]="D #0 1 INSTALL 7G 8M_1"
!AI! && SET Sources[!LDA!]="VB G7 VB-NT 8M _3_ LONGER"
!AI! && SET Sources[!LDA!]="VB G7 VB-NT 5P _3_ LONGER GSD"
!AI! && SET Sources[!LDA!]="VB G7 VB-NT 4G _3_ LONGER"
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""



REM GOTO NEXT_CONTINUE

:GITHUB__________________SET_ARRRAY

SET PATH_GIT="C:\Program Files\Git\bin"
SET GoodSync_GSync="C:\Program Files\Siber Systems\GoodSync\gsync.exe"
SET AI=SET /A LDA=LDA+1

!AI! && SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 4G INCL"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 4G -- 4G SUCCESS"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 5P -- 5P SUCCESS"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 4G INCL"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ 7G TO 4G_"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00 VB6 VB-NT -- ROOT 0 COMP_NAMER"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_01 -- ROOT 1"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 00_Best_VB_01 02 SCRIPTER CODE -- GITHUB"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 02 BAT 59-RUN GOODSYNC SET SCRIPTOR -- VB WANT QUICK CHANGER"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ 02 BAT 59-RUN GOODSYNC SET SCRIPTOR--VB -- 00_Best_VB_01"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ MY WEB 01 MAIN"
!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB _ MY WEB 02 WORD SET"
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""



:JUMPER

REM -----------------------------------------------------------------
REM -- VAR LINE HERE GO AT END AS GOT SCRIPT WITHIN 
REM -- GOODSYNC TO RUN WHEN DONE

REM -----------------------------------------------------------------
REM -- ALSO HERE IS REM OUT -- ONLY TO SHOW
REM -- BUTTY GITHUB HAS ABILITY RUN ON OWN WITH ONE FOLDER NONE MULTIPLE
REM -- AND THAT WILL BE AT THE END -- SEARCH IF WANTED TO
REM -----------------------------------------------------------------
REM -- Sat 29-Feb-2020 11:58:00
REM -----------------------------------------------------------------
REM -- SET /A LDA=LDA+1
REM -- SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB"
REM -----------------------------------------------------------------

SET AI=SET /A LDA=LDA+1

REM !AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_#_1_2"
REM GOTO JUMP
	REM SET /A LDA=LDA+1
	REM !AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_001_PAIR_01_BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT"
	REM SET /A LDA=LDA+1
	REM !AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_001_PAIR_02_BAT 45-SCRIPT RUN GITHUB - GOODSYNC.BAT"
REM :JUMP
REM !AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ SYNC_FOLDER_Multiple_Thread Port Scanner 02 CON"

!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""
!AI! && SET Sources[!LDA!]=""

REM -----------------------------------------------------------------
REM -- LEAVE UNTIL END AND THEN THE GITHUB SCRIPT WILL RUN FROM GOODSYNC CALL SCRIPT THE
REM -- BAT 45-SCRIPT RUN GITHUB.BAT
REM -----------------------------------------------------------------
REM -- MAYBE WE DON'T WANT GITHUB UPDATE WHILE GOODSYNC MODE WORKER
REM -----------------------------------------------------------------

IF !MODE_RUN_WITH_GITHUB!==TRUE GOTO WANT_GITHUB
IF !MODE_RUN!==GITHUB           GOTO WANT_GITHUB
GOTO NEXT_CONTINUE

:WANT_GITHUB

	SET AI=SET /A LDA=LDA+1
	!AI! && SET Sources[!LDA!]="C SCRIPTOR __ y _ 7G __ GITHUB"


:NEXT_CONTINUE
GOTO NEXT_CONTINUE
:D_DRIVE_GOODSYNC_JOB____SET_ARRRAY
	SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"
	SET AI=SET /A LDA=LDA+1
	
	!AI! && SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 4G _ JOB SET"
	!AI! && SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 8G _ JOB SET"
	!AI! && SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 4G GSD"
	!AI! && SET Sources[!LDA!]="0001 C GOODSYNC 2 GO -- D TO D __ 7G 8M GSD"
	
:NEXT_CONTINUE
GOTO NEXT_CONTINUE
:CAMERA__________________SET_ARRRAY

	REM  ALL JOB FROM ASUS-7 COMPUTER
	SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"
	SET AI=SET /A LDA=LDA+1

	GOTO CAMERA_2

	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G SHARE"
	!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G GSD"
	!AI! && SET Sources[!LDA!]="D DSC __ 7G 8M #GSD"
	!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G #GSD"
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 4G_SAMSUNG 1TB_2020 #GSD"
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 7G 4G"
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 400 DAY 7G 4G __ 2019 CyberShot HX60V"
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 400 DAY 7G 4G __ 2020 CyberShot HX60V"
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 01"
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 02 4G"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 03 - VIDEO MINE 2020"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 04 - VIDEO MINE 02 4G 7G"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 05 - VIDEO MINE 01 _ SAM 1TB 2020"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 07 - VIDEO MINE 01"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G 5P"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G 8M"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 1 1 MM"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 1 1 MM 5P"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 1 1 MM 8G"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 1 HC"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 1 HC 2 BUNKER"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC ROOT"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 3 ROOT 1"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 3 ROOT 2"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 3 ROOT 3 DATE ALPHA"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 4 AUTO"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 4 VIRTUAL 1"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 4 VIRTUAL 2"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 5 LITT"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC ROOT"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC__FOR PHOTO GD 1 7G"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC__FOR PHOTO GD 2 7G"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC__FOR PHOTO GD 3 5P"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC__FOR PHOTO GD 3 8M"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 1 MM IM1 & VI1"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 2 HC"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 3 HC ROOT"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 4 AUTO"
	!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 5 LITT"
	
	@REM ---- PRE CLOUD
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #8 4G-F-HDD TO 7G-SAMSUNG-3-HDD"
	@REM ---- ITEM COVER BY ON BEFORE
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #8 D-HDD 4K ULTRA 4G 7G" 
	
	@REM ---- ALL CLOUD BEGIN
	!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2020+ #1 DSC CYBERSHOT 2020"
	
	REM BETTER FILTER REQUIRE NOT +2020 NIT MORE LIKE EXCLUDE 2019 2018 
	REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #7 +2020 --"
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #1 DSC CYBERSHOT 2019"
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #2 DSC 2019+SCREENCASTIFY"
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 DSC CYBERSHOT 2020 D-HDD -- IMAGE"
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 DSC CYBERSHOT 2020 SAM-F-HDD 1_TB -- MP4"
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 F-HDD DSC--2018+CCTV HIKVISION"
	!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #4 D-HDD 2019+4K ULTRA"
	
	!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 03 OD MATT4"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 08 - VIDEO MINE 01 4G_F TO 7G_SUMSUNG_3"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 09 - VIDEO MINE 01 OD-MATT4"
	!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 10 - VIDEO MINE 2020 OD-MATT4"
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""

	
REM ---------------------
REM Count = 025 -- Thu 13-Feb-2020 14:42:20
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Waiting for 8(120) sec on verb GET: Server says: Forbidden (status code 403): Rate Limit Exceeded
REM ---------------------
REM ---------------------
REM Count = 026 -- Thu 13-Feb-2020 14:43:18
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Server Account not found
REM ---------------------
REM ---------------------
REM Count = 027 -- Thu 13-Feb-2020 14:45:19
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Error locking folder: downloading lock file: Skip Close on Disconnected/Stopped file system
REM ---------------------
REM ---------------------
REM Count = 028 -- Thu 13-Feb-2020 14:45:54
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Error locking folder: checking for lock file: no reply after 120(90)-sec timeout on verb GetInfo:9: Recv: Server says: ServerPipe Receiver is still computing response (status code 518)
REM ---------------------
REM ---------------------
REM Count = 029 -- Thu 13-Feb-2020 14:47:10
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM SSL: Cannot load trusted root certificates from system: error:0B084009:x509 certificate routines:X509_load_cert_crl_file:PEM lib[b084009]
REM ---------------------
REM ---------------------
REM Count = 030 -- Thu 13-Feb-2020 14:47:33
REM ---------------------
REM Form FindWindow ---
REM Administrator:  C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR.BAT
REM ---------------------
REM Checking root folder: GetInfo: The device is not ready.  (error 21)


REM files have changed (excluding renames), more than a threshold of 20%. So the job will not synchronize automatically.	
	
REM Error analyzing C:\SCRIPTOR GITHUB: Cannot parse state file, delete it if it became corrupted: C:/SCRIPTOR GITHUB: End of file at pos 491520

	
:CAMERA_2
SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"
SET AI=SET /A LDA=LDA+1

!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO MY CAMERA FUJI"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO MY CAMERA HX"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO MY CAMERA HX-V"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO MY SYNC-VB-DSC"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO NOKIA"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO OUTDOOR"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO SAMSUNG 128"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO USB_32GB"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD FIND ME INFO V_DSC_ME"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 EVER _ #1 SONY HX60V CAMERA"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 EVER _ #2 SMB FUJI XP90"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 EVER _ #2 SMB FUJI XP90 _ FIND ME INFO"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 EVER _ #2 SMB FUJI XP90 _ FIND ME INFO SYNC"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - LEFT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V - RIGHT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #1 MEDIA CARD BACKUP -- =MC - HX60V1"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #2 MCSDV0  MC BACKUP -- 7G 4G HDD - LEFT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #2 MCSDV0  MC BACKUP -- 7G 4G HDD -RIGHT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #2 MCSDV0  MC BACKUP -- 7G 8M HDD - LEFT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #2 MCSDV0  MC BACKUP -- 7G 8M HDD - RIGHT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #3 MCSDV0  MC BACKUP -- 4G TO HDD - LEFT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #3 MCSDV0  MC BACKUP -- 4G TO HDD - RIGHT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #3 MCSDV0  MC BACKUP -- 4G TO HDD _GSD"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #3 MCSDV0  MC BACKUP -- 7G TO HDD"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #3 MCSDV0  MC BACKUP -- 8M TO HDD"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G GSD - LEFT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G GSD - RIGHT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G SHARE - LEFT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G SHARE - RIGHT"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G SHARE 1"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #4 MCSDV0  MC BACKUP -- 4G TO 7G SHARE 2"
!AI! && SET Sources[!LDA!]="D DSC __ MC CARD V0 _____ #5 7G 4G __ 2019 CyberShot HX60V"

REM !AI! && SET Sources[!LDA!]="D DSC EVER 4_CLOUD_2TB ROIDSRIM WHOLE 01"

!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #0  ALL"

REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #1  2011"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #2 +2018"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #3 +2019"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #4 +2015"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #4 +2015 _ 4G TO GD"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #5 -2015"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE #5 -2015 _ 4G TO GD"

!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2010+ #1 NIKON"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2012+ #1 NOKIA E72"

REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2017+ #1 DSC CYBERSHOT 2017"
REM !AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2018+ #2 DSC CYBERSHOT 2018"

!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2018+ #3 FUJI"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2018+ #4 SAMSUNG MINI S5"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2018+ #5 GO PRO"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2018+ #7 DOUBLE SCREEN"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2018+ #8 CCTV HIKVISION"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2019+ #1 DSC CYBERSHOT 2019"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2019+ #2 DSC 2019+SCREENCASTIFY"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2020+ #1 DSC CYBERSHOT 0000 D-HDD MP4"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2020+ #1 DSC CYBERSHOT 2020 D-HDD MP4"
!AI! && SET Sources[!LDA!]="D DSC EVER GOOGLE 2020+ #1 DSC CYBERSHOT 2020 T-HDD MP4"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #1 DSC 0000+SONY MP4 00 SAM 4G 7G"

REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #1 DSC 2015+SONY"
REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #1 DSC 2015+SONY MP4"
REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #1 DSC 2015+SONY MP4 4G SAM"
REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #1 DSC 2015+SONY MP4 7G SAM"
REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #5 +2015 --"
REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #5 -2015 --"
REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #7 +2018 --"

!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #7 +2020 --"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #8 4G-F-HDD TO 7G-SAM-3-HDD COPY BELOW"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE #8 D-HDD 4K ULTRA 4G 7G"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #1 DSC 2015+ _AGAIN"

REM !AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #1 DSC CYBERSHOT 2019"

!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #1 DSC CYBERSHOT 2020"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2019+ #2 DSC 2019+SCREENCASTIFY"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 DSC CYBERSHOT 2020 D-HDD -- IMAGE"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 DSC CYBERSHOT 2020 SAM-F-HDD 1_TB -- MP4"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #1 F-HDD DSC--2018+CCTV HIKVISION"
!AI! && SET Sources[!LDA!]="D DSC EVER ONE DRIVE 2020+ #4 D-HDD 2019+4K ULTRA"
!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 4G-F-HDD TO 7G SAM-3-HDD"
!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 4G_SAMSUNG 1TB_2020"
!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 4G_SAMSUNG 1TB_2020 #GSD"

REM !AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 4G_SAMSUNG 1TB_2020 #GSD (1)"

!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 0 DSC 7G 4G"

REM !AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 400 DAY 7G 4G __ 2019 CyberShot HX60V"

!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 00 - 400 DAY 7G 4G __ 2020 CyberShot HX60V"
!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 01 8M"
!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 01 NOT GSD"
!AI! && SET Sources[!LDA!]="D DSC VI_2 __  G P DSC SYNC DSC ARC 01 - 400 DAY 03 OD MATT4"

REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 02 - IMAGE ALL"
REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 03 - ART"

!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 03 - VIDEO MINE 2020"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 03 - VIDEO MINE 2020 GSD"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 04 - VIDEO MINE 02 4G 7G"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 04 - VIDEO MINE 02 4G 7G #GSD"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 05 - VIDEO MINE 01 _ SAM 1TB 2020"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 07 - VIDEO MINE 01"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 07 - VIDEO MINE 01 8M"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 08 - VIDEO MINE 01 4G_F TO 7G_SUMSUNG_3"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 09 - VIDEO MINE 2020 OD-MATT4"
!AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 10 - VIDEO MINE 01 OD"

REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  G P DSC SYNC DSC ARC 10 - VIDEO MINE 01 OD-MATT4 (1)"
REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  YOUTUBE DSC MP4 4G 4G YT_1 YT_2"
REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  YOUTUBE DSC MP4 C-HDD 7G YT_1"
REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  YOUTUBE DSC MP4 D-HDD 4G YT_1"
REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  YOUTUBE DSC MP4 D-HDD C-HDD YT_1 YT_2"
REM !AI! && SET Sources[!LDA!]="D DSC VI_3 __  YOUTUBE DSC MP4 D-HDD YT_1 YT_2"
REM !AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE MATT.LITT - NOT USE"
REM !AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE METAL.LITT - NOT USE"

!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 1 1 MM 8G"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 2 HC BUNKER"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 3 HC AUTO"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X1 4 HC LITT"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC__FOR PHOTO GD 3 8M"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 2 HC__FOR PHOTO GD 4 8M"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X2 4 HC__FOR PHOTO GD 7G 5P"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 1 MM IM1 & VI1"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME GOOGLE M_ X3 2 HC"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G 5P"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G 8M"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G LINK 01 HDD-D"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G LINK 02 HDD-D"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G LINK 04"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G LINK 05"
!AI! && SET Sources[!LDA!]="D DSC VI_DSC_ME __ 7G LINK 08"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G #GSD"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G D DSC EVER ONE DRIVE #8 4G-F-HDD TO 7G-SAM-3-HDD COPY BELOW"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G __ 2015+ Sony"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G __ 2019 CyberShot HX60V"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 4G __ QUICKER _ 2015+"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 5P"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 8M"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 8M #GSD"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 8M __ 2015+ Sony"
!AI! && SET Sources[!LDA!]="D DSC __ 7G 8M __ 2019 CyberShot HX60V"


	
	
	
:NEXT_CONTINUE
GOTO NEXT_CONTINUE
:CAMERA_TO_CLOUD_LONGER__SET_ARRRAY

	REM ALL JOB FROM ASUS-7 COMPUTER
	SET GoodSync_GSync="D:\GoodSync\x64\gsync.exe"

	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	!AI! && SET Sources[!LDA!]=""
	
:NEXT_CONTINUE



REM -----------------------------------------------------------------
REM -- SORT THE EMPTY ARRAY FOR VOID VALUE
REM -----------------------------------------------------------------
SET LDB=0
for /L %%a in (1,1,!LDA!) do (
	IF NOT !sources[%%a]!=="" (
		SET /A LDB=LDB+1
		SET Sources_02[!LDB!]=!sources[%%a]!
	)
)

SET LDA=%LDB%

REM -- TEST DEBUG
REM SET LDA=1

REM -----------------------------------------------------------------
REM TEST ONLY RUN 1 JOB QUICKER DEBUGGING
REM SET LDA=1
REM -----------------------------------------------------------------

	
REM EQU - EQUAL
REM NEQ - NOT EQUAL
REM LSS - LESS THAN
REM LEQ - LESS THAN OR EQUAL
REM GTR - GREATER THAN
REM GEQ - GREATER THAN OR EQUAL

REM SET COUNTER=2
REM IF /I !COUNTER! GEQ 0 SET PAD=0
REM IF /I !COUNTER! GEQ 10 SET PAD=0
REM IF /I !COUNTER! GEQ 100 SET PAD=0
REM IF /I !COUNTER! GEQ 1000 SET PAD=0
REM IF /I !COUNTER! GEQ 10000 SET PAD=0


ECHO.
ECHO ------------------------------------------------------------------------


REM -----------------------------------------------------------------
REM STRIP QUOTE THIS BIT BEFORE END :"=
REM -----------------------------------------------------------------
REM EXAMPLE !VAR:"=!
REM EXAMPLE !Sources_02[%%a]!
REM -----------------------------------------------------------------

for /L %%a in (1,1,!LDA!) do (
	IF /I %%a LSS 10 (SET PADD=0) ELSE SET PADD=
	ECHO !PADD!%%a -- !Sources_02[%%a]:"=!
)


SET "ANOTHER_JOB_COUNTER=0"
SET "ERROR_COUNT=0"
SET "X=0"
SET "FAULT_COUNTER=0"
SET "Sync_Runner_FAULT_TOTAL=TRUE"

REM -----------------------------------------------------------------
REM -- DON'T REQUIRE HERE AS LONG AS RUN GITHUB SYNC JOB
REM -- IT HAS SCRIPT THAT DOES IT ALSO
REM -----------------------------------------------------------------
REM "%~dp0\BAT 59-RUN GOODSYNC SET SCRIPTOR-AHK_MINIMIZE.ahk" !TITLE_VAR!  /QUICK_INTRO_DUMMY_RUN
REM -----------------------------------------------------------------
ECHO ----------------------------------------------------------------

@ECHO OFF
@ECHO ON
@ECHO OFF
SET LDG=0
SET LDM=
SET LDR=0


REM -------------------------------------------------------------
REM -------------------------------------------------------------
REM TWO TYPE OF WAY
REM IF INPUT STRING HAVE SPACE AND COLON SPECIAL CHARACTER 
REM UPSET THE FLOW OF OD ONE STRING
REM ENCLOSE QUOTE AND MAKE HARD 2ND METHOD ALLOW
REM RESULT OUTPUT 
REM 2ND METHOD SHOW CHARACTER POSITION BEGIN LINE
REM Changes: 0
REM 1:Changes: 0
REM -------------------------------------------------------------
REM MY IDEA FIND STRING AND RESULT HAVE NUMERIC VALUE ABOVE NAUGHT
REM THE DOT CHARACTER ARE WILD CARD
REM -------------------------------------------------------------
REM Wed 23-Sep-2020 16:42:00
REM -------------------------------------------------------------
REM ECHO -------------------------------------------------------------
REM ECHO Changes: 0|FINDSTR /i Changes..[0-9]
REM ECHO Changes: 0|FINDSTR /i /nrc:"Changes: [0-9]"
REM ECHO -------------------------------------------------------------
REM PAUSE


FOR /L %%a in (1,1,!LDA!) DO (

	ECHO.
	IF /I %%a   LSS 10 (SET PADD1=0) ELSE SET PADD1=
	IF /I !LDA! LSS 10 (SET PADD2=0) ELSE SET PADD2=

	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO !PADD1!%%a of !PADD2!!LDA! -- START
	ECHO ----------------------------------------------------------------


	
	REM -----------------------------------------------------------------
	REM STRIP QUOTE THIS BIT BEFORE END :"=
	REM -----------------------------------------------------------------
	REM EXAMPLE !VAR:"=!
	REM EXAMPLE !Sources_02[%%a]!
	REM -----------------------------------------------------------------
	REM CREDIT FINDER AT END OF CODE
	REM -----------------------------------------------------------------
	REM -- STRIP QUOTE EITHER END -- EXAMPLE -- !GoodSync_GSync! NORMAL DISPLAY !GoodSync_GSync:"=! STRIP QUOTE WAY
	REM -----------------------------------------------------------------

	ECHO !Sources_02[%%a]:"=!

	ECHO ----------------------------------------------------------------
	ECHO RUN COMMAND
	ECHO ----------------------------------------------------------------

	ECHO.
	ECHO %GoodSync_GSync% sync !Sources_02[%%a]!^>!FILENAME_ER!
	IF %%a  LSS 2  ECHO.
	REM -----------------------------------------------------------------
	REM LOOK GOOD LINE -- THE FIRST ENTRY HERE NEST LOOP NOT SPACE GAP PRINT HERE
	REM -----------------------------------------------------------------
	
	%GoodSync_GSync% sync !Sources_02[%%a]!>!FILENAME_ER!

	REM  OUT EXAMPLE
	REM  "C:\SCRIPTER\SCRIPTER CODE -- BAT\#NFS-7-ASUS-GL522VW\BAT 59-RUN GOODSYNC SET SCRIPTOR_GOODSYNC_OUTPUT_#NFS_EX.TXT"
	REM  "C:\SCRIPTER\SCRIPTER CODE -- BAT\#NFS-7-ASUS-GL522VW\BAT 59-RUN GOODSYNC SET SCRIPTOR_GOODSYNC_OUTPUT_#NFS_EX.TXT"
	
	
	REM ----------------------------------------------------------------
	REM ------ 1200 UCS-2 (UTF-16 Little Endian Byte Order)
	REM ----------------------------------------------------------------
	REM SEND OUTPUT FILE FROM GOODSYNC RUN TO COMMAND CONSOLE WINDOW
	REM ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
	%ConvertCP% 1200 0 /i !FILENAME_ER! /o !FILENAME_ER_2!
	DEL !FILENAME_ER! >nul 2>nul
	RENAME !FILENAME_ER_2! !FILENAME_ER_4!
	TYPE !FILENAME_ER!


	REM ------------------------------------------------------------
	REM -- SYMBOL -- CYMBAL
	REM -- THE SET COMMAND NOT HAVE SPACE BEFORE = SYMBOL
	REM ------------------------------------------------------------
	SET ANALYSIS_COMPLETE=FALSE
	SET SYNC_RUNNER=FALSE
	SET SYNC_RUNNER_ONE=FALSE
	REM ------------------------------------------------------------
	SET ANOTHER_JOB=FALSE
	SET UNRESOLVED_CONFLICTS=FALSE
	SET COMPUTER_IS_OFFLINE=FALSE
	SET JOB_NOT_FOUND=FALSE
	SET NONE_TO_DO_______=FALSE
	SET JOB_IS_USE_BY_ANOTHER_PROCESS=FALSE
	SET NONE_TO_DO_______=FALSE
	SET NET_PATH_NOT_FIND=FALSE
	SET VOLUME_NOT_FOUND=FALSE
	SET SYNC_FOLDER_NOT_EXIST=FALSE
	SET DELETE_IT_IF_IT_BECAME_CORRUPTED=FALSE
	SET SPECIFIED_NETWORK_NAME_IS_NOT_FINDAR=FALSE
	SET OPERATION_HIDE_ERROR=FALSE
	SET FILE_HAVE_CHANGE_MORE_THAN_THRESHOLD=FALSE
	SET NOT_ABLE_PARSE_STATE_FILE_DELETE_IT=FALSE
	SET PROGRAM_RETURNED_CONTROL_ADD_VBCR=TRUE
	SET CHANGE_HAPPEN=FALSE
	REM ------------------------------------------------------------
	
	IF /I %%a   GEQ 13 PAUSE

	REM ------------------------------------------------------------
	REM ------------------------------------------------------------
	REM ------------------------------------------------------------
	REM ------------------------------------------------------------

	REM -- ALBION VS WATFORD
	REM -- Sat 08-Feb-2020 17:30:00
	REM -- Sat 08-Feb-2020 20:00:00 -- 2 HOUR 30 MINUTE
	
	FIND /i "-- analysis complete" !filename_er!>nul
	if !errorlevel!==0 set analysis_complete=true

	FIND /i "SYNC: RUNNING:" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET ANALYSIS_COMPLETE=TRUE

	FIND /i "SYNC COMPLETE." !FILENAME_ER!>nul
	IF !errorlevel!==0 SET ANALYSIS_COMPLETE=TRUE
	IF !errorlevel!==0 SET SYNC_RUNNER_ONE=TRUE



	
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM TWO TYPE OF WAY
	REM IF INPUT STRING HAVE SPACE AND COLON SPECIAL CHARACTER 
	REM UPSET THE FLOW OF OD ONE STRING
	REM ENCLOSE QUOTE AND MAKE HARD 2ND METHOD ALLOW
	REM -------------------------------------------------------------
	REM MY IDEA FIND STRING AND RESULT HAVE NUMERIC VALUE ABOVE NAUGHT
	REM THE DOT CHARACTER ARE WILD CARD
	REM -------------------------------------------------------------
	REM Wed 23-Sep-2020 16:42:00
	REM -------------------------------------------------------------
	REM ECHO Changes: 0|FINDSTR /i Changes..[0-9]
	REM ECHO Changes: 0|FINDSTR /i /nrc:"Changes: [0-9]"
	REM -------------------------------------------------------------
	REM INSENSITIVE REGEX SEARCH
	REM /NRC
	REM /IRC
	REM INSENSITIVE REGEX CASE
	REM IGNOR       REGEX CASE -- SOME PEOPLE TALKER 
	REM NUMERIC     REGEX 
	REM NUMERIC     REGEX NRC  -- ZAMBIAN NRC NUMBER -- ZAMBIA-N
	REM ZAMBIAN     REGEX CASE -- MEAN IDEA FUZZY
	REM AN EXAMPLE OF AN NRC NUMBER WOULD BE 111111/11/1.
	REM RESULT NOT REQUIRE
	REM ATTEMPT PROPER - LATER ON
	REM -------------------------------------------------------------
	REM RESULT OUTPUT 
	REM 2ND METHOD SHOW CHARACTER POSITION BEGIN LINE
	REM WHICH PARAMETER ANYWAY /o BUTTY THE POSITION WHOLE FILE UNLIKE OTHER ONE
	REM Changes: 0
	REM 1:Changes: 0
	REM -------------------------------------------------------------
	REM FINDSTR /i Changes..[0-9] !FILENAME_ER!
	REM -------------------------------------------------------------
	REM RESULT OUTPUT CONTENT OF FILE THE LINE WITHIN
	REM -------------------------------------------------------------
	REM 164830 Changes: 0, Conflicts: 0, CopyTime: 0, FixState: 0, Errors: 0, All: 6617
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	
	REM FINDSTR /i Changes..[0-9],     !FILENAME_ER!
	
	
	
	REM ECHO -------------------------------------------------------------
	REM ECHO -------------------------------------------------------------
	REM ECHO -------------------------------------------------------------
	REM ECHO -------------------------------------------------------------
	REM FINDSTR /i /c:"CHANGES: [0-9]" !FILENAME_ER!
	REM ECHO -------------------------------------------------------------
	REM ECHO -------------------------------------------------------------
	REM ECHO -------------------------------------------------------------
	REM ECHO -------------------------------------------------------------
	
	REM  ECHO !VAR! | FINDSTR /I /C:"Analysis_Complete">nul
	
	REM SET /a param=%1+0
	REM IF NOT %param%==0 ECHO Valid number

	
	
	REM -------------------------------------------------------------
	REM FIND /i "CHANGES: 0," !FILENAME_ER!>nul
	REM IF !errorlevel!==0 SET CHANGE_HAPPEN=FALSE
	REM -------------------------------------------------------------
	REM THE SORT OF CHANGE LIKE -- NONE -- AND ID -- ERROR OR FIXSTATE
	REM -------------------------------------------------------------
	FIND /i "CHANGES: 0, CONFLICTS: 0, COPYTIME: 0, FIXSTATE: 0, ERRORS: 0" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET ANALYSIS_COMPLETE=TRUE
	IF !errorlevel!==0 SET NONE_TO_DO_______=TRUE
	REM IF !errorlevel!==0 SET SET CHANGE_HAPPEN=NONE

	
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM __ DOUBLE STEP LINE -- NOT BOTHER HERE __ FixState: 0
	REM __ EXAMPLE ONE ONE
	REM __ Changes: 0, Conflicts: 0, CopyTime: 0, FixState: 0, Errors: 0
	REM -------------------------------------------------------------
	REM -- FIND /I ARE CASE SENSITIVE
	REM -------------------------------------------------------------
	REM FIND /i "CHANGES: 0, CONFLICTS: 0, COPYTIME: 0," !FILENAME_ER!>nul
	REM IF NOT !CHANGE_HAPPEN!==NONE (
		REM IF !errorlevel!==0 SET CHANGE_HAPPEN=CHECKER1
	REM )
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM NONE CHANGE -- MAYBE FIXSTATE OR ERROR OR NONE
	REM RULE 1ST TWO BOTH OUT BEFORE
	REM -------------------------------------------------------------
	REM IF ERROR = NONE
	REM -------------------------------------------------------------
	REM GIVER TO FIND _OR_ STATEMENT USE TALLY COUNT INSTEAD
	REM -------------------------------------------------------------
	REM SET /A ACCUMULATOR=0
	REM IF NOT !CHANGE_HAPPEN!==TRUE         SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==CHECKER1     SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF !ACCUMULATOR! NEQ 2 (
		REM FIND /i ", ERRORS: 0" !FILENAME_ER!>nul
		REM IF !errorlevel!==0                 SET CHANGE_HAPPEN=CHECKER2
	REM )
	REM REM -------------------------------------------------------------
	REM REM NONE ERROR HAPPEN  -- MAYBE FIXSTATE OR NOTHING ART ALL
	REM REM -------------------------------------------------------------
	REM SET /A ACCUMULATOR=0
	REM IF NOT !CHANGE_HAPPEN!==TRUE         SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==CHECKER1     SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==CHECKER2     SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF !ACCUMULATOR! NEQ 3 (
		REM FIND /i ", FIXSTATE: 0" !FILENAME_ER!>nul
		REM IF !errorlevel!==0                 SET CHANGE_HAPPEN=CHECKER3
	REM ) 
	REM REM -------------------------------------------------------------
	REM REM OBVIOUS FOUND RESULT DOUBLE CHECKER
	REM REM -------------------------------------------------------------
	REM REM OBVIOUS THE RESULT MAYBE QUICKER WHEN HERE INSTEAD
	REM REM NOT FIND -- SYNC COMPLETE
	REM REM -------------------------------------------------------------
	REM REM FIND /i "SYNC COMPLETE." !FILENAME_ER!>nul
	REM REM IF !errorlevel!==0 SET SYNC_RUNNER_ONE=TRUE
	REM REM -------------------------------------------------------------
	REM REM DEFAULT IS TRUE UNLESS PROVE -- IF !CHANGE_HAPPEN!==TRUE
	REM REM -------------------------------------------------------------
	REM REM EQU - EQUAL
	REM REM NEQ - NOT EQUAL
	REM REM LSS - LESS THAN
	REM REM LEQ - LESS THAN OR EQUAL
	REM REM GTR - GREATER THAN
	REM REM GEQ - GREATER THAN OR EQUAL
	REM REM -------------------------------------------------------------
	REM SET /A ACCUMULATOR=0
	REM IF NOT !CHANGE_HAPPEN!==TRUE         SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==NONE_2222    SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==CHECKER1     SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==CHECKER2     SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF NOT !CHANGE_HAPPEN!==CHECKER3     SET /A ACCUMULATOR=ACCUMULATOR+1
	REM IF !ACCUMULATOR! NEQ 5 (
		REM FIND /i "CHANGES:" !FILENAME_ER!>nul
		REM IF NOT !errorlevel!==0 (
		REM FIND /i ", CONFLICTS:" !FILENAME_ER!>nul
		REM )
		REM IF NOT !errorlevel!==0 (
		REM FIND /i ", COPYTIME:" !FILENAME_ER!>nul
		REM )
		REM IF NOT !errorlevel!==0 (
		REM FIND /i ", FIXSTATE:" !FILENAME_ER!>nul
		REM )
		REM IF NOT !errorlevel!==0 (
		REM FIND /i ", ERRORS:" !FILENAME_ER!>nul
		REM )
		REM IF NOT !errorlevel!==0 (
			REM SET CHANGE_HAPPEN=FALSE
	REM )
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
	REM -------------------------------------------------------------
		
	REM -------------------------------------------------------------
	SET ERROR_GO=FALSE
	REM -------------------------------------------------------------
	
	FIND /i "ANOTHER JOB IS SYNCING IN FOLDER" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET /A ANOTHER_JOB_COUNTER=!ANOTHER_JOB_COUNTER!+1
	IF !errorlevel!==0 SET ANOTHER_JOB=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "UNRESOLVED CONFLITS" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET UNRESOLVED_CONFLICTS=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "ANALYZE HAS FINISHED WITH CONFLICTS" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET UNRESOLVED_CONFLICTS=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "COMPUTER IS OFFLINE OR TURNED OFF" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET COMPUTER_IS_OFFLINE=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "ERROR PARSING COMMAND LINE: JOB" !FILENAME_ER!>nul     & REM -- JOB_NOT_FOUND
	IF !errorlevel!==0 SET JOB_NOT_FOUND=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "THE PROCESS CANNOT ACCESS THE FILE BECAUSE IT IS BEING USED BY ANOTHER PROCESS" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET JOB_IS_USE_BY_ANOTHER_PROCESS=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "THE NETWORK NAME CANNOT BE FOUND" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET NET_PATH_NOT_FIND=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "SYNC FOLDER DOES NOT EXIST" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET SYNC_FOLDER_NOT_EXIST=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "DELETE IT IF IT BECAME CORRUPTED" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET DELETE_IT_IF_IT_BECAME_CORRUPTED=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "THE SPECIFIED NETWORK NAME IS NO LONGER AVAILABLE" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET SPECIFIED_NETWORK_NAME_IS_NOT_FINDAR=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "FILES HAVE CHANGED (EXCLUDING RENAMES), MORE THAN A THRESHOLD OF" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET FILE_HAVE_CHANGE_MORE_THAN_THRESHOLD=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "CANNOT PARSE STATE FILE, DELETE IT" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET NOT_ABLE_PARSE_STATE_FILE_DELETE_IT=TRUE
	IF !errorlevel!==0 SET ERROR_GO=TRUE
	FIND /i "PROGRAM RETURNED CONTROL" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET PROGRAM_RETURNED_CONTROL_ADD_VBCR=TRUE
	IF !errorlevel!==0 ECHO.
	
	FIND /i "VOLUME NOT FOUND" !FILENAME_ER!>nul
	IF !errorlevel!==0 SET VOLUME_NOT_FOUND=TRUE
	if !errorlevel!==0 SET ERROR_GO=TRUE
	REM -- THE MEDIA CARD FOR CAMERA SOMETIME NOT PLUG IN AND THEN 
	REM -- NOT WANT ERROR ABOUT IT ON THERE
	REM ECHO !Sources_02[%%a]! | FIND /i "D DSC __ MC CARD V0 _____" >nul


	if !ERROR_GO!=="TRUE" SET Sync_Runner_FAULT_TOTAL=FALSE
	if !ERROR_GO!=="TRUE" SET Sync_Runner_ONE=FALSE
	
	REM -------------------------------------------------------------
	REM TEMP OFF Wed 23-Sep-2020 09:32:10
	REM if !errorlevel!==0 SET Sync_Runner_FAULT_TOTAL=FALSE
	REM if !errorlevel!==0 SET Sync_Runner_ONE=FALSE
	REM -------------------------------------------------------------
	REM -- NOT JOB WORK NUMBER [ #1 ] AS THAT THE CAMERA MEDIA CARD QUITE OFTEN NOT PLUG IN 
	REM -- NOT COUNT AS ERROR THEN HIDE RESULT
	REM -- OPERATION ARCHIVE WHEN = VOLUME_NOT_FOUND=TRUE
	REM -------------------------------------------------------------
	IF !MODE_RUN!==CAMERA_BACKUP (
		IF "%%a"=="1" SET OPERATION_HIDE_ERROR=TRUE
	)
	
	REM ----------------------------------------------------------------
	REM ----------------------------------------------------------------
	SET ANALYSIS_AND_SYNC_NOT_RUN=FALSE
	SET ANALYSIS_AND_SYNC_NOT_RUN_1=01
	SET ANALYSIS_AND_SYNC_NOT_RUN_2=02
	IF NOT !OPERATION_HIDE_ERROR!==TRUE (
		IF !Analysis_Complete!==FALSE     SET ANALYSIS_AND_SYNC_NOT_RUN_1=FALSE
		IF !Sync_Runner_ONE!==FALSE       SET ANALYSIS_AND_SYNC_NOT_RUN_2=FALSE
	)
	
	IF !ANALYSIS_AND_SYNC_NOT_RUN_1!==!ANALYSIS_AND_SYNC_NOT_RUN_2! SET ANALYSIS_AND_SYNC_NOT_RUN=TRUE
	
	IF !ANALYSIS_AND_SYNC_NOT_RUN!==TRUE                            SET STATUS_84[%%a]=ERROR
	
	IF /I %%a    LSS 10 (SET PADD1=0) ELSE SET PADD1=
	IF /I !LDA!  LSS 10 (SET PADD2=0) ELSE SET PADD2=
	SET STATUS_TT[%%a]=AT OPERATION !PADD1!%%a _of_ !PADD2!!LDA!
	
	IF NOT !ANALYSIS_AND_SYNC_NOT_RUN!==TRUE                        SET STATUS_84[%%a]=GOOD-SYNC

	IF !Sync_Runner_ONE!==FALSE                                     SET /A FAULT_COUNTER=!FAULT_COUNTER!+1
	IF !ANALYSIS_AND_SYNC_NOT_RUN!==TRUE                            SET /A ERROR_COUNT=!ERROR_COUNT!+1
	SET STATUS_88[%%a]=!ERROR_COUNT!

	REM ----------------------------------------------------------------
	REM PROBLEM OF CONFLICT OF THIS FILE
	REM ONLY WAY NOW IS TO EXCLUDE IN GOODSYNC
	REM ----------------------------------------------------------------
	DEL !FILENAME_ER! >nul 2>nul
	REM ----------------------------------------------------------------

	REM ACCUMULATOR
	SET L=
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	IF /I %%a   LSS 10 (SET PADD1=0) ELSE SET PADD1=
	IF /I !LDA! LSS 10 (SET PADD2=0) ELSE SET PADD2=
	SET /A L=L+1 & SET msgbox[!L!,%%a]=!PADD1!%%a OF !PADD2!!LDA! -- COMPLETE
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=!Sources_02[%%a]:"=!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=!GOODSYNC_GSYNC:"=!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=ANALYSIS_COMPLETE             !ANALYSIS_COMPLETE!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=SYNC_RUNNER                   !SYNC_RUNNER_ONE!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=NONE_TO_DO                    !NONE_TO_DO_______!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=CONFLICT                      !UNRESOLVED_CONFLICTS!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=CHANGE_AR                     !CHANGE_HAPPEN!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=ANOTHER_RUNNER                !ANOTHER_JOB!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=COMPUTER_IS_OFFLINE           !COMPUTER_IS_OFFLINE!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=JOB NOT FOUND                 !JOB_NOT_FOUND!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=JOB_IS_USE_BY_ANOTHER_PROCESS !JOB_IS_USE_BY_ANOTHER_PROCESS!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=NET_PATH_NOT_FIND             !NET_PATH_NOT_FIND!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=SYNC_FOLDER_NOT_EXIST         !SYNC_FOLDER_NOT_EXIST!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=SPECIFIED_NETWORK_NOT_FINDAR  !SPECIFIED_NETWORK_NAME_IS_NOT_FINDAR!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=STATE_FILE_CORRUPTED_DELETE   !DELETE_IT_IF_IT_BECAME_CORRUPTED!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=VOLUME_NOT_FOUND              !VOLUME_NOT_FOUND!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=FILE_HAVE_CHANGE_THRESHOLD    !FILE_HAVE_CHANGE_MORE_THAN_THRESHOLD!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=CANNOT PARSE STATE FILE KILL  !NOT_ABLE_PARSE_STATE_FILE_DELETE_IT!
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=RESULT FIND                   !STATUS_84[%%a]!
	REM -------------------------------------------------------------
	IF /I !STATUS_88[%%a]!  LSS 10 (SET PADD1=0) ELSE SET PADD1=
	IF /I %%a               LSS 10 (SET PADD2=0) ELSE SET PADD2=
	IF /I !STATUS_TT[%%a]!  LSS 10 (SET PADD3=0) ELSE SET PADD3=
	REM -------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=RESULT OVERALL ERROR COUNT    !PADD1!!STATUS_88[%%a]! ERROR OF !PADD2!%%a -- !PADD3!!STATUS_TT[%%a]!
	REM -------------------------------------------------------------
	SET /A L=L+1 & SET msgbox[!L!,%%a]=ANOTHER_JOB_COUNTER           !ANOTHER_JOB_COUNTER!
	REM -------------------------------------------------------------
	IF !OPERATION_HIDE_ERROR!==TRUE (
	SET /A L=L+1 & SET msgbox[!L!,%%a]=OPERATION_HIDE_ERROR          !OPERATION_HIDE_ERROR!
	)
	SET /A L=L+1 & SET msgbox[!L!,%%a]=----------------------------------------------------------------

	SET LDM=%%a
	
	REM FOR /L %%parameter IN (start,step,end) DO command  -- REM ---- SHOW JOB ARRAY -- msgbox

	REM ECHO. 
	FOR /L %%f IN (1,1,!L!) DO (
		ECHO !msgbox[%%f,%%a]!
	)
	
	REM IF !L! GTR !LDL! SET LDL=!L!

	
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM TEMP OUT
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM IF 1==2 (
	REM REM ---- PUT IN THE ERROR ARRAY -- msgboxer
	REM IF !Sync_Runner_FAULT_TOTAL!==FALSE (
		REM FOR /L %%f IN (1,1,!LDL!) DO (
			REM SET msgboxer[%%f,%%a]=!msgbox[%%f,%%a]!
			REM REM ECHO XXAAA  %%a FFF  %%f LDL  !LDL!   "msgboxer"  !msgboxer[%%f,%%a]!
		REM )
	REM )
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM TEMP OUT
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	
	
	REM ECHO ERROR__WORKER --------------------------------------------------
	REM -- AFTER HERE NOT WORK GOOD
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM TEMP OUT
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM REM ---- PUT MINIMAL ERROR ARRAY -- msgboxer
	REM IF !Sync_Runner_FAULT_TOTAL!==FALSE (
		REM FOR /L %%v IN (1,1,%%a) DO (
			REM REM ECHO "RRRR " !msgboxer[%%v,%%a]!
			REM SET VAR=!msgboxer[%%v,%%a]!
			REM REM ECHO "AAA "  %%a   "VVV " %%v " 444 VAR " !VAR!    
			REM IF %%v==2                 SET msgboxerB[%%v,%%a]=!VAR!
			REM IF %%v==4                 SET msgboxerB[%%v,%%a]=!VAR!
			REM ECHO !VAR! | FINDSTR /I /C:"Analysis_Complete">nul
			REM If !errorlevel!==0        SET msgboxerB[%%v,%%a]=!VAR!
			REM ECHO !VAR! | FINDSTR /I /C:"Sync_Runner">nul
			REM If !errorlevel!==0        SET msgboxerB[%%v,%%a]=!VAR!
			REM ECHO !VAR! | FINDSTR /I /C:"Another_Running">nul
			REM If !errorlevel!==0        SET START_LINE=TRUE
			REM IF !START_LINE!==TRUE (
				REM ECHO !VAR! | FINDSTR /I /C:"TRUE">nul
				REM If !errorlevel!==0    SET msgboxerB[%%v,%%a]=!VAR!
				REM ECHO !VAR! | FINDSTR /I /C:"RESULT OVERALL ERROR COUNT">nul
				REM If !errorlevel!==0    SET msgboxerB[%%v,%%a]=!VAR!
			REM )
			REM REM SET VAR_2=!msgboxerB[%%v,%%a]!
			REM REM ECHO "LDM "  %%a   "VVV " %%v "11111 VAR_2 " !VAR!    
			REM REM ---------------------------------------------------------
			REM REM -- FIND THE START LINE WHERE ALL TRUE FLAG FOR ERROR BEGINNER
			REM REM -- AFTER COMPOSE EDITOR HAPPEN
			REM REM -- FINDSTR /I /C:"TRUE" -- WITHOUT QUOTE OR NOT 
			REM REM -- POSSIBLE SPACE IN LINE MAKE CHANGE
			REM REM ---------------------------------------------------------
			REM REM OPERATION FIND HAPPEN -- DISPLAY RESULT SAME AS /X MUST BE DEFAULT
			REM REM ---------------------------------------------------------
		REM )
	REM )
	REM )
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM TEMP OUT
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------
	REM ---------------------------------------------------------

	
	
	REM ECHO SHOW MINIMAL ERROR ARRAY ---------------------------------------------
	REM REM ---- SHOW BRIEF ERROR ARRAY -- msgboxer
	REM FOR /L %%f IN (1,1,%%a) DO (
	REM FOR /L %%v IN (1,1,!LDL!) DO (
		REM REM ECHO VVV  %%v   FFF  %%f
		REM REM SET VAR=!msgboxerB[%%v,%%f]! 
		REM REM ECHO !VAR!
		REM REM IF NOT "!VAR!"=="" ECHO !VAR!
	REM )
	REM )


	
	REM TIMEOUT /T 4

	REM -------------------------------------------------------------
	REM ---- IN THE LOOP 
	REM -------------------------------------------------------------

	)



	REM -------------------------------------------------------------
	REM FOR /L %%parameter IN (start,step,end) DO command 
	REM tokens=2,4,6 will cause the second, fourth and sixth items on each line to be processed
	REM tokens=2-6 will cause the second, third, fourth, fifth and sixth items on each line to be processed
	REM tokens=* will cause all items on each line to be processed
	REM tokens=3* will process the third token and the 4th + all subsequent items, this can also be written as tokens=3,*
	REM -------------------------------------------------------------
	
	REM IF !Sync_Runner_FAULT_TOTAL!==FALSE (
		REM ECHO ERROR__WORKER --------------------------------------------------
		REM REM -- LOOP ALL ERROR JOB SO FAR AND DISPLAY THEM -----------
		REM REM ---------------------------------------------------------
		REM FOR /L %%v IN (1,1,!LDR!) DO (
			REM SET START_LINE=FALSE
			REM FOR /L %%f IN (1,1,!LDD!) DO (
				REM SET VAR=!msgboxer[%%f,%%v]!
			REM FOR /L %%f IN (1,1,!LDL!) DO (
				REM SET /A LDG=LDG+1 & SET msgboxer[%%f,!LDR!]=!msgbox[%%f,%%a]!
			REM )
				REM REM ---------------------------------------------------------
				REM REM -- FIND THE START LINE WHERE ALL TRUE FLAG FOR ERROR BEGINNER
				REM REM -- AFTER COMPOSE EDITOR HAPPEN
				REM REM -- FINDSTR /I /C:"TRUE" -- WITHOUT QUOTE OR NOT 
				REM REM -- POSSIBLE SPACE IN LINE MAKE CHANGE
				REM REM ---------------------------------------------------------
				REM REM OPERATION FIND HAPPEN -- DISPLAY RESULT SAME AS /X MUST BE DEFAULT
				REM REM ---------------------------------------------------------
			REM )
		REM )
	REM )
)

	REM ECHO JOB__SET -------------------------------------------------------------

	REM FOR /L %%f IN (1,1,!LDL!) DO (
		REM ECHO !msgboxer[%%f,%%a]:"=!
	REM )



@REM ----------------------------------------------------------------
@REM FALSE FALL FOOLE - STUNT MAN - FALL GUY - SCRIPTING GUY - HEY GUYS
@REM WEEK-DAY - WEAK-DAY
@REM MONTH-DAY
@REM ----------------------------------------------------------------

REM ECHO.
REM ECHO ----------------------------------------------------------------
REM for /L %%a in (1,1,!LDA!) do (
	REM ECHO %%a of !LDA!
	REM ECHO !Sources_02[%%a]:"=!
	REM ECHO !STATUS_4[%%a]:"=!
	REM ECHO !STATUS_5[%%a]:"=!
	REM ECHO !STATUS_6[%%a]:"=!
	REM ECHO !STATUS_7[%%a]:"=!
	REM ECHO !STATUS_8[%%a]:"=!
	REM ECHO !STATUS_9[%%a]:"=!
	REM ECHO !STATUS_10[%%a]:"=!
	REM ECHO !STATUS_11[%%a]:"=!
	REM ECHO !STATUS_12[%%a]:"=!
	REM ECHO !STATUS_13[%%a]:"=!
	REM ECHO ----------------------------------------------------------------
REM )

REM IF NOT "!COMP_1!"=="!COMP_2!" (
	REM IF "!Sync_Runner_FAULT_TOTAL!"=="FALSE" (
		REM ECHO CONFLICT ERROR FOUND OVERALL _ COUNT = !FAULT_COUNTER!  ---- X-X-X-X-X-X-X-X-X
		REM ECHO ----------------------------------------------------------------
		REM REM for /L %%a in (1,1,!X!) do (
			REM REM IF 	!STATUS_84![%%a]=="ERROR" (
				REM REM ECHO !STATUS_1[%%a]:"=!
				REM REM ECHO !STATUS_3[%%a]:"=!
				REM REM ECHO !STATUS_2[%%a]:"=!
				REM REM ECHO !STATUS_84[%%a]:"=!
				REM REM ECHO ----------------------------------------------------------------
			REM REM )
		REM REM )
		REM REM TIMEOUT /T 4
	REM )


	
IF NOT !ERROR_COUNT!==0 (
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO NOT SUCCESSFUL ATTENTION                  ---- X-X-X-X-X-X-X-X-X
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
)

IF !ERROR_COUNT!==0 (
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO END RUNNER                                ---- *****************
	ECHO SYNC COMPLETE SUCCESSFUL                  ---- *****************
	ECHO ----------------------------------------------------------------
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO ----------------------------------------------------------------
	ECHO.
)

IF !MODE_RUN!==GITHUB  GOTO GITHUB_SUB
GOTO NEXT_PART

:GITHUB_SUB
	REM -----------------------------------------------------------------
	REM -- NOT REQUIRE
	REM -- THE LAST JOB OF GITHUB SCRIPT HERE WOULD DO THEM
	REM -----------------------------------------------------------------
	REM -- BUT USEFUL BUT NOT RUN TWO SAME TIME
	REM -- SOMETIME THERE CHANGE BUT NOT GET UPDATE IF CHANGE BEFORE
	REM -----------------------------------------------------------------
	REM -- NOW HAS ABLE TO CHECK IF ALREADY RUNNER
	REM -----------------------------------------------------------------
	REM -----------------------------------------------------------------
	ECHO.

	IF NOT !MODE_RUN!==GITHUB GOTO JUMP_OVER_GITHUB
	START "" "C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB.BAT"
	REM -----------------------------------------------------------------
	REM -- COLOR -- DOS WINDOW BLUE 97 RGB COLOUR
	REM -- FONT -- LUCIDA CONSOLE 14
	REM -- FONT BOLD
	REM -----------------------------------------------------------------
	
	:JUMP_OVER_GITHUB
	REM ECHO.
	REM ECHO ------------------------------------------------------------
	REM ECHO RUN COMMAND 
	REM REM ECHO %~dp0
	REM ECHO ----------------------------------------------------------------
	REM TIMEOUT /T 8
TIMEOUT /T 30
GOTO ENDE

:NEXT_PART

ECHO.
TIMEOUT /T 300
REM ------------- 300 = 5 MINUTE

IF NOT !ERROR_COUNT!==0   PAUSE
:ENDER


@REM ----------------------------------------------------------------
@REM --- ECHO DE-STUPID-POO
@REM --- ECHO 
@REM --- ECHO DE-STUPID-POO
@REM --- DE-STUPID-POO
@REM --- DE-STUPID-POO OR POO
@REM ----------------------------------------------------------------
@REM FALSE FALL FOOLE - STUNT MAN - FALL GUY - SCRIPTING GUY - HEY GUYS
@REM WEEK-DAY - WEAK-DAY
@REM MONTH-DAY
@REM ----------------------------------------------------------------

ECHO.
ECHO ----------------------------------------------------------------

:ENDE
EXIT

@REM ----------------------------------------------------------------
@REM -- NOT WORKING ODD SOD'S -- UNABLE TO CONVERT THE CODEPAGE 
@REM -- USING DOS COMMANDING
@REM ----------------------------------------------------------------
@REM chcp 1200 >nul & cmd /a /c type "%~dp0GOODSYNC_ER_OUTPUT.TXT" >"%~dp0GOODSYNC_ER_OUTPUT_2.TXT"
@REM cmd /a /c type "%~dp0GOODSYNC_ER_OUTPUT.TXT" >"%~dp0GOODSYNC_ER_OUTPUT_2.TXT"
@REM cmd /a /c TYPE "%~dp0GOODSYNC_ER_OUTPUT_2.TXT"

@REM @echo off
@REM >%~dp0GOODSYNC_ER_OUTPUT.TXT (for /F "tokens=1* delims=:" %%g in ('findstr "^" "Sync: Running:"') do echo %%g = "%%h")

REM -----------------------------------------------------------------
REM CREDIT FIND BUT ONLY HELP TO LOCATE IN OWN CODE
REM ----
REM BATCH STRIP %~0 - Google Search
REM https://www.google.com/search?safe=active&ei=YZt7XJTWAdme1fAPo52CmA0&q=BATCH+STRIP+%25%7E0&oq=BATCH+STRIP+%25%7E0&gs_l=psy-ab.3...7068.8831..9110...0.0..0.65.340.6......0....1..gws-wiz.......0i71j0i8i7i30.X6lNLPYEc7I
REM ----
REM ----
REM How do you strip quotes out of an ECHO'ed string in a Windows batch file? - Stack Overflow
REM https://stackoverflow.com/questions/804646/how-do-you-strip-quotes-out-of-an-echoed-string-in-a-windows-batch-file
REM ----
REM -----------------------------------------------------------------

REM USING ARRAYS IN BATCH DOS COMMAND PROMPT LEVEL
REM ----
REM How to loop through array in batch? - Stack Overflow
REM https://stackoverflow.com/questions/18462169/how-to-loop-through-array-in-batch
REM ----

REM ----
REM Batch Script Variables
REM https://www.tutorialspoint.com/batch_script/batch_script_variables.htm
REM ----
REM EXAMPLE
REM @ECHO OFF 
REM SET GLOBALVAR= 5
REM SETLOCAL
REM SET VAR= 13145
REM SET /A VAR= %VAR% + 5
REM ECHO %VAR%
REM ECHO %GLOBALVAR%
REM ENDLOCAL
REM Few key things to note about the above program.

REM The ‘globalvar’ is defined with a global scope and is available throughout the entire script.

REM The ‘var‘ variable is defined in a local scope because it is enclosed between a ‘SETLOCAL’ and ‘ENDLOCAL’ block. Hence, this variable will be destroyed as soon the ‘ENDLOCAL’ statement is executed.

