' -------------------------------------------------------------------
' __ CODE BY MATTHEW LANCASTER
' __ DATE BEGINNER 4 AM TO 4:44 PM 12 HOUR TWO CODE SET SESSION ----
' __ WITH SOME HEAVY WIND 
' __ THROWING BITS FROM ONE PLACE TO ANOTHER 
' __ I AM THE WEAVER __ I AM THE WIND
' __ DATE BEGINNER AND ENDER ----------------------------------------
' -------------------------------------------------------------------
' [ Fri 13:00:00 Pm_29 Dec 2017 ] The UK
' [ Fri 04:44:40 Pm_29 Dec 2017 ] GMT UTC+0 WET
' ------------------------------------
' [ Sat 05:10:00 Am_21 Apr 2018 ] Add WildCard Sub Folder File Finder Proper
' ------------------------------------
' LAST EDITOR
' TOTAL TIMER -- 008 + 009 MOTION
' Wed 18-Mar-2020 00:54:00 -- 2 HOUR 50 MINUTE
' ------------------------------------

' ----
' DeployHappiness | Pinning Programs to the Taskbar with Group Policy 
' https://deployhappiness.com/pinning-programs-to-the-taskbar-with-group-policy/
' ----


' ADDITIONAL 10 URL'S OPEN OF HELPING

' -------------------------------------------------------------------
' [ Thu 15:10:00 Pm_10 May 2018 ] Make Counter of How Many Added Before and After
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 002 Session __
' -------------------------------------------------------------------
' Fri 18-May-2018 03:34:28
' Fri 18-May-2018 05:39:52 __ 2 HOURING IN EARLY HOUR DAWN
'                             I ADD CHECK IF EXIST BEFORE MAKE ICON SPEEDER
'                             FOR EVERY BOOTER _ STILL HAVE TO MANUALLY REMOVE 
'                             ABANDONED LINKS
'                             IT WAS CAUSE PROBLEMS BY HAVING LINKS DOUBLE THEY 
'                             HIDE AS WHITE LABEL SOME FEW TOGETHER
' Fri 18-May-2018 06:24:52 __ 3 HOUR _ DO SOME EXTRA WORK
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 003 Session __
' -------------------------------------------------------------------
' Fri 18-May-2018 11:34:46
' Fri 18-May-2018 12:19:12 __ 1 HOUR- MORE SPEEDER UP WORKS IN AN INSTANT NOW
'                             IF NOTHING TO DO
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 004 Session __
' -------------------------------------------------------------------
' Fri 18-May-2018 22:44:00
' Fri 18-May-2018 22:44:00
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 005 Session __
' -------------------------------------------------------------------
' Sun 07-Oct-2018 02:57:00
' Sun 07-Oct-2018 03:15:00 __ Additional & Modify 
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 006 Session __
' -------------------------------------------------------------------
' Sun 07-Oct-2018 05:40:00
' Sun 07-Oct-2018 05:44:00 __ Back to Write the Time Header-ing 
'                          __ And Programs to Be Installed ASUS-5P
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 007 Session __
' -------------------------------------------------------------------
' -----------------------------------------------------------
' USE EXE -- WHEN PinTo10_v4 -- MSI 8-ASUS-M WHICH GOT UPDATE WINDOW
' NOT WORK ANYMORE
' RECENT UPDATE SOFTWARE FIND BLOGGER MESSENGER COMMENT
' NOT WORK EITHER
' ICON MADDEN SET IN
' -----------------------------------------------------------
' Thu 20-Feb-2020 13:02:02
' Thu 20-Feb-2020 13:33:58 -- 32 MINUTE
' -----------------------------------------------------------
' Thu 20-Feb-2020 18:29:08
' Thu 20-Feb-2020 21:06:22 -- 2 HOUR 37 MINUTE
' Thu 20-Feb-2020 21:06:22 -- 3 HOUR 09 MINUTE
' -----------------------------------------------------------

' -------------------------------------------------------------------
' 008 Session __
' -------------------------------------------------------------------
' PLAN TO AND COMPLETER ALMOST AS READER
' FOR OPERATING SYSTEM WINDOWS 10
' THAT UPDATE DO TO LATEST
' THE CODE NOT WORK PINITEM.EXE
' AND THEN ANOTHER WAY
' IS OPEN EXPLORER WITH / SELECTION TO FILENAME
' AND DIY FROM THERE
' --
' ANOTHER WAY WHEN TIME EXTRA -- CODE IN PLACE ALREADY NOT COMPLETE YET
' IS MAKE SHORTCUT 
' AND LESS OVERHEAD OF EXPLORER LOAD 
' ONLY DRAG FROM DESKTOP
' SEARCH STRING 
' ---- ' PIN ITEM BATCH LOAD EXPLORER NEW LINKER WHEN EXE NOT WORK
' -------------------------------------------------------------------
' Tue 17-Mar-2020 09:43:26
' Tue 17-Mar-2020 11:24:00 -- 1 HOUR 40 MINUTE
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' 009 Session __ PART TWO OF SESSION 088 TWO IN ONE DAY OVER MIDNIGHT
' -------------------------------------------------------------------
' REM OUT WSHShell.Run
' RUN EXPLORER IS HEAVY OVERHEAD FOR EACH SHORTCUT FINDER
' INSTEAD NOW GOT MAKE SHORTCUT DESKTOP THAT BE MORE FINER
' MOVE SHORTCUT TO TASKBAR
' -----------------------------------------------
' Tue 17-Mar-2020 23:43:51
' Wed 18-Mar-2020 00:54:00 -- 1 HOUR 10 MINUTE
' -------------------------------------------------------------------
' -------------------------------------------------------------------
' TOTAL TIMER -- 008 + 009 MOTION
' Wed 18-Mar-2020 00:54:00 -- 2 HOUR 50 MINUTE
' -------------------------------------------------------------------


' -------------------------------------------------------------------
' [ Friday 20:48:00 Pm_08 March 2019 ]
' -------------------------------------------------------------------
' SKYPE IS APP FROM WINDOWS STORE AND NOT ABLE PUT AS LINK 
' ONLY PUT FROM WINDOWS OWN STYLE
' -------------------------------------------------------------------
' FINDER AND NOT WANTER
' -------------------------------------------------------------------
' "C:\Program Files\HandBrake\HandBrake.exe"
' "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe"
' "C:\Program Files (x86)\DVDVideoSoft\Free MP4 Video Converter\FreeMP4VideoConverter.exe"
' "C:\Users\MATT 01\AppData\Local\FlickrUploadrWindows\app-1.0.1.292\Flickr.exe"
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' WORK 10 -- 16-MAY-2026 22:44:26 SAT
' -------------------------------------------------------------------
' -------------------------------------------------------------------
' NEW PATH 2026 
' -------------------------------------------------------------------
' NEW
' C:\SCRIPTER\SCRIPTER CODE -- VB 02 VBSCRIPT
' -------------------------------------------------------------------
' OLD
' C:\SCRIPTER\SCRIPTER CODE -- VB 02 VBSCRIPTCRIPT
' -------------------------------------------------------------------



' CHECK IF ANY WSCRIPT ALREADY RUNNER AND QUIT OTHER ONE IF IS WORKER
' -------------------------------------------------------------------
CALL ROUTINE_DELETE_WSCRIPT_FINDER_RUN



DIM TT_EDITOR_1
DIM TT_EDITOR_2


Const ForReading = 1, ForWriting = 2, ForAppending = 8
Const ShowWindow = 1, DontShowWindow = 0, DontWaitUntilFinished = false, WaitUntilFinished = true

DIM AATRUE

' END RESULT ITEM
DIM LINK_SET_EXIST_TOTAL_VERIFY_2

DIM Q
DIM PinTo10_EXE_PATH
DIM PinTo10_v4_EXE__


Q=CHR(34)

PinTo10_EXE_PATH = "C:\SCRIPTER\SCRIPTER CODE -- VB 02 VBSCRIPT\VBS 12-Pinto10\PinTo10.exe" 
PinTo10_EXE_PATH = "C:\SCRIPTER\SCRIPTER CODE -- VB 02 VBSCRIPT\VBS 12-Pinto10\PinTo10.exe"
PinTo10_v4_EXE__=Q & "C:\SCRIPTER\SCRIPTER CODE -- VB 02 VBSCRIPT\VBS 12-Pinto10\PinTo10_v4.exe" & Q

DIM GETUSERNAME
DIM GETCOMPUTERNAME
DIM COMPUTERNAME
DIM WSHSHELL
SET WSHSHELL = CreateObject("WScript.Shell")
GETUSERNAME = CreateObject("WScript.Network").USERNAME
GETCOMPUTERNAME = CreateObject("WScript.Network").COMPUTERNAME
COMPUTERNAME = CreateObject("WScript.Network").COMPUTERNAME
' ------------------------------------------------------------------
' ANOTHER EXAMPLE
' ------------------------------------------------------------------
' COMPUTERNAME = WSHSHELL.ExpandEnvironmentStrings("%computername%")
' ------------------------------------------------------------------


' IF strComputerName="8-MSI-GP62M-7RD" THEN 
	' PinTo10_EXE_PATH = PinTo10_v4_EXE__
' END IF

'EXAMPLE
'PinTo10.exe /PTFOL:"C:\Windows" /PTFILE:"notepad.exe"

Set args = Wscript.Arguments
For Each arg In args
	XF0 = XF0 + arg
Next

'If Sent-to is Used Sometime Additional Quote Surround are User
' -------------------------------------------------------------
XF0 = UCASE(Replace(XF0,"""",""))

IF INSTR(XF0,"-Q") THEN QUITE_MODE_ENDING=TRUE
IF INSTR(XF0,"/Q") THEN QUITE_MODE_ENDING=TRUE

' QUITE_MODE_ENDING=TRUE

' QUITE_MODE_ENDING=TRUE

DIM XCOUNTER_EXPLORER
DIM LOAD_TO_DESKTOP
DIM LOAD_TO_DESKTOP_BEEN_FLAG

DIM LINK_SET_ALREADY_EXIST_TOTAL
DIM Version_OS
DIM objShell
DIM objFSO
DIM LINK_SET_STRING_1 
DIM APPDATA_FOLDER_FILE_COUNT_VAR_1
DIM ARRAY_1(2000)
DIM ARRAY_2(2000)
DIM ARRAY_4(2000)
DIM ARRAY_5(2000)

Set objShell = Wscript.CreateObject("WScript.Shell")
Set objFSO = CreateObject("Scripting.FileSystemObject")
Dim FSO
Set FSO = CreateObject("Scripting.FileSystemObject")
DIM oFSO
Set oFSO = CreateObject("Scripting.FileSystemObject")

WindowsDir = objShell.ExpandEnvironmentStrings("%windir%")
AppDataLocation=objShell.ExpandEnvironmentStrings("%APPDATA%")
COUNT_I=0

CALL GET_WINDOWS_VERSION
'WINDOWS 7 = 6.1.7601

obj_SOURCE_Folder = AppDataLocation & "\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)

IF INSTR(XF0,"-L") THEN LOAD_WINDOWS_FOLDER=TRUE
IF INSTR(XF0,"/L") THEN LOAD_WINDOWS_FOLDER=TRUE

IF LOAD_WINDOWS_FOLDER=TRUE THEN
	'Dim objShell
	Set objShell = Wscript.CreateObject("WScript.Shell")
	objShell.Run CHR(34)& "EXPLORER.exe" & CHR(34)& " " & CHR(34)& obj_SOURCE_Folder & CHR(34)
	Set objShell = Nothing
	WScript.Quit(0)
END IF


APPDATA_FOLDER_FILE_COUNT_VAR_1=0
Call APPDATA_FOLDER_FILE_COUNT(objSuperFolder, APPDATA_FOLDER_FILE_COUNT_VAR_1)

' WScript.Quit(0)

DIM FILE_SCAN_FIND_2
DIM FILE_SCAN_FIND_4


CALL CREATE_PIN_ITEM_ARRAY


' ------------------------------------
' CHECK FOR DUPLICATES IN ARRAY
' ------------------------------------
DIM R_SET_1
DIM R_SET_2

I_VAR=""
FOR R_SET_1=1 TO UBOUND(ARRAY_1)
	FOR R_SET_2=1 TO UBOUND(ARRAY_1)
		IF ARRAY_1(R_SET_1)<>"" AND ARRAY_1(R_SET_2)<>"" THEN 
			IF UCASE(ARRAY_1(R_SET_1))=UCASE(ARRAY_1(R_SET_2)) AND R_SET_1<>R_SET_2 THEN 
				I_VAR=I_VAR & VBCRLF & ARRAY_1(R_SET_1) & VBCRLF
				
				' ------------------------------
				' DELETE THE OFFENDING DUPLICATE
				' ------------------------------
				ARRAY_1(R_SET_2)=""
				' ------------------------------
				

			END IF
		END IF
	NEXT
NEXT
IF QUITE_MODE_ENDING=FALSE AND I_VAR<>"" THEN 
	MSGBOX "DUPLICATE ENTRY IN VBS 12-PINITEM BATCH.VBS" & VBCRLF & I_VAR,vbMsgBoxSetForeground,Wscript.ScriptName
END IF

' ------------------------------------
' CHECK FOR DUPLICATES IN ARRAY 5
' ------------------------------------
I_VAR=""
FOR R_SET_1=1 TO UBOUND(ARRAY_5)
	FOR R_SET_2=1 TO UBOUND(ARRAY_5)
		IF ARRAY_5(R_SET_1)<>"" AND ARRAY_5(R_SET_2)<>"" THEN 
			IF UCASE(ARRAY_5(R_SET_1))=UCASE(ARRAY_5(R_SET_2)) AND R_SET_1<>R_SET_2 THEN 
				I_VAR=I_VAR & VBCRLF & ARRAY_5(R_SET_1) & VBCRLF

				' ------------------------------
				' DELETE THE OFFENDING DUPLICATE
				' ------------------------------
				ARRAY_5(R_SET_2)=""
				' ------------------------------
				

			END IF
		END IF
	NEXT
NEXT
IF QUITE_MODE_ENDING=FALSE AND I_VAR<>"" THEN 
	MSGBOX "DUPLICATE ENTRY IN VBS 12-PINITEM BATCH.VBS" & VBCRLF & I_VAR,vbMsgBoxSetForeground,Wscript.ScriptName
END IF

' ------------------------------------
' CHECK FOR DUPLICATES MASSIVE SPEEDER
' ------------------------------------
obj_SOURCE_Folder = AppDataLocation & "\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
CALL GET_LINK_SET_STRING_1(objSuperFolder)

ITEM_TO_PUT_TASKBAR=0

FOR R_SET=1 TO UBOUND(ARRAY_1)
	IF ARRAY_1(R_SET)<>"" THEN 
		If objFSO.FileExists(ARRAY_1(R_SET)) = TRUE Then
			FILE_SCAN_FIND_1=UCASE(MID(ARRAY_1(R_SET),INSTRREV(ARRAY_1(R_SET),"\")+1))
			FILE_SCAN_FIND_1=UCASE(MID(FILE_SCAN_FIND_1,1,INSTRREV(FILE_SCAN_FIND_1,".")-1))
			' MSGBOX FILE_SCAN_FIND_1,vbMsgBoxSetForeground,Wscript.ScriptName
			
			IF INSTR(LINK_SET_STRING_1,FILE_SCAN_FIND_1)>0 THEN
				ARRAY_2(R_SET)=TRUE
				LINK_SET_ALREADY_EXIST_TOTAL=LINK_SET_ALREADY_EXIST_TOTAL+1
			ELSE
				ITEM_TO_PUT_TASKBAR=ITEM_TO_PUT_TASKBAR+1
				' MSGBOX FILE_SCAN_FIND_1,vbMsgBoxSetForeground,Wscript.ScriptName
			END IF
		END IF
	END IF
NEXT



' ------------------------------------------------------
' CHECK FOR FILEEXISTS THAT COULD BE 64 BIT & VICE VERSA
' ------------------------------------------------------
' DIM R_SET_1
FOR R_SET_1=1 TO UBOUND(ARRAY_1)
	HOLDER_VAR=ARRAY_1(R_SET_1)
	SET_VAR_FLAG_1=FALSE
	SET_VAR_FLAG_2=FALSE
	If objFSO.FileExists(ARRAY_1(R_SET_1)) = FALSE Then
		IF INSTR(UCASE(ARRAY_1(R_SET_1)),"\PROGRAM FILES (X86)\")>0 THEN 
			ARRAY_1(R_SET_1)=REPLACE(UCASE(ARRAY_1(R_SET_1)), "\PROGRAM FILES (X86)\","\PROGRAM FILES\")
			SET_VAR_FLAG_1=TRUE
		END IF
	END IF
	
	' TRY BOTH
	' HERE WILL PUT BACK AS WAS IF NOT FOUND BETWEEN (86X) AND 64 BIT
	' OR AND WILL INVERT FOR VICE VERSA
	If objFSO.FileExists(ARRAY_1(R_SET_1)) = FALSE Then
		IF INSTR(UCASE(ARRAY_1(R_SET_1)),"\PROGRAM FILES\")>0 THEN 
			ARRAY_1(R_SET_1)=REPLACE(UCASE(ARRAY_1(R_SET_1)), "\PROGRAM FILES\","\PROGRAM FILES (X86)\")
			SET_VAR_FLAG_2=TRUE
		END IF
	END IF
	
	' PUT THE CASE CONVERSION BACK RESTORE
	IF UCASE(HOLDER_VAR) = UCASE(ARRAY_1(R_SET_1)) THEN
		ARRAY_1(R_SET_1)=HOLDER_VAR
	END IF
	
	' IF BOTH CONVERSION HAPPEN AND NOTHING CHANGED ON FILEEXISTS THEN RESTORE CASE CONVERSION
	If objFSO.FileExists(ARRAY_1(R_SET_1)) = FALSE Then
		IF SET_VAR_FLAG_1=TRUE OR SET_VAR_FLAG_2=TRUE THEN 
			ARRAY_1(R_SET_1)=HOLDER_VAR
		END IF
	END IF
	
NEXT
' ------------------------------------

' If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	' ARRAY_1(I)="C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
' END IF

DIM EXTRA_ITEM_ADD_TO_TASKBAR

'WScript.Quit(0)

FOR R_SET=1 TO UBOUND(ARRAY_1)
	IF ARRAY_1(R_SET)<>"" THEN 
		If objFSO.FileExists(ARRAY_1(R_SET)) = TRUE Then
			COUNT_I=COUNT_I+1
		ELSE
			IF QUITE_MODE_ENDING=FALSE THEN 
				WScript.Echo "01 OF 02 -- ITEM DON'T EXIST" & VBCRLF & VBCRLF & ARRAY_1(R_SET)
			END IF
		END IF
	END IF
NEXT


FOR R_SET=1 TO UBOUND(ARRAY_5)
	IF ARRAY_5(R_SET)<>"" THEN 
		If objFSO.FileExists(ARRAY_5(R_SET)) = TRUE Then
			COUNT_I5=COUNT_I5+1
		ELSE
			IF QUITE_MODE_ENDING=FALSE THEN 
				WScript.Echo "02 OF 02 -- ITEM DON'T EXIST" & VBCRLF & VBCRLF & ARRAY_5(R_SET)
			END IF
		END IF
	END IF
NEXT


obj_SOURCE_Folder = AppDataLocation & "\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
APPDATA_FOLDER_FILE_COUNT_VAR_2=0
Call APPDATA_FOLDER_FILE_COUNT(objSuperFolder, APPDATA_FOLDER_FILE_COUNT_VAR_2)


SET_TO_DO_COUNT=0
FOR R_SET=0 TO UBOUND(ARRAY_1)
' MSGBOX ARRAY_1(R_SET),vbMsgBoxSetForeground,Wscript.ScriptName
	IF ARRAY_4(R_SET)=TRUE THEN 
		SET_TO_DO_COUNT=SET_TO_DO_COUNT+1
	END IF
NEXT 

SET WSHShell = WScript.CreateObject("WScript.Shell")
Set objShell = WScript.CreateObject("WScript.Shell")
strDesktop = objShell.SpecialFolders("Desktop")
Set FOLDER = FSO.GETFOLDER(strDesktop)

IF ARRAY_1(R_SET2)<>"" THEN
	ITEM_VAR_PATH=MID(ARRAY_1(R_SET2),1,INSTRREV(ARRAY_1(R_SET2),"\")-1)
	ITEM_VAR_FILE=MID(ARRAY_1(R_SET2),INSTRREV(ARRAY_1(R_SET2),"\")+1)
	ITEM_VAR_FILE_NOT_EXT=MID(ITEM_VAR_FILE,1,INSTRREV(ITEM_VAR_FILE,".")-1)
END IF

' LINKS THAT ALREADY EXIST ON DESKTOP
' -----------------------------------
IF AATRUE="" THEN 
	AATRUE=LINK_ALREADY_EXIST_DOUBLE_VERIFY_2(FOLDER)
END IF

AATRUE="LINKS THAT ALREADY EXIST ON DESKTOP -- COPIER TO CLIPBOARD" & VBCRLF & "ALL THE DESKTOP ICONS" & VBCRLF & VBCRLF & AATRUE

MSGBOX AATRUE,vbMsgBoxSetForeground,Wscript.ScriptName
'
' Get clipboard text
' Set objHTML = CreateObject("htmlfile")
' text = objHTML.ParentWindow.ClipboardData.GetData("text")

' EDIT: I use this snippet to put text back on the clipboard, but it needs third party software; a standalone executable 'clip.exe' which can be found on Windows 2003 Server or just on the internet:

' Put it back to the clipboard
Set WshShell = CreateObject("WScript.Shell")
Set oExec = WshShell.Exec("clip")

Set oIn = oExec.stdIn

oIn.WriteLine AATRUE
oIn.Close










COUNT_ICON_PLACE_TASKBAR=0			
LOAD_TO_TASKBAR_EXPLORER=0

I_VAR=""
I_VAR=I_VAR + "--------------------------------------------------------"+VBCRLF
I_VAR=I_VAR + "DO YOU LIKE ME TO PIN ITEM TO TASKBAR LOAD EXPLORER SHORTCUT"+VBCRLF
I_VAR=I_VAR + "--------------------------------------------------------"+VBCRLF
I_VAR=I_VAR + "YesNoCancel"+VBCRLF
I_VAR=I_VAR + "--------------------------------------------------------"+VBCRLF

LOAD_TO_TASKBAR_EXPLORER=VBNO
IF Version_OS<>11 THEN
	lRet = MsgBox(I_VAR, vbYesNoCancel + vbMsgBoxSetForeground , Wscript.ScriptName)
	LOAD_TO_TASKBAR_EXPLORER=lRet
END IF

XCOUNTER_EXPLORER=0
IF LOAD_TO_TASKBAR_EXPLORER=VBYES THEN
	SET WSHShell = WScript.CreateObject("WScript.Shell")
	Set objShell = WScript.CreateObject("WScript.Shell")

	obj_SOURCE_Folder = AppDataLocation & "\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
	Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
	APPDATA_FOLDER_FILE_COUNT_VAR_2=0
	Call APPDATA_FOLDER_FILE_COUNT(objSuperFolder, APPDATA_FOLDER_FILE_COUNT_VAR_2)
	
	' MSGBOX APPDATA_FOLDER_FILE_COUNT_VAR_2,vbMsgBoxSetForeground,Wscript.ScriptName

	' ---- RESULT FROM HERE GET PUT THERE --  LINK_SET_STRING_1 =
	' ---------------------------------------------------------------------
	CALL GET_LINK_SET_STRING_1(objSuperFolder)
	FOR R_SET=1 TO UBOUND(ARRAY_5)
		IF ARRAY_5(R_SET)<>"" THEN 
			If objFSO.FileExists(ARRAY_5(R_SET)) = TRUE Then
				FILE_SCAN_FIND_1=UCASE(MID(ARRAY_5(R_SET),INSTR(ARRAY_5(R_SET),"\")+1))
				IF INSTR(LINK_SET_STRING_1 ,FILE_SCAN_FIND_1)=0 THEN 
					' -----------------------------------------------
					' Tue 17-Mar-2020 09:42:36
					' Tue 17-Mar-2020 10:28:21 -- 45 MINUTE
					' -----------------------------------------------
					' VBScript - Creating a Shortcut
					' https://www.vbsedit.com/html/e6ac108b-15f6-4a54-891f-589e8b687ace.asp
					' -----------------------------------------------
					ITEM_VAR_PATH=""
					ITEM_VAR_FILE=""
					ITEM_VAR_FILE_NOT_EXT=""
					ITEM_VAR_PATH=MID(ARRAY_5(R_SET),1,INSTRREV(ARRAY_5(R_SET),"\")-1)
					ITEM_VAR_FILE=MID(ARRAY_5(R_SET),INSTRREV(ARRAY_5(R_SET),"\")+1)
					
					ITEM_VAR_FILE_NOT_EXT=MID(ITEM_VAR_FILE,1,INSTRREV(ITEM_VAR_FILE,".")-1)
					' THERE MIGHT BE TWO PATH *.EXE.LNK -- REMOVE END ONE ONCE OKAY BUT NOT TWICE
					' DO HERE INSTEAD
					ITEM_VAR_FILE_NOT_EXT=REPLACE(UCASE(ITEM_VAR_FILE_NOT_EXT),".LNK","")
					ITEM_VAR_FILE_NOT_EXT=REPLACE(UCASE(ITEM_VAR_FILE_NOT_EXT),".EXE","")
					' MSGBOX "2222     " & ITEM_VAR_PATH,vbMsgBoxSetForeground,Wscript.ScriptName

					strTASKBAR_EXPLORER = AppDataLocation & "\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
					Set FOLDER = objFSO.GetFolder(strTASKBAR_EXPLORER)

					' GATHER THE DATA INTO STRING -- AATRUEZ
					' ---------------------
					AATRUEZ=LINK_ALREADY_EXIST_DOUBLE_VERIFY_2(FOLDER)

					' -----------------------------------------------
					' IF ALL LOWER CASE PUT ALL UPPER CASE
					' IF SEMI LOW AND HIGH CASE ONLY MAKE SURE FIRST LETTER IS HIGH 
					' AND LEAVE AS SAME
					IF ITEM_VAR_FILE_NOT_EXT=LCASE(ITEM_VAR_FILE_NOT_EXT) THEN 
						ITEM_VAR_FILE_NOT_EXT=UCASE(ITEM_VAR_FILE_NOT_EXT)
					ELSE
						ITEM_VAR_FILE_NOT_EXT=UCASE(MID(ITEM_VAR_FILE_NOT_EXT,1,1))+MID(ITEM_VAR_FILE_NOT_EXT,2)
					END IF
					
					
					' MSGBOX  ITEM_VAR_FILE_NOT_EXT ' ---- DISPLAY PROGRAM NAME QUICK POP,vbMsgBoxSetForeground,Wscript.ScriptName
					
					' IF INSTR(UCASE(AATRUEZ),UCASE("Visual Basic 6.0"))>0 THEN MSGBOX "HERE",vbMsgBoxSetForeground,Wscript.ScriptName
					
					IF ITEM_VAR_PATH<>"" THEN 
						' ----
						' Shortcut - VBScript - SS64.com 
						' https://ss64.com/vb/shortcut.html
						' ----
						IF INSTR(UCASE(AATRUEZ),UCASE(ITEM_VAR_FILE_NOT_EXT))=0 THEN 
							Set lnk = objShell.CreateShortcut(strTASKBAR_EXPLORER & "\" & ITEM_VAR_FILE_NOT_EXT & ".lnk")
							' MSGBOX ITEM_VAR_FILE_NOT_EXT &VBCRLF & INSTR(UCASE(AATRUEZ),UCASE(ITEM_VAR_FILE_NOT_EXT)),vbMsgBoxSetForeground,Wscript.ScriptName
							
							COUNT_ICON_PLACE_TASKBAR=COUNT_ICON_PLACE_TASKBAR+1

							IF XCOUNTER_EXPLORER<10 THEN 
							
								' REPEAT HERE AND HAS TO BE SET NEAR COMMAND
								SET WSHShell = WScript.CreateObject("WScript.Shell")
								
								WSHShell.Run "C:\Windows\explorer.exe /select, """+ARRAY_5(R_SET)+"""" , ShowWindow, DontWaitUntilFinished
								
								' ONLY LOAD 10
								' -----------------------------------
								XCOUNTER_EXPLORER=XCOUNTER_EXPLORER+1
								' MSGBOX ITEM_VAR_FILE_NOT_EXT,vbMsgBoxSetForeground,Wscript.ScriptName
							END IF
						END IF
					END IF 
				END IF 
			END IF 
		END IF
	NEXT
END IF
		
						
IF COUNT_ICON_PLACE_TASKBAR>0 THEN 
	MSGBOX COUNT_ICON_PLACE_TASKBAR & " * ITEMS PLACE-ER TASKBAR EXPLORER -- ONLY 1ST 10 LOADED",vbMsgBoxSetForeground,Wscript.ScriptName 
ELSE
	IF LOAD_TO_TASKBAR_EXPLORER=VBYES THEN 
		MSGBOX "NOTHING REQUIRE DONE FOR TASKBAR EXPLORER LOADER",vbMsgBoxSetForeground,Wscript.ScriptName 
	END IF 
END IF





































COUNT_ICON_PLACE_DESKTOP=0			
LOAD_TO_DESKTOP=0

I_VAR=""
I_VAR=I_VAR + "--------------------------------------------------------"+VBCRLF
I_VAR=I_VAR + "DO YOU LIKE ME TO PIN ITEM TO DESKTOP SHORTCUT"+VBCRLF
I_VAR=I_VAR + "--------------------------------------------------------"+VBCRLF
I_VAR=I_VAR + "YesNoCancel"+VBCRLF
I_VAR=I_VAR + "--------------------------------------------------------"+VBCRLF

lRet = MsgBox(I_VAR, vbYesNoCancel  + vbMsgBoxSetForeground , Wscript.ScriptName)
LOAD_TO_DESKTOP=lRet

IF LOAD_TO_DESKTOP=VBYES THEN
	SET WSHShell = WScript.CreateObject("WScript.Shell")
	Set objShell = WScript.CreateObject("WScript.Shell")
	obj_SOURCE_Folder = objShell.SpecialFolders("Desktop")
	Set objSuperFolder  = FSO.GETFOLDER(obj_SOURCE_Folder)
	' ---- RESULT FROM HERE GET PUT THERE --  LINK_SET_STRING_1 =
	' ---------------------------------------------------------------------
	CALL GET_LINK_SET_STRING_1(objSuperFolder)
	FOR R_SET=1 TO UBOUND(ARRAY_1)
		IF ARRAY_1(R_SET)<>"" THEN 
			If objFSO.FileExists(ARRAY_1(R_SET)) = TRUE Then
				FILE_SCAN_FIND_1=UCASE(MID(ARRAY_1(R_SET),INSTR(ARRAY_1(R_SET),"\")+1))
				IF INSTR(LINK_SET_STRING_1 ,FILE_SCAN_FIND_1)=0 THEN 
					' -----------------------------------------------
					' Tue 17-Mar-2020 09:42:36
					' Tue 17-Mar-2020 10:28:21 -- 45 MINUTE
					' -----------------------------------------------
					' VBScript - Creating a Shortcut
					' https://www.vbsedit.com/html/e6ac108b-15f6-4a54-891f-589e8b687ace.asp
					' -----------------------------------------------
					ITEM_VAR_PATH=""
					ITEM_VAR_FILE=""
					ITEM_VAR_FILE_NOT_EXT=""
					ITEM_VAR_PATH=MID(ARRAY_1(R_SET),1,INSTRREV(ARRAY_1(R_SET),"\")-1)
					ITEM_VAR_FILE=MID(ARRAY_1(R_SET),INSTRREV(ARRAY_1(R_SET),"\")+1)
					ITEM_VAR_FILE_NOT_EXT=MID(ITEM_VAR_FILE,1,INSTRREV(ITEM_VAR_FILE,".")-1)
					' THERE MIGHT BE TWO PATH *.EXE.LNK -- REMOVE END ONE ONCE OKAY BUT NOT TWICE
					' DO HERE INSTEAD
					ITEM_VAR_FILE_NOT_EXT=REPLACE(UCASE(ITEM_VAR_FILE_NOT_EXT),".LNK","")
					ITEM_VAR_FILE_NOT_EXT=REPLACE(UCASE(ITEM_VAR_FILE_NOT_EXT),".EXE","")
					' MSGBOX "2222     " & ITEM_VAR_PATH,vbMsgBoxSetForeground,Wscript.ScriptName

					strDesktop = objShell.SpecialFolders("Desktop")
					Set FOLDER = FSO.GETFOLDER(strDesktop)

					' GATHER THE DATA INTO STRING -- AATRUEZ
					' ---------------------
					AATRUEZ=LINK_ALREADY_EXIST_DOUBLE_VERIFY_2(FOLDER)

					' -----------------------------------------------
					' IF ALL LOWER CASE PUT ALL UPPER CASE
					' IF SEMI LOW AND HIGH CASE ONLY MAKE SURE FIRST LETTER IS HIGH 
					' AND LEAVE AS SAME
					IF ITEM_VAR_FILE_NOT_EXT=LCASE(ITEM_VAR_FILE_NOT_EXT) THEN 
						ITEM_VAR_FILE_NOT_EXT=UCASE(ITEM_VAR_FILE_NOT_EXT)
					ELSE
						ITEM_VAR_FILE_NOT_EXT=UCASE(MID(ITEM_VAR_FILE_NOT_EXT,1,1))+MID(ITEM_VAR_FILE_NOT_EXT,2)
					END IF
					
					
					' MSGBOX  ITEM_VAR_FILE_NOT_EXT ' ---- DISPLAY PROGRAM NAME QUICK POP,vbMsgBoxSetForeground,Wscript.ScriptName
					
					' IF INSTR(UCASE(AATRUEZ),UCASE("Visual Basic 6.0"))>0 THEN MSGBOX "HERE",vbMsgBoxSetForeground,Wscript.ScriptName
					
					IF ITEM_VAR_PATH<>"" THEN 
						' ----
						' Shortcut - VBScript - SS64.com 
						' https://ss64.com/vb/shortcut.html
						' ----
						IF INSTR(UCASE(AATRUEZ),UCASE(ITEM_VAR_FILE_NOT_EXT))=0 THEN 
							Set lnk = objShell.CreateShortcut(strDesktop & "\" & ITEM_VAR_FILE_NOT_EXT & ".lnk")
							' MSGBOX ITEM_VAR_FILE_NOT_EXT &VBCRLF & INSTR(UCASE(AATRUEZ),UCASE(ITEM_VAR_FILE_NOT_EXT)),vbMsgBoxSetForeground,Wscript.ScriptName
							
							COUNT_ICON_PLACE_DESKTOP=COUNT_ICON_PLACE_DESKTOP+1

							lnk.TargetPath = ARRAY_1(R_SET)
							lnk.Arguments = ""
							
							lnk.Description = UCASE(ITEM_VAR_FILE_NOT_EXT)  ' NOT WANT BIGGER UCASE GONE & BACK -- GOOGLE AI SAY THIS ONE AI REPORT THIS ONE IS MANDATORY
							
							' lnk.HotKey = "ALT+CTRL+F"
							' lnk.IconLocation = ARRAY_1(R_SET) & ", 2"     ' 2 OR 1 ---- IF REAL ICON NOT EXE
							' lnk.WindowStyle = "1"
							lnk.WorkingDirectory = ITEM_VAR_PATH
							lnk.Save
							Set lnk = Nothing ' -- Clean up 
							' MSGBOX "INSTALL THIS ICON" & VBCRLF & ITEM_VAR_FILE_NOT_EXT,vbMsgBoxSetForeground,Wscript.ScriptName 
						END IF
					END IF 
				END IF 
			END IF 
		END IF
	NEXT
END IF
		
						
IF COUNT_ICON_PLACE_DESKTOP>0 THEN 
	MSGBOX COUNT_ICON_PLACE_DESKTOP & " * ITEMS PLACED DESKTOP",vbMsgBoxSetForeground,Wscript.ScriptName 
ELSE
	IF LOAD_TO_DESKTOP=VBYES THEN
		MSGBOX "NOTHING PLACER DESKTOP",vbMsgBoxSetForeground,Wscript.ScriptName 
	END IF 
END IF 

MSGBOX "THE END",vbMsgBoxSetForeground,Wscript.ScriptName 

WScript.Quit(0)




' -------------------------------------------------------------------
'END OF
' -------------------------------------------------------------------
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' STARTING
' -------------------------------------------------------------------
' -------------------------------------------------------------------
SUB CREATE_PIN_ITEM_ARRAY
' -------------------------------------------------------------------
I=0

' -------------------------------------------------------------------

I=I+1:ARRAY_1(I)="C:\Windows\System32\cmd.exe"
' I=I+1:ARRAY_1(I)="C:\Windows\explorer.exe"

I=I+1:ARRAY_1(I)="C:\Program Files\Google\Chrome\Application\chrome.exe"

If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	' WINDOWS 10 IS USE 32 BIT CHROME
	' WINDOWS 11 IS USE 64 BIT CHROME
	ARRAY_1(I)="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
END IF


I=I+1:ARRAY_1(I)="C:\Program Files\Mozilla Firefox\firefox.exe"
If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	ARRAY_1(I)="C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
END IF

IF Version_OS=10 THEN
	' I=I+1:ARRAY_1(I)="C:\Program Files\Internet Explorer\iexplore.exe"
END IF

obj_SOURCE_Folder = "C:\Users\" & GETUSERNAME & "\AppData\Local\FlickrUploadrWindows"
SET_GO=TRUE
If objFSO.FOLDERExists(obj_SOURCE_Folder) = FALSE Then SET_GO=FALSE
IF SET_GO=TRUE THEN 
	FILE_SCAN_FIND_2=""
	Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
	Call ShowSubfolders(objSuperFolder, "Flickr.exe")
	IF FILE_SCAN_FIND_2<>"" THEN 
		'I=I+1:ARRAY_1(I)=FILE_SCAN_FIND_2
	ELSE
		'I=I+1:ARRAY_1(I)=obj_SOURCE_Folder & "\Flickr.exe"
	END IF
END IF


' ---------------------------------------------------------------------
' NEW SUPER COOL ROUTINE TO INSTANT FIND NORTON UISTUB.EXE
' THE MAIN ENGINE AND ALLOW SHORTCUT
' THEY NORTON FREQUENTLY CHANGE THE NAME OF FOLDER IN PROGRAM FILES
' AND MAY BE LOCATED IN PROGRAM FILES OR PROGRAM FILES (X86)
' AFTER THEY DISCARD AND OLD VERSION THEY NEVER LEAVE UISTUB.EXE BEHIND
' MY CODE SEARCH PROGRAM FILES AND (X86) LIKE NORMAL ONE DO
' BUT IT ONLY SEARCH FOR FIRST PART OF NAME AFTER LIKE EXAMPLE 
' "C:\PROGRAM FILES\NORTON" AND THAT IS ALL AS NORTON ALWAYS START 
' WITH NORTON UP UNTIL NOW
' IS A NEW HIGH SPEED WAY TO SEARCH FOR BETTER CODER
' ---------------------------------------------------------------------
' WRITE CODE TIME
' Sat 09-Mar-2019 23:39:39
' Sat 09-Mar-2019 01:22:00
' ---------------------------------------------------------------------

' ---------------------------------------------------------------------
' DECLARE THESE TWO
' ---------------------------------------------------------------------
' DIM FILE_SCAN_FIND_2
' DIM FILE_SCAN_FIND_4
' ---------------------------------------------------------------------
FILE_SCAN_FIND_4=""
Call ShowSubfolders_FIND_NORTON_UISTUB_EXE

FILE_SCAN_FIND_4="C:\Program Files\Norton\Suite\NortonUI.exe"
If objFSO.FileExists(FILE_SCAN_FIND_4) = TRUE Then
	I=I+1:ARRAY_1(I)=FILE_SCAN_FIND_4
	ELSE
	FILE_SCAN_FIND_4=""
END IF

FILE_SCAN_FIND_4=""
Call ShowSubfolders_FIND_NORTON_UISTUB_EXE

IF FILE_SCAN_FIND_4="" THEN 
	Call ShowSubfolders_FIND_NORTON_UISTUB_EXE
	IF FILE_SCAN_FIND_4<>"" THEN I=I+1:ARRAY_1(I)=FILE_SCAN_FIND_4
ELSE
	' WHEN CANNOT FIND ALLOW FOR ALERT ANYWAY
	I=I+1:ARRAY_1(I)="C:\Program Files\Norton Security\Engine\...\uiStub.exe"
END IF


' obj_SOURCE_Folder = "C:\Users\" & GETUSERNAME & "\AppData\Local\GrammarlyForWindows"
' SET_GO=TRUE
' If objFSO.FOLDERExists(obj_SOURCE_Folder) = FALSE Then SET_GO=FALSE
' IF SET_GO=TRUE THEN 
	' FILE_SCAN_FIND_2=""
	' Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
	' Call ShowSubfolders (objSuperFolder,"GrammarlyForWindows.exe")
	' IF FILE_SCAN_FIND_2<>"" THEN 
		' I=I+1:ARRAY_1(I)=FILE_SCAN_FIND_2
	' ELSE
		' I=I+1:ARRAY_1(I)=obj_SOURCE_Folder & "\GrammarlyForWindows.exe"
	' END IF
' END IF


IF Version_OS=6 THEN
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\UWT2.2 _ WIN 7\Ultimate Windows Tweaker.exe"
END IF 


IF Version_OS=10 THEN
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\UWT4 ___ WIN 10\Ultimate Windows Tweaker 4.1.1.exe"
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\UWT4.3 ___ WIN 10\Ultimate Windows Tweaker 4.3\Ultimate Windows Tweaker 4.3.exe"
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\UWT4.4.1 ___ WIN 10\Ultimate Windows Tweaker 4.4.1\Ultimate Windows Tweaker 4.4.1.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nokia\Nokia Suite\NokiaSuite.exe"
	I=I+1:ARRAY_1(I)="C:\Windows\system32\mspaint.exe"
	I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\x64\specialfoldersview.exe"
END IF 
IF Version_OS=11 THEN
' 	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nokia\Nokia Suite\NokiaSuite.exe"
	I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\x64\specialfoldersview.exe"
END IF

' 1-ASUS-X5DIJ
' 2-ASUS-EEE
' 3-LINDA-PC
' 4-ASUS-GL522VW
' 5-ASUS-P2520LA
' 7-ASUS-GL522VW
' 8-MSI-GP62M-7RD

' IF GETCOMPUTERNAME="1-ASUS-X5DIJ" then 
' IF GETCOMPUTERNAME="2-ASUS-EEE" then 
' IF GETCOMPUTERNAME="3-LINDA-PC" then 
' IF GETCOMPUTERNAME="4-ASUS-GL522VW" then 
' IF GETCOMPUTERNAME="5-ASUS-P2520LA" then 
' IF GETCOMPUTERNAME="7-ASUS-GL522VW" then 


IF GETCOMPUTERNAME="8-MSI-GP62M-7RD" then 
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\NetSetMan\netsetman.exe"

END IF 

IF GETCOMPUTERNAME="4-ASUS-GL522VW" then 
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\DFX\dfx.exe"

END IF 

IF GETCOMPUTERNAME="7-ASUS-GL522VW" then 
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\DFX\dfx.exe"

END IF 
IF Version_OS=11 OR Version_OS=10 THEN
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Freemake\Freemake Video Converter\FreemakeVC.exe"
END IF

'I=I+1:ARRAY_1(I)="C:\Program Files\Mythicsoft\Agent Ransack\AgentRansack.exe"
'If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
'	ARRAY_1(I)="C:\Program Files (x86)\Mythicsoft\Agent Ransack\AgentRansack.exe"
'END IF



I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\bluetoothlogview.exe"
I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\bluetoothview.exe"


IF GETCOMPUTERNAME="7-ASUS-GL522VW" then 
	' I=I+1:ARRAY_1(I)="C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR--VB\BAT 59-RUN GOODSYNC SET SCRIPTOR.exe" 
	
	' C:\SCRIPTOR GITHUB\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR--VB\BAT 59-RUN GOODSYNC SET SCRIPTOR.exe
	' C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 59-RUN GOODSYNC SET SCRIPTOR--VB\BAT 59-RUN GOODSYNC SET SCRIPTOR.exe
	' SUPPOSED TO ADD HERE TO END --  GOODSYNC_MODE  TASKBAR_TRAY_ICON
END IF 


I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\Run_AS\Matt_RunAS_v2017.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\Run_AS 2011-06-11 VER 1.0.164\Matt_RunAS_v1.0.164.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\Run_AS 2012-09-25 VER 1.0.192 EXE ONLY\Matt_RunAS_V1.0.192.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Clip_Type\Clip_Type.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Shell Execute Loader\Shell Execute Loader.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Shell Explorer Loader\Shell Explorer Loader.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Shell KeyBoard Loader\shell keyboard loader.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Send_To\Send To Multi Menu\#0 Send To Multi Menu.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Send_To\Send To Text List of Files & Sub Folders IRFAN\#0 Send To Text List of Files and Sub Folders IRFAN.EXE"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\CPU % OF A PROGRAM\CPU % INDIVIDUAL PROCESS.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\CLIPBOARD_VIEWER\ClipBoard Viewer.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\VB_KEEP_RUNNER\VB_KEEP_RUNNER.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\CLIPBOARD LOGGER\CLIPBOARD LOGGER.EXE"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_BEST_VB_01\URL Logger\URL Logger.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Shell NotePad Loader\Shell NotePad Loader.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Shell Loader Loader\Shell Loader Loader.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Batch_Compiler_Auto\BatchCompiler.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Shell VBasic 6 Loader\Shell VBasic 6 Loader.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_SEND_TO\Send To Text List of Files & Sub Folders IRFAN\#0 Send To Text List of Files and Sub Folders IRFAN.EXE"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\VB_KEEP_RUNNER\VB_KEEP_RUNNER.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\CPU % OF A PROGRAM\CPU % INDIVIDUAL PROCESS.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Clipboard Logger\ClipBoard Logger.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\CLIPBOARD_VIEWER\ClipBoard Viewer.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\URL Logger\URL Logger.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\EliteSpy\EliteSpy.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Tidal_Info\Tidal.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_Best_VB_01\Cid-Run-Me-Ace\Cid-RunMe.exe"
I=I+1:ARRAY_1(I)="D:\VB6\VB-NT\00_SEND_TO\Send To Text List of Files & Sub Folders IRFAN\#0 Send To Text List of Files and Sub Folders IRFAN.EXE"
I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Microsoft Speech SDK 5.1\Bin\TTSApp.exe"
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\devenv.exe"          ' VISUAL BASIC 2008
I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Microsoft Visual Studio\VB98\VB6.EXE"                                     ' ----------------------
I=I+1:ARRAY_1(I)="C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\devenv.exe" ' VISUAL BASIC 2026

I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Microsoft Visual Studio\VB98\VB6.EXE"

I=I+1:ARRAY_1(I)="C:\Program Files\Unity\Editor\Unity.exe" ' Visual Studio 2018 Unity 2018.3.7f1 (64-bit)
' THERE IS A 2017 VERSION BUT SAME LINK AS THIS ONE JUST ONLY DIFF 2017 VS 2018
' AS I SPEAK 2017 LINK REDIRECTING TO 2018 BOTH LINKS GO THERE
'--------------------------------------------------------------------------------------------------------

I=I+1:ARRAY_1(I)="C:\Program Files\Logitech\SetPointP\SetPoint.exe"

I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Microsoft Visual Studio Tools for Unity\15.0\Visual Studio 2017 Tools.unitypackage"
I=I+1:ARRAY_1(I)=""


' -------------------------------------------------------------------
' -------------------------------------------------------------------

' -------------------------------------------------------------------
I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Siber Systems\AI RoboForm\Identities.exe"
' -------------------------------------------------------------------
I=I+1:ARRAY_1(I)="C:\Program Files\Siber Systems\GoodSync\GoodSync.exe"

' -------------------------------------------------------------------
' SET_GO_GS=FALSE
' IF GETCOMPUTERNAME="4-ASUS-GL522VW" then SET_GO_GS=TRUE
' IF GETCOMPUTERNAME="7-ASUS-GL522VW" then SET_GO_GS=TRUE

' IF Version_OS=10 THEN
	' I=I+1:ARRAY_1(I)="C:\GOODSYNC JOB CONTROL\GoodSync2Go AHK2EXE - C\AUTOKEY -- 80-AHK TO EXE LOAD GOODSYNC2GO C DRIVE.AHK.EXE"
	' IF SET_GO_GS=TRUE THEN 
		' I=I+1:ARRAY_1(I)="D:\GOODSYNC JOB CONTROL\GoodSync2Go AHK2EXE - D\AUTOKEY -- 80-AHK TO EXE LOAD GOODSYNC2GO D DRIVE.AHK.EXE"
	' END IF
' END IF

IF Version_OS=10 OR Version_OS=11 THEN
	I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\x64\hashmyfiles.exe"
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\Reg Converter\RegConvert.exe"
	'I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\x64\regfromapp.exe"
END IF 



I=I+1:ARRAY_1(I)="C:\PStart\PStart.exe"
I=I+1:ARRAY_1(I)="C:\PStart\Progs\#_PortableApps\Start.exe"
I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirLauncher.exe"
I=I+1:ARRAY_1(I)="C:\Program Files (x86)\WinMerge\WinMergeU.exe"
I=I+1:ARRAY_1(I)="C:\Program Files (x86)\seRapid\seRapid.exe"
' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\TeamViewer\TeamViewer.exe"



I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Notepad++\notepad++.exe"
If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	ARRAY_1(I)="C:\Program Files\Notepad++\notepad++.exe"
END IF


IF GETCOMPUTERNAME="8-MSI-GP62M-7RD" THEN
	' I=I+1:ARRAY_1(I)="C:\Program Files\Piriform\CCleaner 7\CCleaner.exe"
END IF

IF Version_OS=10 THEN
	
	' I=I+1:ARRAY_1(I)="C:\PStart\Progs\#_PortableApps\PortableApps\PicPickPortable\App\picpick\picpick.exe"
	
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\PicPick\picpick.exe"
	
	' I=I+1:ARRAY_1(I)="C:\Program Files\OVH\hubiC\hubiC.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\Common Files\LogiShrd\Unifying\DJCUHost.exe"
END IF

IF Version_OS=11 THEN
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\PicPick\picpick.exe"
	
	' I=I+1:ARRAY_1(I)="C:\Program Files\OVH\hubiC\hubiC.exe"
	' I=I+1:ARRAY_1(I)="C:\Program Files\Piriform\CCleaner 7\CCleaner.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\LogiOptionsPlus\logioptionsplus.exe"
END IF


I=I+1:ARRAY_1(I)="C:\Program Files\JAM Software\TreeSize Free\TreeSizeFree.exe"
If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	' WINDOWS 10 IS USER 32 BIT TREESIZE
	ARRAY_1(I)="C:\Program Files (x86)\JAM Software\TreeSize Free\TreeSizeFree.exe"
END IF

I=I+1:ARRAY_1(I)="C:\Program Files\VS Revo Group\Revo Uninstaller Pro\RevoUninPro.exe"


I=I+1:ARRAY_1(I)="C:\Program Files\Audacity\Audacity.exe"
If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	' WINDOWS 10 IS USER 32 BIT AUDACITY
	ARRAY_1(I)="C:\Program Files (x86)\Audacity\Audacity.exe"
END IF


IF Version_OS=10 THEN
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Cool2000\cool2000.exe"
END IF

' DUPLICATE ENTRY
' I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\Reg Converter\RegConvert.exe"

' IF GETCOMPUTERNAME<>"3-LINDA-PC" THEN
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Duplicate Cleaner Pro\DuplicateCleaner.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Winamp\winamp.exe"
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Greatis\WinDowse\WinDowse.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\MPC-HC\mpc-hc64.exe"
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\MPC-HC\mpc-hc.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\PWGen\PWGen.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\Process Lasso\ProcessLasso.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\ViceVersa Pro\ViceVersa.exe"
' END IF


IF Version_OS=10 OR Version_OS=11 THEN
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\WordWeb\wweb32.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\WordWeb\wwnotray.exe"
	' I=I+1:ARRAY_1(I)="C:\Program Files\WinHTTrack\WinHTTrack.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\WinRAR\WinRAR.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\UltraISO\UltraISO.exe"
END IF



' I=I+1:ARRAY_1(I)="C:\PStart\Progs\#_PortableApps\PortableApps\ProcessExplorerPortable\ProcessExplorerPortable.exe"

IF GETCOMPUTERNAME<>"3-LINDA-PC" THEN
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\01 www.System Internals.com\SysInternals\SysinternalsSuite\procexp.exe"
	' I=I+1:ARRAY_1(I)="C:\PStart\Progs\#_PortableApps\PortableApps\AutorunsPortable\App\Autoruns\Autoruns64.exe"
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\01 www.System Internals.com\SysInternals\SysinternalsSuite\Autoruns.exe"

END IF

PART_WIZ="C:\Program Files\MiniTool Partition Wizard 10\partitionwizard.exe"
If objFSO.FileExists(PART_WIZ) = TRUE Then
	I=I+1:ARRAY_1(I)=PART_WIZ
END IF
PART_WIZ="C:\Program Files\MiniTool Partition Wizard 11\partitionwizard.exe"
If objFSO.FileExists(PART_WIZ) = TRUE Then
	I=I+1:ARRAY_1(I)=PART_WIZ
END IF
PART_WIZ="C:\Program Files\MiniTool Partition Wizard 12\partitionwizard.exe"
If objFSO.FileExists(PART_WIZ) = TRUE Then
	I=I+1:ARRAY_1(I)=PART_WIZ
END IF
PART_WIZ="C:\Program Files\MiniTool Partition Wizard 13\partitionwizard.exe"
If objFSO.FileExists(PART_WIZ) = TRUE Then
	I=I+1:ARRAY_1(I)=PART_WIZ
END IF







IF Version_OS=10 THEN
	I=I+1:ARRAY_1(I)="C:\Program Files\MiniToolPowerDataRecovery\PowerDataRecovery.exe"
END IF

I=I+1:ARRAY_1(I)="C:\Program Files (x86)\NeoSmart Technologies\EasyBCD\EasyBCD.exe" ' V 2.4

' I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\EASYBCD\EasyBCD 2.4.exe" THIS IS INSTALLER

I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\EASY USB CREATOR 2.3.2\Easy USB Creator v2.3.2.exe" ' PAID FOR

I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\EASYBCD\ImgBurn.exe"

I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\RUFUS\rufus-3.1.exe" 'LATEST

' I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\EASYBCD\Easy USB Creator Lite.exe"




IF Version_OS=10 THEN
	I=I+1:ARRAY_1(I)="C:\ProgramData\Logishrd\LogiOptions\Software\Current\LogiOptionsUI.exe"
	If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
		I=I-1
		I=I+1:ARRAY_1(I)="C:\Program Files\Logitech\LogiOptions\LogiOptions.exe"
	END IF
	' ---------------------------------------------------------------
	' THIS THE NEW VERSION ARRIVE 2019 09 05 
	' "C:\Program Files\Logitech\LogiOptions\LogiOptions.exe"
	' IF BOTH NOT EXIST ANY COMPUTER 
	' THEN PUT BACK AND DISPLAY BOTH FOR NOT EXIST AT ENDER MESSENGER
	' ---------------------------------------------------------------
	If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
		I=I-1
		I=I+1:ARRAY_1(I)="C:\ProgramData\Logishrd\LogiOptions\Software\Current\LogiOptionsUI.exe"
		I=I+1:ARRAY_1(I)="C:\Program Files\Logitech\LogiOptions\LogiOptions.exe"
	END IF
END IF




IF Version_OS=10 THEN

	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero 2018\Nero Vision\NeroVision.exe"
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero 2018\Nero Launcher\NeroLauncher.exe" 


	'I=I+1:ARRAY_1(I)="C:\Program Files (x86)\No-IP\DUC40.exe"
	'I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero TuneItUp\TuneItUp.exe"
	
END IF

'IF GETCOMPUTERNAME<>"3-LINDA-PC" THEN

	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero 2018\Nero WaveEditor\waveedit.exe"
	
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero Apps\Nero WaveEditor\waveedit.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero Common\Nero Launcher\NeroLauncher.exe"
	I=I+1:ARRAY_1(I)="C:\ProgramData\VideoDownloaderUltimateWinApp\VideoDownloaderUltimate.exe"
	
	IF Version_OS=10 THEN
		I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Nero\Nero 2018\Nero WaveEditor\waveedit.exe"
	END IF	
	
	I=I+1:ARRAY_1(I)="C:\Program Files\Mythicsoft\FileLocator Pro\FileLocatorPro.exe"

'END IF


IF Version_OS=10 THEN

	I=I+1:ARRAY_1(I)="C:\Program Files\FileZilla FTP Client\filezilla.exe"
	
	' C:\Program Files\FileZilla Server\filezilla-server-gui.exe --server.name Local --server.host 127.0.0.1 --server.port 14148
	' I=I+1:ARRAY_1(I)="C:\Program Files\FileZilla Server\filezilla-server-gui.exe"
END IF


' MOST UP TO DATE VERSION
' -----------------------
'I=I+1:ARRAY_1(I)="C:\Windows\System32\calc.exe"

I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 01 VB\Calc VB.exe"
I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 02 XP\Calc XP.exe"

' I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 03 07\Calc Windows 7.exe"
' WINDOWS 7 CALC
' CAN'T BE RENAMED OR MOVED
' INSTALL FROM 
' C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 03 07\Old Calculator for Windows 10.exe
' C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 03 07\OldCalcWin10.zip
' ----
' Downloads / Tools by other people / Old Calculator for Windows 10 from Windows 7 or Windows 8
' https://winaero.com/download.php?view.1795
' ----


IF Version_OS=10 OR VERSION_OS=11 THEN
	' WIN 07 CALC FOR WIN 10 OR WIN XP
	' WILL ONLY WORK ON WIN 10 
	' NOT A VALID WINDOWS APPLICATION FOR WINDOWS 7
	' GUESS BE THE SAME ONE AS WIN 07 ANYWAY
	' I=I+1:ARRAY_1(I)="C:\Windows\System32\Calc1.exe" 
	' I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 04 10\Calc Windows 10.exe"
	' I=I+1:ARRAY_1(I)="C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_11.2508.4.0_x64__8wekyb3d8bbwe\CalculatorApp.exe"
	' C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_11.2508.4.0_x64__8wekyb3d8bbwe\CalculatorApp.exe
	
	
	' ------------------------------------------------------------------------------------
	' CALC WINDOWS 11 IS THE SAME AS WINDOWS 10
	' Calc Windows 10.exe IS A LAUNCHER FOR WINDOWS 10 AND WINDOWS 11 CALC
 	' ------------------------------------------------------------------------------------
	
	I=I+1:ARRAY_1(I)="C:\PStart\# NOT INSTALL REQUIRED\CALC WIN 04 10\Calc Windows 10.exe"
END IF

' ---------------------------------------------------------------------------
' ----
' Downloads / Tools by other people / Classic Paint app for Windows 10
' https://winaero.com/download.php?view.1927
' ----
' D:\03_MICROSOFT\# 01 OPERATING_SYSTEM\#_OP_SYS\ClassicPaintforWindows10.zip
' ---------------------------------------------------------------------------
' ORIGINAL LOCATION COMES WITH WINDOWS
' ---------------------------------------------------------------------------


IF Version_OS=10 OR Version_OS=11 THEN
	' DVD RIPER COPIER
	I=I+1:ARRAY_1(I)="C:\Program Files\HandBrake\HandBrake.exe"
	I=I+1:ARRAY_1(I)="C:\Program Files\Oracle\VirtualBox\VirtualBox.exe"
	I=I+1:ARRAY_1(I)="C:\Windows\System32\Taskmgr.exe"
END IF

I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Glarysoft\Software Update 5\Software Update.exe"
If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	ARRAY_1(I)="C:\Program Files (x86)\Glarysoft\Software Update\Software Update.exe"
END IF

IF Version_OS=10 THEN
	' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Evernote\Evernote\EvernoteClipper.exe"
END IF

IF GETCOMPUTERNAME="4-ASUS-GL522VW" THEN
	FOR R_USERNAME=1 TO 8
		U1=TRIM(CSTR(R_USERNAME))
		U2="C:\Users\MATT 0"+U1+"\AppData\Roaming\Insync\App\Insync.exe"
		If objFSO.FileExists(U2) = TRUE Then
			I=I+1:ARRAY_1(I)=U2
		END IF
	NEXT
	
	' THIS IS A WINDOWS APP AND WONT WORK PUT ON DESKTOP BY HERE
	' press Win + R, type shell:AppsFolder, find the app, right-click it, and select "Create shortcut"
	'
	' I=I+1:ARRAY_1(I)="C:\Program Files\WindowsApps\DigitalVolcanoSoftware.40903F03D22BA_5.26.0.0_x64__55chcb595f864\Duplicate Cleaner 5\Duplicate Cleaner 5.exe"
	
END IF


' IF GETCOMPUTERNAME="8-MSI-GP62M-7RD" THEN
	FOR R_USERNAME=1 TO 8
		U1=TRIM(CSTR(R_USERNAME))
		U2="C:\Users\MATT 0"+U1+"\AppData\Roaming\Insync\App\Insync.exe"
		If objFSO.FileExists(U2) = TRUE Then
			I=I+1:ARRAY_1(I)=U2
		END IF
	NEXT
' END IF


IF Version_OS=10 THEN
	I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Microsoft Office\Office12\OUTLOOK.EXE"
END IF


I=I+1:ARRAY_1(I)="C:\Program Files (x86)\TextCrawler Pro\TextCrawler.exe"


' I=I+1:ARRAY_1(I)="C:\PStart\Progs\#_Hiren_Programs\Programs\guiformat.exe"





I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Arduino\arduino.exe"
If objFSO.FileExists(ARRAY_1(I)) = FALSE Then
	ARRAY_1(I)=""
	' I=I-1
END IF

' CHANGE FORM 7-ASUS-GL522VW"
IF GETCOMPUTERNAME="4-ASUS-GL522VW" THEN
	I=I+1:ARRAY_1(I)="C:\Users\" & GETUSERNAME & "\AppData\Local\GitHubDesktop\GitHubDesktop.exe"
END IF

' C:\Windows\WinSxS\amd64_microsoft-windows-s..ytools-ex.resources_31bf3856ad364e35_10.0.16299.15_en-us_28a070b1f81f73ec\secpol.msc

' "C:\PStart\# NOT INSTALL REQUIRED\FFMPEG\ffmpeg-gui_v1.1- FRONT END CONVERT ANY TO ANY\ffmpeggui\ffmpeggui.exe"


' Fri 20-Mar-2020 01:48:30
' UNINSTALLL HAPPEN
' Alon Video Joiner
IF GETCOMPUTERNAME="4-ASUS-GL522VW" THEN
I=I+1:ARRAY_1(I)="D:\Program Files (x86)\Microsoft Encarta\Encarta Encyclopedia 2001\ENC2001.EXE"
END IF 


' ONLY ON 4-ASUS-GL522VW
' THIS IS A WINDOWS APP
' I=I+1:ARRAY_1(I)="C:\Program Files\WindowsApps\DigitalVolcanoSoftware.40903F03D22BA_5.26.0.0_x64__55chcb595f864\Duplicate Cleaner 5\Duplicate Cleaner 5.exe"



I=I+1:ARRAY_1(I)="C:\Program Files\MiniTool Screen Recorder\MiniTool Screen Recorder.exe"
I=I+1:ARRAY_1(I)="C:\PStart\Progs\0_Nirsoft_Package\NirSoft\mweather.exe"
I=I+1:ARRAY_1(I)="C:\Windows\regedit.exe"

I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""
I=I+1:ARRAY_1(I)=""

ARRAY_1_INDEX=I



' CLIPBOARD(

' ARRAY_5 THESE ARE FOR THE TASKBAR
' ARRAY_1 THESE ARE FOR DESKTOP
' --------------------------
I=1
I=I+1:ARRAY_5(I)="C:\PStart\Progs\#_PortableApps\PortableApps\AutorunsPortable\AutorunsPortable.exe"
' I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe"
'I=I+1:ARRAY_5(I)="C:\PStart\# NOT INSTALL REQUIRED\Advanced_Renamer\ARen.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Advanced Renamer\ARen.exe"

' -- REPEAT IN ARRAY_1
' -------------------------
' I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Arduino\arduino.exe"

I=I+1:ARRAY_5(I)="D:\GOODSYNC JOB CONTROL\GoodSync2Go AHK2EXE - D\AUTOKEY -- 80-AHK TO EXE LOAD GOODSYNC2GO D DRIVE.AHK.EXE"
I=I+1:ARRAY_5(I)="C:\Users\MATT 01\AppData\Local\balena_etcher\balenaEtcher.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\BootRacer\Bootrace.exe"

IF Version_OS=10 THEN
	I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Canon\Quick Menu\CNQMMAIN.EXE"
	' --- TRY WINDOWS 11 LATER NEVER USE THE THING
	I=I+1:ARRAY_5(I)="C:\Program Files (x86)\DOSBox-0.72\dosbox.exe"
END IF

I=I+1:ARRAY_5(I)="C:\Program Files\Defraggler\Defraggler.exe"

I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Duplicate Cleaner Pro\DuplicateCleaner.exe"
I=I+1:ARRAY_5(I)="C:\PStart\# NOT INSTALL REQUIRED\EASY USB CREATOR 2.3.2\Easy USB Creator v2.3.2.exe"
'I=I+1:ARRAY_5(I)="C:\WINDOWS\Installer\{03EC818F-96E5-497F-AF28-EC6BC4CF32D3}\EasyVideoMaker.exe_96942AE20DCC466DBFC84D044"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\NeoSmart Technologies\EasyBCD\EasyBCD.exe" ' V 2.4

' I=I+1:ARRAY_5(I)="D:\Program Files (x86)\Microsoft Encarta\Encarta Encyclopedia 2001\ENC2001.EXE"
I=I+1:ARRAY_5(I)="C:\Program Files\Mythicsoft\FileLocator Pro\FileLocatorPro.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Mozilla Firefox\firefox.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\foobar2000\foobar2000.exe"
'I=I+1:ARRAY_5(I)="C:\WINDOWS\Installer\{01995E6E-DABA-47BE-8E59-4149038DAC0A}\FreeSpeedVideo.exe_11C90DF38DEB457BA61C5A87D"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Freemake\Freemake Audio Converter\FreemakeAudioConverter.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Freemake\Freemake Music Box\FreemakeMusicBox.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Freemake\Freemake Video Downloader\FreemakeVideoDownloader.exe"
IF FSO.FILEEXISTS("C:\Program Files (x86)\Freemake\Freemake Downloader\FreemakeVC.exe")=TRUE THEN 
	ARRAY_5(I)="C:\Program Files (x86)\Freemake\Freemake Downloader\FreemakeVC.exe"
END IF

IF Version_OS=10 THEN
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Freemake\Freemake YouTube To MP3 Boom\FreemakeYB.exe"
END IF
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Freemake\Freemake Video Converter\FreemakeVC.exe"
'I=I+1:ARRAY_5(I)="C:\Program Files\Git\git-bash.exe"
I=I+1:ARRAY_5(I)="C:\Users\MATT 01\AppData\Local\GitHubDesktop\GitHubDesktop.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Siber Systems\GoodSync\GoodSync.exe"
' I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Google\Drive File Stream\launch.bat"
I=I+1:ARRAY_5(I)="C:\HBCD\Programs\Programs\grubinst_gui.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\HandBrake\HandBrake.exe"
I=I+1:ARRAY_5(I)="C:\HBCD\HBCDMenu.exe"

IF Version_OS=10 THEN
	I=I+1:ARRAY_5(I)="C:\Program Files\WinHTTrack\WinHTTrack.exe"
END IF

I=I+1:ARRAY_5(I)="C:\Program Files (x86)\IMGBURN\ImgBurn.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\seRapid\seRapid.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\IObit\IObit Unlocker\IObitUnlocker.exe"

' SORT HERE
' I=I+1:ARRAY_5(I)="C:\Program Files (x86)\IrfanView\i_view64.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\IrfanView\i_view64.exe"

U2="C:\Program Files (x86)\IrfanView\i_view32.exe"
If objFSO.FileExists(U2) = TRUE Then
	I=I+1:ARRAY_5(I)=U2
END IF

U2="C:\Program Files (x86)\Kat MP3 Recorder\Kat MP3 Recorder.exe"
If objFSO.FileExists(U2) = TRUE Then
	I=I+1:ARRAY_5(I)=U2
END IF

I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Mega Video Converter\Client.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\MiniTool Partition Wizard 13\partitionwizard.exe"

' -- GOT IN WINDOWS 10 REPEAT BEFORE
' ---------------------------------------------
' I=I+1:ARRAY_5(I)="C:\Program Files\MiniToolPowerDataRecovery\PowerDataRecovery.exe"


I=I+1:ARRAY_5(I)="C:\Program Files (x86)\MP4Tools\bin\MP4Joiner.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\MP4Tools\bin\MP4Splitter.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\MPC-HC\mpc-hc64.exe"
'I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Nero\Nero 2018\Nero Launcher\NeroLauncher.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Nero\Nero Common\Nero Launcher\NeroLauncher.exe"
' SORT HERE
' I=I+1:ARRAY_5(I)="C:\Program Files\Norton\Utilities\NortonUtilitiesUI.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Oracle\VirtualBox\VirtualBox.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\PicPick\picpick.exe"
' I=I+1:ARRAY_5(I)="C:\Program Files\Piriform\CCleaner 7\CCleaner.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Recuva\recuva64.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Speccy\Speccy64.exe"
' C:\Program Files\Process Lasso\ProcessLasso.exe
' I=I+1:ARRAY_5(I)="C:\Program Files\Process Lasso\ProcessLassoLauncher.exe"
I=I+1:ARRAY_5(I)="C:\PStart\PStart.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\PWGen\PWGen.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\QNAP\Qfinder\QfinderPro.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\RemoteNetBackup\RemoteBackup.exe"
' ONLY FOR THE MACHINES COMPUTER THAT HAVE IT
IF FSO.FILEEXISTS("C:\Program Files (x86)\RemoteNetBackup\RemoteBackup.exe") = FALSE THEN 
	ARRAY_5(I)=""
END IF

I=I+1:ARRAY_5(I)="C:\Program Files\VS Revo Group\Revo Uninstaller Pro\RevoUninPro.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\seRapid\seRapid.exe"
'I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Samsung\SideSync4\SideSync.exe"
'I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Samsung\Smart Switch PC\SmartSwitchPC.exe"
' I=I+1:ARRAY_1(I)="C:\Program Files (x86)\Glarysoft\Software Update 5\Software Update.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Speccy\Speccy64.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\TextCrawler Pro\TextCrawler.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\JAM Software\TreeSize Free\TreeSizeFree.exe"
'I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Wondershare\Wondershare TunesGo (Win) - Android Devices\TunesGo.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\UltraISO\UltraISO.exe"
'I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Common Files\Logishrd\Unifying\DJCUHost.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\USB Safely Remove\USBSafelyRemove.exe"
I=I+1:ARRAY_5(I)="D:\#0 1 INSTALLATIONS\00 INSTALLER_SET\# 00 Install Progs\# Installed Now\#00 Paid For\USBIMAGER\usbimager.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\ViceVersa Pro\ViceVersa.exe"
I=I+1:ARRAY_5(I)="C:\ProgramData\VideoDownloaderUltimateWinApp\VideoDownloaderUltimate.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\Oracle\VirtualBox\VirtualBox.exe"
' I=I+1:ARRAY_5(I)="C:\Program Files\VSPlayer\VSPlayer.exe"




U2="C:\Program Files\VSPlayer\VSPlayer\VSPlayer.exe" '  HIKVISION
If objFSO.FileExists(U2) = TRUE Then
	I=I+1:ARRAY_5(I)=U2
END IF

I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Nero\Nero Apps\Nero WaveEditor\waveedit.exe"

U2="C:\Program Files (x86)\Nero\Nero 2018\Nero WaveEditor\waveedit.exe"
If objFSO.FileExists(U2) = TRUE Then
	I=I+1:ARRAY_5(I)=U2
END IF

I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Winamp\winamp.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\WinRAR\WinRAR.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Wise\Wise Video Converter\WiseVideoConverter.exe"
'I=I+1:ARRAY_5(I)="C:\WINDOWS\Installer\{58582B88-0260-4C80-9A89-8CA0923AFD26}\_4ae13d6c.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\XnViewMP\xnviewmp.exe"
'I=I+1:ARRAY_5(I)="C:\Windows\Installer\{543D2D61-3E3D-4CAD-A39A-B40D7E0911DB}\YoutubeMovieMaker._1396BF56F31E4060B7BF96A42"


I=I+1:ARRAY_5(I)="C:\HBCD\Programs\Programs\GRUBInst_GUI.exe"
I=I+1:ARRAY_5(I)="C:\HBCD\HBCDMenu.exe"

U2="C:\Program Files\WinHTTrack\WinHTTrack.exe"
If objFSO.FileExists(U2) = TRUE Then
	I=I+1:ARRAY_5(I)=U2
END IF


I=I+1:ARRAY_5(I)="C:\Program Files (x86)\Mega Video Converter\Client.exe"
I=I+1:ARRAY_5(I)="C:\PStart\# NOT INSTALL REQUIRED\Reg Converter\RegConvert.exe"
I=I+1:ARRAY_5(I)="C:\Program Files\ViceVersa Pro\ViceVersa.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\MP4Tools\bin\MP4Splitter.exe"
I=I+1:ARRAY_5(I)="C:\Program Files (x86)\MP4Tools\bin\MP4Joiner.exe"
I=I+1:ARRAY_5(I)="C:\Windows\System32\cmd.exe"
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""
I=I+1:ARRAY_5(I)=""



' ---- TAKE ALL TASKBAR ONE AND USE FOR DESKTOP
' PUT ALL ARRAY1 IN ARRAY5 AND OPPOSITE
' ---------------------------------------------
' IF Version_OS=11 THEN
	FOR R_INDEX = 1 TO UBOUND(ARRAY_1)
 		IF ARRAY_1(R_INDEX)<>"" THEN 
			TO_GO=TRUE
			FOR T_INDEX = 1 TO UBOUND(ARRAY_5)
				' REPEAT OFFENDER -- ARRAY_5
				IF ARRAY_5(T_INDEX)=ARRAY_1(R_INDEX) THEN TO_GO=FALSE
			NEXT
			IF TO_GO=TRUE THEN 
				I=I+1:ARRAY_5(I)=ARRAY_1(R_INDEX)
			END IF
		END IF
	NEXT
' END IF
	
	FOR R_INDEX = 1 TO UBOUND(ARRAY_5)
 		IF ARRAY_5(R_INDEX)<>"" THEN 
			TO_GO=TRUE
			FOR T_INDEX = 1 TO UBOUND(ARRAY_5)
				' REPEAT OFFENDER -- ARRAY_5
				IF ARRAY_5(T_INDEX)=ARRAY_1(R_INDEX) THEN TO_GO=FALSE
			NEXT
			IF TO_GO=TRUE THEN 
				ARRAY_1_INDEX=ARRAY_1_INDEX+1:ARRAY_1(ARRAY_1_INDEX)=ARRAY_5(R_INDEX)
			END IF
		END IF
	NEXT
' 


	' FILTER WHAT DON'T WANT FOR TASK BAR
	DIM ARRAY_FILTER_5(150)
	I_22=0
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="FreemakeAudioConverter.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="FreemakeMusicBox.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="dosbox.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="AUTOKEY -- 80-AHK TO EXE LOAD GOODSYNC2GO D DRIVE.AHK.EXE"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Bootrace.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="foobar2000.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="FreemakeYB.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="FreemakeVideoDownloader.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="WinHTTrack.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="grubinst_gui.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="HBCDMenu.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="CNQMMAIN.EXE" ' CANNON PRINTER
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="IObitUnlocker.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="msedge.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Kat MP3 Recorder.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="MP4Joiner.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Speccy64.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="recuva64.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="RemoteBackup.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="specialfoldersview.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="NortonUI.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="xnviewmp.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="WiseVideoConverter.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="usbimager.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Clip_Type.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="PowerDataRecovery.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="TTSApp.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="OUTLOOK.EXE"
	
	
	' SOME DON'T FIND WITH .EXE EXTENSION
	' ADD CODE TO FILTER IT OFF
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="EliteSpy.exe"
	' I_22=I_22+1:ARRAY_FILTER_5(I_22)="EliteSpy"
	
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="#0 Send To Multi Menu.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Clip_Type.exe"
	' I_22=I_22+1:ARRAY_FILTER_5(I_22)="Clip_Type"
	
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="bluetoothlogview.exe"
	' I_22=I_22+1:ARRAY_FILTER_5(I_22)="BLUETOOTHLOGVIEW"

	I_22=I_22+1:ARRAY_FILTER_5(I_22)="bluetoothview.exe"
	' I_22=I_22+1:ARRAY_FILTER_5(I_22)="BLUETOOTHVIEW"

	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Ultimate Windows Tweaker 4.1.1.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="RemoteBackup.exe" ' UNINSTALL HERE HIKVISION
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="msedge.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="nero.exe" ' Nero Burning ROM
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="hashmyfiles.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="NeroVision.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="CNQMMAIN.EXE" ' CANNON PRINTER
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="TunesGo.exe"  ' UNINSTALL HERE
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="SideSync.exe" ' UNINSTALL HERE
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="HBCDMenu.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Kat MP3 Recorder"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Code.exe" ' "C:\Program Files\Microsoft VS Code\Code.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="WinHTTrack.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="AutorunsPortable.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="vlc.exe" ' NOT IN ARRAY_5
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="ENC2001"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="balenaEtcher.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="VirtualBox.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="MP4Splitter.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="Client.exe"    ' Mega Video Converter
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="VSPlayer.exe"  ' HIKVISION
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="mweather.exe"	
	I_22=I_22+1:ARRAY_FILTER_5(I_22)="SetPoint.exe"
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""	
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""	
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""
	I_22=I_22+1:ARRAY_FILTER_5(I_22)=""
	
	FOR R_INDEX_1 = 1 TO UBOUND(ARRAY_FILTER_5)
	FOR R_INDEX_2 = 1 TO UBOUND(ARRAY_5)
 		IF ARRAY_FILTER_5(R_INDEX_1)<>"" THEN
 		IF ARRAY_5(R_INDEX_2)<>"" THEN
			' MSGBOX ARRAY_5(R_INDEX_2)
			SEARCH_WITH_NOT_EXT=UCASE(ARRAY_FILTER_5(R_INDEX_1))
			' THERE MIGHT BE TWO PATH *.EXE.LNK -- REMOVE END ONE ONCE OKAY BUT NOT TWICE
			' DO HERE INSTEAD
			SEARCH_WITH_NOT_EXT=REPLACE(UCASE(SEARCH_WITH_NOT_EXT),".LNK","")
			SEARCH_WITH_NOT_EXT=REPLACE(UCASE(SEARCH_WITH_NOT_EXT),".EXE","")
			IF INSTR(SEARCH_WITH_NOT_EXT,".")>0 THEN 
				SEARCH_WITH_NOT_EXT=MID(SEARCH_WITH_NOT_EXT,1,INSTR(SEARCH_WITH_NOT_EXT,".")-1)
			END IF
			IF INSTR(UCASE(ARRAY_5(R_INDEX_2)),SEARCH_WITH_NOT_EXT)>0 THEN 
				IF INSTR(SEARCH_WITH_NOT_EXT,"ENC2")>0 THEN 
					' MSGBOX SEARCH_WITH_NOT_EXT
				END IF
				ARRAY_5(R_INDEX_2)=""
				' MSGBOX SEARCH_WITH_NOT_EXT
			END IF
		END IF
		END IF
	NEXT
	NEXT

	' -------------------------------------------------------------
	' CLEAN UP THIS CODE
	' DUPLICATE ARRAY 
	' WE WANTED MORE FOR DESKTOP LESS FOR TASKBAR WITH FILTERED OFF
	' BUT THE SAME
	' WHAT FILTER IS GOOD
	' -------------------------------------------------------------
	FOR R_INDEX_1 = 1 TO UBOUND(ARRAY_FILTER_5)
	FOR R_INDEX_2 = 1 TO UBOUND(ARRAY_1)
 		IF ARRAY_FILTER_5(R_INDEX_1)<>"" THEN
 		IF ARRAY_1(R_INDEX_2)<>"" THEN
			' MSGBOX ARRAY_5(R_INDEX_2)
			SEARCH_WITH_NOT_EXT=UCASE(ARRAY_FILTER_5(R_INDEX_1))
			' THERE MIGHT BE TWO PATH *.EXE.LNK -- REMOVE END ONE ONCE OKAY BUT NOT TWICE
			' DO HERE INSTEAD
			SEARCH_WITH_NOT_EXT=REPLACE(UCASE(SEARCH_WITH_NOT_EXT),".LNK","")
			SEARCH_WITH_NOT_EXT=REPLACE(UCASE(SEARCH_WITH_NOT_EXT),".EXE","")
			IF INSTR(SEARCH_WITH_NOT_EXT,".")>0 THEN 
				SEARCH_WITH_NOT_EXT=MID(SEARCH_WITH_NOT_EXT,1,INSTR(SEARCH_WITH_NOT_EXT,".")-1)
			END IF
			IF INSTR(UCASE(ARRAY_1(R_INDEX_2)),SEARCH_WITH_NOT_EXT)>0 THEN 
				IF INSTR(SEARCH_WITH_NOT_EXT,"ENC2")>0 THEN 
					' MSGBOX SEARCH_WITH_NOT_EXT
				END IF
				ARRAY_1(R_INDEX_2)=""
				' MSGBOX SEARCH_WITH_NOT_EXT
			END IF
		END IF
		END IF
	NEXT
	NEXT
	










' -------------------------------------------------------------------
' WORK
' -------------------------------------------------------------------
' DO A CHECK FOR DUPLICATE CROSS ARRAY
' -------------------------------------------------------------------



' -------------------------------------------------------------------
' ASUS 5-P NOT REQUIRED ON TASKBAR
' -------------------------------------------------------------------
' C:\Program Files\# NO INSTALL REQUIRED\Advanced_Renamer\ARen.exe
' C:\Program Files (x86)\Nokia\Nokia Suite\NokiaSuite.exe
' C:\PStart\Progs\0_Nirsoft_Package\NirSoft\x64\specialfoldersview.exe
' C:\Program Files\CCleaner\CCleaner64.exe
' C:\Program Files\Common Files\Logishrd\Unifying\DJCUHost.exe
' C:\Program Files\OVH\hubiC\hubiC.exe" run --showsync
' -------------------------------------------------------------------
' ASUS 5-P NOT INSTALLED YET AND SORT IF WANT PLACED WITH TASKBAR
' -------------------------------------------------------------------
' -------------------------------------------------------------------
' ASUS 5-P NOT RELEVANT
' -------------------------------------------------------------------
' C:\Program Files (x86)\DFX\dfx.exe
' C:\ProgramData\Logishrd\LogiOptions\Software\Current\LogiOptionsUI.exe
' C:\Windows\System32\Calc1.exe
' -------------------------------------------------------------------
' ASUS 5-P YES SHOW ON TASKBAR
' -------------------------------------------------------------------
' C:\Program Files (x86)\Freemake\Freemake Video Converter\FreemakeVC.exe
' C:\Program Files (x86)\Nero\Nero 2018\Nero Launcher\NeroLauncher.exe
' C:\Program Files (x86)\Nero\Nero 2018\Nero WaveEditor\waveedit.exe
' C:\Program Files\MPC-HC\mpc-hc64.exe
' C:\Program Files (x86)\No-IP\DUC40.exe
' C:\Program Files\HandBrake\HandBrake.exe
' -------------------------------------------------------------------
' ASUS 5-P OFF TASKBAR
' -------------------------------------------------------------------
' C:\Program Files (x86)\Nero\Nero 2018\Nero Vision\NeroVision.exe
' C:\Program Files (x86)\Cool2000\cool2000.exe
' C:\Program Files (x86)\Audacity\audacity.exe
' C:\Program Files\WinHTTrack\WinHTTrack.exe
' C:\Program Files\FileZilla FTP Client\filezilla.exe
' C:\Program Files (x86)\FileZilla Server\FileZilla Server Interface.exe
' -------------------------------------------------------------------


' -------------------------------------------------------------------
' -------------------------------------------------------------------
' -------------------------------------------------------------------
' -------------------------------------------------------------------

' -------------------------------------------------------------------
' -------------------------------------------------------------------
' -------------------------------------------------------------------
' -------------------------------------------------------------------

END SUB


' -------------------------------------------------------
SUB GET_WINDOWS_VERSION
' -------------------------------------------------------
	Set SystemSet = GetObject("winmgmts:").InstancesOf ("Win32_OperatingSystem") 
	for each System in SystemSet 
	' WScript.Echo System.Caption 
	' WScript.Echo System.Manufacturer 
	' WScript.Echo System.BuildType 
	' WScript.Echo " Version: " + System.Version 
	' WScript.Echo " Locale: " + System.Locale 
	' WScript.Echo " Windows Directory: " + System.WindowsDirectory 
	' WScript.Echo " Total memory: " + System.TotalVisibleMemorySize + " bytes" 
	' WScript.Echo " Serial Number: " + System.SerialNumber 
	' Wscript.Echo "" 
	Version_OS = CINT(MID(System.Version,1,INSTR(System.Version,".")-1))
	'WINDOWS 7 = 6.1.7601 
	'WINDOWS 11 = 10.0.26200
	' IF System.Version =10.0.26200 THEN Version_OS=11

	IF GETCOMPUTERNAME="9-ASUS-G815LM" THEN Version_OS="11"

	next 
END SUB

' THIS CODE NOT RUN
' -------------------------------------------------------
SUB RUN_THE_CODE_PIN_TO
' -------------------------------------------------------

' ------------------------------------
' CHECK FOR DUPLICATES MASSIVE SPEEDER
' ------------------------------------
obj_SOURCE_Folder = AppDataLocation & "\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
CALL GET_LINK_SET_STRING_1(objSuperFolder)

FOR R_SET=1 TO UBOUND(ARRAY_1)
	IF ARRAY_1(R_SET)<>"" THEN 
		If objFSO.FileExists(ARRAY_1(R_SET)) = TRUE Then
			FILE_SCAN_FIND_1=UCASE(MID(ARRAY_1(R_SET),INSTR(ARRAY_1(R_SET),"\")+1))

			
			IF INSTR(LINK_SET_STRING_1 ,FILE_SCAN_FIND_1)=0 THEN 
				ARRAY_4(R_SET)=TRUE
				LINK_SET_EXIST_TOTAL_VERIFY_FAIL = LINK_SET_EXIST_TOTAL_VERIFY_FAIL + 1
				LINKTEXT_SET_NOT_VERIFY = LINKTEXT_SET_NOT_VERIFY + ARRAY_1(R_SET) + VBCRLF
			END IF
		END IF
	END IF
NEXT

IF LINK_SET_EXIST_TOTAL_VERIFY_FAIL>0 THEN 
	LINK_SET_EXIST_TOTAL_VERIFY_2= "THE FOLLOW SET DOUBLE VERIFY NOT MAKE IT ON"+VBCRLF+VBCRLF+"OPEN IN EXPLORER _ YES / NOT" & VBCRLF & VBCRLF & "ERROR COUNTER  " & LINK_SET_EXIST_TOTAL_VERIFY_FAIL & VBCRLF & VBCRLF & LINKTEXT_SET_NOT_VERIFY
END IF


END SUB


' ----------------------------------------------
SUB GET_LINK_SET_STRING_1(fFolder)
' ----------------------------------------------
	TT_EDITOR_1=""
	TT_EDITOR_2=""
	LINK_SET_STRING_1 =""
	Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
	Dim oFile
	For Each objFile in colFiles
		Set oFile = oFSO.GetFile(objFile.PATH)
		
		If IsNull(oFile) =FALSE Then 
			' MsgBox("File not found: " & objFile.PATH),vbMsgBoxSetForeground,Wscript.ScriptName  : Exit SUB
			
			With oFile.OpenAsTextStream()
				readBinary = .Read(oFile.Size)
				.Close
			End With
			
			TT_EDITOR_1 = readBinary
			TT_EDITOR_2 = oFile.NAME
			'MSGBOX oFile.NAME
			' MSGBOX oFile.NAME
			' TT_EDITOR_1= TT_EDITOR_1 &VBCRLF objFile.PATH
			
			IF LEN(TT_EDITOR_1)>0 THEN 
				LINK_SET_STRING_1 =LINK_SET_STRING_1 &  VBCRLF & TT_EDITOR_1 & VBCRLF & oFile.NAME
			END IF
		END IF
		
	Next
	LINK_SET_STRING_1 =UCASE(LINK_SET_STRING_1)
End SUB


' ----------------------------------------------
FUNCTION LINK_ALREADY_EXIST_DOUBLE_VERIFY_2(fFolder)
' ----------------------------------------------
	TT_EDITOR_2=""
	AATRUE=""
	LINK_ALREADY_EXIST_DOUBLE_VERIFY_2=""
	Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
	Dim oFile
	For Each objFile in colFiles
		

		' ----------------------------------------
		' VBScript Scripting Techniques: Shortcuts
		' ----------------------------------------
		' https://www.robvanderwoude.com/vbstech_shortcuts.php
		' ----------------------------------------
		' Author: Denis St-Pierre
		' *Retrieves* Shortcut info without using WMI
		' The *Undocumented* Trick: use the ".CreateShortcut" method without the
		' ".Save" method; works like a GetShortcut when the shortcut already exists!

		Set oFile = oFSO.GetFile(objFile.PATH)
		strTargetPath=oFile
		GOGOLINK=FALSE
		IF INSTR(UCASE(strTargetPath),".URL")>0 THEN GOGOLINK=TRUE
		IF INSTR(UCASE(strTargetPath),".LNK")>0 THEN GOGOLINK=TRUE
		IF GOGOLINK=TRUE THEN 
			Set wshShell    = CreateObject("WScript.Shell")
			' CreateShortcut works like a GetShortcut when the shortcut already exists!
			Set objShortcut = wshShell.CreateShortcut(strTargetPath)

			' For URL shortcuts, only ".FullName" and ".TargetPath" are valid
			' WScript.Echo "Full Name         : " & objShortcut.FullName
			' WScript.Echo "Arguments         : " & objShortcut.Arguments
			' WScript.Echo "Working Directory : " & objShortcut.WorkingDirectory
			' WScript.Echo "Target Path       : " & objShortcut.TargetPath
			' WScript.Echo "Icon Location     : " & objShortcut.IconLocation
			' WScript.Echo "Hotkey            : " & objShortcut.Hotkey
			' WScript.Echo "Window Style      : " & objShortcut.WindowStyle
			' WScript.Echo "Description       : " & objShortcut.Description


			' MSGBOX "8888" & VBCRLF & objShortcut.FullName & VBCRLF & objShortcut.TargetPath & VBCRLF 
			TT_EDITOR_2 = TT_EDITOR_2 & strTargetPath & VBCRLF & objShortcut.TargetPath & VBCRLF & "------------" & VBCRLF

			Set objShortcut = Nothing
			Set wshShell    = Nothing		
		END IF
	Next
	
	' MSGBOX  TT_EDITOR_2
			
	LINK_ALREADY_EXIST_DOUBLE_VERIFY_2=TT_EDITOR_2
	
	
	' SET WSHShell = WScript.CreateObject("WScript.Shell")
	' Set objShell = WScript.CreateObject("WScript.Shell")
	' strDesktop = objShell.SpecialFolders("Desktop")
	' Set FOLDER = FSO.GETFOLDER(strDesktop)

	AATRUE=TT_EDITOR_2


	' MSGBOX AATRUE
	' Wscript.QUIT				' WScript.Quit(0)
End FUNCTION






' ----------------------------------------------
FUNCTION LINK_ALREADY_EXIST_DOUBLE_VERIFY(fFolder,FILE_SCAN_FIND_1)
' ----------------------------------------------
	LINK_ALREADY_EXIST_DOUBLE_VERIFY=FALSE
	Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
    FILE_SCAN_FIND_1=MID(FILE_SCAN_FIND_1,INSTR(FILE_SCAN_FIND_1,"\")+1)
	Dim oFile
	For Each objFile in colFiles
		'Set File_1 = fso.OpenTextFile(objFile.PATH, ForReading,0,0)
		
		Set oFile = oFSO.GetFile(objFile.PATH)
		If IsNull(oFile) Then MsgBox("File not found: " & strPath),vbMsgBoxSetForeground,Wscript.ScriptName  : Exit Function
		With oFile.OpenAsTextStream()
			readBinary = .Read(oFile.Size)
			.Close
		End With
		
		TT_EDITOR_1 = readBinary
		' BINARY
		IF INSTR(UCASE(TT_EDITOR_1),UCASE(FILE_SCAN_FIND_1))>0 THEN 
			MSGBOX FILE_SCAN_FIND_1
			LINK_ALREADY_EXIST_DOUBLE_VERIFY=TRUE
			EXIT FOR
		END IF
	Next
	MSGBOX  TT_EDITOR_1
End FUNCTION


' ----------------------------------------------
FUNCTION LINK_ALREADY_EXIST(fFolder,FILE_SCAN_FIND_1)
' ----------------------------------------------
	LINK_ALREADY_EXIST=FALSE
	Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
    FILE_SCAN_FIND_1=MID(FILE_SCAN_FIND_1,INSTR(FILE_SCAN_FIND_1,"\")+1)
	Dim oFile
	For Each objFile in colFiles
		'Set File_1 = fso.OpenTextFile(objFile.PATH, ForReading,0,0)
		
		Set oFile = oFSO.GetFile(objFile.PATH)
		If IsNull(oFile) Then MsgBox("File not found: " & strPath),vbMsgBoxSetForeground,Wscript.ScriptName  : Exit Function
		With oFile.OpenAsTextStream()
			readBinary = .Read(oFile.Size)
			.Close
		End With
		
		TT_EDITOR_1 = readBinary

		IF INSTR(UCASE(TT_EDITOR_1),UCASE(FILE_SCAN_FIND_1))>0 THEN 
			LINK_ALREADY_EXIST=TRUE
		END IF
	Next
End FUNCTION

' ----------------------------------------------
SUB APPDATA_FOLDER_FILE_COUNT(fFolder,FILE_SCAN_FIND_1)
' ----------------------------------------------
	Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
    For Each objFile in colFiles
		FILE_SCAN_FIND_1=FILE_SCAN_FIND_1+1
	Next
	
    For Each Subfolder in fFolder.SubFolders
		' MIGHT AS WELL SUB FOLDER SCAN IT AS THE CODE IS HERE
		' ----------------------------------------------------
        CALL APPDATA_FOLDER_FILE_COUNT(Subfolder,FILE_SCAN_FIND_1)
    Next
End SUB


' ---------------------------------------------------------------------
' NEW SUPER COOL ROUTINE TO INSTANT FIND NORTON UISTUB.EXE
' THE MAIN ENGINE AND ALLOW SHORTCUT
' THEY NORTON FREQUENTLY CHANGE THE NAME OF FOLDER IN PROGRAM FILES
' AND MAY BE LOCATED IN PROGRAM FILES OR PROGRAM FILES (X86)
' AFTER THEY DISCARD AND OLD VERSION THEY NEVER LEAVE UISTUB.EXE BEHIND
' MY CODE SEARCH PROGRAM FILES AND (X86) LIKE NORMAL ONE DO
' BUT IT ONLY SEARCH FOR FIRST PART OF NAME AFTER LIKE EXAMPLE 
' "C:\PROGRAM FILES\NORTON" AND THAT IS ALL AS NORTON ALWAYS START 
' WITH NORTON UP UNTIL NOW
' IS A NEW HIGH SPEED WAY TO SEARCH FOR BETTER CODER
' ---------------------------------------------------------------------
' WRITE CODE TIME
' Sat 09-Mar-2019 23:39:39
' Sat 09-Mar-2019 01:22:00
' ---------------------------------------------------------------------
' 01 OF 02
' ------------------------------------
Sub ShowSubfolders_FIND_NORTON_UISTUB_EXE
' ------------------------------------
	FILE_SCAN_FIND_4=""
	FOR R_COUNT=1 TO 2
		IF R_COUNT=1 THEN obj_SOURCE_Folder = "C:\Program Files"
		IF R_COUNT=2 THEN obj_SOURCE_Folder = "C:\Program Files (X86)"
		Set objSuperFolder = objFSO.GetFolder(obj_SOURCE_Folder)
		For Each Subfolder in objSuperFolder.SubFolders
			If INSTR(UCASE(Subfolder.PATH), UCASE(FILE_SCAN_FIND_1))>0 Then
				If objFSO.FOLDERExists(Subfolder.PATH+"\ENGINE") = TRUE Then
					FILE_SCAN_FIND_2=""
					Set objSuperFolder_2 = objFSO.GetFolder(Subfolder.PATH+"\ENGINE")
					Call ShowSubfolders_FIND_NORTON_UISTUB_EXE_02(objSuperFolder_2, "uistub.exe")
					IF FILE_SCAN_FIND_2<>"" THEN
						FILE_SCAN_FIND_4=FILE_SCAN_FIND_2
						EXIT FOR
					END IF
				End If
			End If
		Next
	Next
End Sub

' ------------------------------------
' 02 OF 02
' ------------------------------------
Sub ShowSubfolders_FIND_NORTON_UISTUB_EXE_02(fFolder,FILE_SCAN_FIND_1)
' ------------------------------------
    Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
    For Each objFile in colFiles
		If INSTR(UCASE(objFile.name)+"*", UCASE(FILE_SCAN_FIND_1)+"*")>0 Then
			FILE_SCAN_FIND_2=objFile.PATH
		End If
    Next
	
    For Each Subfolder in fFolder.SubFolders
		' WITH TWO PARAMETERS YOU HAVE TO USE CALL WORD HERE 
		' OR REMOVE THE BRACKETS
        CALL ShowSubfolders_FIND_NORTON_UISTUB_EXE_02(Subfolder,FILE_SCAN_FIND_1)
    Next
End Sub



' ------------------------------------
Sub ShowSubfolders_FIND_FOLDER(fFolder,FILE_SCAN_FIND_1)
' ------------------------------------
	Set objFolder = objFSO.GetFolder(fFolder.Path)
	Set colFiles = objFolder.Files

	For Each Subfolder in fFolder.SubFolders
		SET_GO=FALSE
		If INSTR(UCASE(Subfolder.PATH), UCASE(FILE_SCAN_FIND_1))>0 Then SET_GO=TRUE
		IF SET_GO=TRUE THEN 
			FILE_SCAN_FIND_2=Subfolder.PATH
			MSGBOX FILE_SCAN_FIND_2,vbMsgBoxSetForeground,Wscript.ScriptName 
			EXIT FOR
		End If

		IF FILE_SCAN_FIND_2="" THEN 
			' CALL ShowSubfolders_FIND_FOLDER(Subfolder,FILE_SCAN_FIND_1)
		END IF
	Next
	
End Sub

' ------------------------------------
Sub ShowSubFolders(fFolder,FILE_SCAN_FIND_1)
' ------------------------------------
    Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
    For Each objFile in colFiles
		SET_GO=FALSE
		If INSTR(UCASE(objFile.name)+"*", UCASE(FILE_SCAN_FIND_1)+"*")>0 Then SET_GO=TRUE
		IF SET_GO=TRUE THEN 
			FILE_SCAN_FIND_2=objFile.PATH
		End If
    Next
	
    For Each Subfolder in fFolder.SubFolders
		' WITH TWO PARAMETERS YOU HAVE TO USE CALL WORD HERE 
		' OR REMOVE THE BRACKETS
        CALL ShowSubFolders(Subfolder,FILE_SCAN_FIND_1)
    Next
End Sub


SUB ROUTINE_DELETE_WSCRIPT_FINDER_RUN
' -------------------------------------------------------------------
' 01 OF 02 
' SOME CONFLICT DISAGREE-ER IN CODE STYLE 
' SOME PEOPLE TALK THIS HAS ERROR 
' THIS ONE IS CORRECT 
' THIS WAS CORRECT 
' THING ARE EXPLAIN HERE
' MSHTA.EXE DELETE ITSELF TOO QUICK FOR RESULT FIND
' NOW WITH BEST EXAMPLE ALSO FIND HIDDEN PROCESS TOP SPEED
' -------------------------------------------------------------------
' PID - FIND MY OWN PROCESS ID IN VBSCRIPT - STACK OVERFLOW 
' https://stackoverflow.com/questions/8296037/find-my-own-process-id-in-vbscript
' -------------------------------------------------------------------
On Error Resume Next
Dim iMyPID
' -------------------
' OLD WAY AND NEW WAY
' -------------------
' iMyPID = GetObject("winmgmts:root\cimv2").Get("Win32_Process.Handle='" & CreateObject("WScript.Shell").Exec("mshta.exe").ProcessID & "'").ParentProcessId
' -------------------
iMyPID=ThisProcessId
On Error Goto 0
 
' -------------------------------------------------------------------
' GOOD CODE TO PASTE ON VB6
' -------------------------------------------------------------------
DIM WSHSHELL
SET WSHSHELL = CreateObject("WScript.Shell")

Set objWMIService = GetObject("winmgmts:{impersonationLevel=impersonate}!\\.\root\cimv2")
Set colProcesses = objWMIService.ExecQuery("select * from win32_process where name = 'wscript.exe'")
' -------------------------------------------------------------------
i1 = 0 ' ANY PROGRAM WSCRIPT 
i2 = 0 ' MY  PROGRAM WSCRIPT 
FOR EACH objProcess IN colProcesses
    IF NOT (IsNull(objProcess.CommandLine )) THEN
		strScriptName = Trim(Right(objProcess.CommandLine,Len(objProcess.CommandLine) - InstrRev(objProcess.CommandLine,"\")))
        strScriptName = Left(strScriptName, Len(strScriptName) - 1)
		PID_Script = objProcess.ProcessID
		
		IF strScriptName = Wscript.ScriptName THEN
			i2=i2+1
		END IF
		IF strScriptName <> Wscript.ScriptName THEN
			i1=i1+1
		END IF
		
		IF i1 > 0 THEN ' ANY PROGRAM WSCRIPT 
			' Wscript.Quit
		END IF
		
		IF iMyPID<>PID_Script THEN 
			' MSGBOX iMyPID & VBCR & PID_Script
			objProcess.Terminate() 
			' WSHSHELL.Run "TASKKILL /F /IM """+CSTR(PID_Script)+"""", DONTShowWindow, WaitUntilFinished
		END IF
    END IF
NEXT
' -------------------------------------------------------------------
END SUB
' -------------------------------------------------------------------
' THING ARE EXPLAIN HERE
' MSHTA.EXE DELETE ITSELF TOO QUICK FOR RESULT FIND
' NOW WITH BEST EXAMPLE ALSO FIND HIDDEN PROCESS TOP SPEED
' -------------------------------------------------------------------
' PID - FIND MY OWN PROCESS ID IN VBSCRIPT - STACK OVERFLOW 
' https://stackoverflow.com/questions/8296037/find-my-own-process-id-in-vbscript
' -------------------------------------------------------------------
' I like Kul-Tigin's idea (+1), and Asok Smith's idea (based on .Exec) deserve respect (+1), 
' and it w'd been even better if .Exec run hidden process. So, to feed my curiosity, 
' I also toyed with this and this's what I did.
' -------------------------------------------------------------------
Function ThisProcessId
    ThisProcessId = 0
    Dim sTFile, oPrc
    With CreateObject("Scripting.FileSystemObject")
        sTFile = .BuildPath(.GetSpecialFolder(2), "sleep.vbs")
        With .OpenTextFile(sTFile, 2, True)
            .Write "WScript.Sleep 1000"
        End With
    End With
    With CreateObject("WScript.Shell").Exec("WScript " & sTFile)
        For Each oPrc In GetObject("winmgmts:\\.\root\cimv2").ExecQuery(_
        "Select * From Win32_Process Where ProcessId=" & .ProcessID)
        Exit For : Next
        ThisProcessId = oPrc.ParentProcessId
    End With
End Function



' --------------------------------------------------------------------
' REFERENCING
' --------------------------------------------------------------------
' ----
' DeployHappiness | Pinning Programs to the Taskbar with Group Policy
' https://deployhappiness.com/pinning-programs-to-the-taskbar-with-group-policy/
' --------
' DeployHappiness | Pin Programs to the Taskbar in Windows 10 with Group Policy
' https://deployhappiness.com/pin-programs-to-the-taskbar-in-windows-10/
' ----

' --------------------------------------------------------------
' HERE IS THE OLD CODE THAT USER PINITEM EXECUTABLE WRITTEN IN C
' SUB SHOW_LEGACY_CODE
' --------------------------------------------------------------
SUB SHOW_LEGACY_CODE_PinTo10_v4

IF 1= 2 THEN 
RESULT_TO_DO=""
RESULT_TO_DO_COUNTER=0
FOR R_SET=1 TO UBOUND(ARRAY_1)
	IF ARRAY_1(R_SET)<>"" AND ARRAY_2(R_SET)=FALSE THEN 
		ITEM_VAR_PATH=Q & MID(ARRAY_1(R_SET),1,INSTRREV(ARRAY_1(R_SET),"\")-1) & Q
		ITEM_VAR_FILE=Q & MID(ARRAY_1(R_SET),INSTRREV(ARRAY_1(R_SET),"\")+1) & Q
		ITEM_VAR_SET=ITEM_VAR_PATH & ITEM_VAR_FILE
		ITEM_VAR_SET=ARRAY_1(R_SET)
		
		' MSGBOX ITEM_VAR_FILE
		
		If objFSO.FileExists(ARRAY_1(R_SET)) = TRUE Then 
			RESULT_TO_DO=RESULT_TO_DO & ITEM_VAR_SET & VBCRLF & VBCRLF
			RESULT_TO_DO_COUNTER=RESULT_TO_DO_COUNTER+1
		END IF
	END IF
NEXT
END IF

' LOAD GOODSYNC2GO C DRIVE.AHK.EXE
IF 1=2 THEN 
FOR R_SET=1 TO UBOUND(ARRAY_1)
	IF ARRAY_1(R_SET)<>"" AND ARRAY_2(R_SET)=FALSE THEN 
		
		ITEM_VAR_PATH=Q & MID(ARRAY_1(R_SET),1,INSTRREV(ARRAY_1(R_SET),"\")-1) & Q
		ITEM_VAR_FILE=Q & MID(ARRAY_1(R_SET),INSTRREV(ARRAY_1(R_SET),"\")+1) & Q
		ITEM_VAR_SET=" /PTFOL:" & ITEM_VAR_PATH & " /PTFILE:" & ITEM_VAR_FILE
		
		' -----------------------------------------------------------
		' USE EXE -- WHEN PinTo10_v4 -- MSI 8-ASUS-M WHICH GOT UPDATE WINDOW
		' NOT WORK ANYMORE
		' RECENT UPDATE SOFTWARE FIND BLOGGER MESSENGER COMMENT
		' NOT WORK EITHER
		' ICON MADDEN SET IN
		' -----------------------------------------------------------
		' Thu 20-Feb-2020 13:02:02
		' Thu 20-Feb-2020 13:33:58 -- 32 MINUTE
		' -----------------------------------------------------------
		' Thu 20-Feb-2020 18:29:08
		' Thu 20-Feb-2020 21:06:22 -- 2 HOUR 37 MINUTE
		' Thu 20-Feb-2020 21:06:22 -- 3 HOUR 09 MINUTE
		' -----------------------------------------------------------
		IF INSTR(PinTo10_EXE_PATH ,"PinTo10_v4")>0  THEN
			
			ITEM_VAR_PATH=MID(ARRAY_1(R_SET),1,INSTRREV(ARRAY_1(R_SET),"\")-1)
			ITEM_VAR_FILE=MID(ARRAY_1(R_SET),INSTRREV(ARRAY_1(R_SET),"\")+1)
			ITEM_VAR_SET=" """+ITEM_VAR_PATH+"\"+ITEM_VAR_FILE+""""+" PIN TASKBAR"
		END IF
		
		' USE POWERSHELL
		IF 1=2 AND INSTR(PinTo10_EXE_PATH ,"PinTo10_v4")>0  THEN
			ITEM_VAR_PATH=MID(ARRAY_1(R_SET),1,INSTRREV(ARRAY_1(R_SET),"\")-1)
			ITEM_VAR_FILE=MID(ARRAY_1(R_SET),INSTRREV(ARRAY_1(R_SET),"\")+1)
			ITEM_VAR_SET=" """+ITEM_VAR_PATH+"\"+ITEM_VAR_FILE+""""+" PIN TASKBAR"
			' -noexit 
			
			PinTo10_EXE_PATH="powershell -noprofile -ExecutionPolicy Bypass -file ""C:\SCRIPTER\SCRIPTER CODE -- VB 02 VBSCRIPT\VBS 12-Pinto10\PinTo10_v4.ps1"""
		END IF
		
		If objFSO.FileExists(PinTo10_EXE_PATH) = FALSE Then 
			MSGBOX "ERROR NOT EXIST "& VBCRLF & PinTo10_EXE_PATH
		END IF

		
		If objFSO.FileExists(ARRAY_1(R_SET)) = TRUE Then 
			' MSGBOX """"&PinTo10_EXE_PATH&""" " & ITEM_VAR_SET
			IF DEBUG_DUMMY_RUN=FALSE THEN 
				objShell.Run """"&PinTo10_EXE_PATH&""" " & ITEM_VAR_SET , 0 , TRUE
			END IF
			EXTRA_ITEM_ADD_TO_TASKBAR = EXTRA_ITEM_ADD_TO_TASKBAR + 1
			
			' MSGBOX ITEM_VAR_FILE
			
			'WScript.Sleep 1000

			IF QUITE_MODE_ENDING=FALSE THEN
				'MSGBOX "ITEM PINNED TO TASKBAR __"+VBCRLF+VBCRLF+ARRAY_1(R_SET)
			END IF
			'WScript.Quit(0)
		END IF
	END IF
NEXT
END IF
END SUB


SUB OLD_REDUNDANT_CODE_SUB_ROUTINE_SHORTCUT_MAKER

	' IF 1=2 THEN ' -- NOT WORK
		' ' ----
		' ' How to create a desktop shortcut with the Windows Script Host 
		' ' https://support.microsoft.com/en-gb/help/244677/how-to-create-a-desktop-shortcut-with-the-windows-script-host
		' ' ----
		' SET WshShell = CreateObject("Wscript.shell")
		' SET strDesktop = WshShell.SpecialFolders("Desktop")
		' ' MSGBOX strDesktop ,vbMsgBoxSetForeground,Wscript.ScriptName
		' oMyShortcut = WshShell.CreateShortcut(strDesktop & "\" & ITEM_VAR_FILE_NOT_EXT & ".lnk")
		' oMyShortcut.WindowStyle = "1" ' 3 &&Maximized 7=Minimized  4=Normal 
		' oMyShortcut.IconLocation = "" ' "C:\myicon.ico"
		' OMyShortcut.TargetPath = ARRAY_1(R_SET)
		' ' oMyShortCut.Hotkey = "" ' "ALT+CTRL+F"
		' oMyShortCut.Save
	' END IF	
	' IF 1=2 THEN ' -- NOT WORK
		' ' ----
		' ' VBScript - Creating a Shortcut 
		' ' https://www.vbsedit.com/html/e6ac108b-15f6-4a54-891f-589e8b687ace.asp
		' ' ----
		' Set Shell = CreateObject("WScript.Shell")
		' DesktopPath = Shell.SpecialFolders("Desktop")
		' DESKTOPPATH="E:\01 Desktop\"+ITEM_VAR_FILE_NOT_EXT+".lnk"
		' ' MSGBOX DesktopPath ,vbMsgBoxSetForeground,Wscript.ScriptName
		' Set link = Shell.CreateShortcut(DESKTOPPATH) 
		' ' DesktopPath)  ' FILENAME
		' link.Arguments = ""          									    ' "1 2 3"
		' link.Description = ""                                               ' "test shortcut"
		' link.HotKey = ""            									    ' "CTRL+ALT+SHIFT+X"
		' link.IconLocation = "app.exe,1"                                     ' AS HERE TESTER
		' link.TargetPath = ARRAY_1(R_SET)
		' link.WindowStyle = 3
		' link.WorkingDirectory = ""   '   "c:\blah"           	            ' IGNOR
		' link.Save
	' END IF
	' ' -----------------------------------------------
END SUB
