

Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "1" /t REG_SZ /d "D:\VB6\VB-NT\00_Send_To\Send To Multi Menu\#0 Send To Multi Menu.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "2" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Run_AS 2011-06-11 VER 1.0.164\Matt_RunAS.VBP" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "3" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Run_AS 2012-10-10 VER 1.0.203\Matt_RunAS.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "4" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Run_AS 2011-06-11\Matt_RunAS.VBP" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "5" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\CPU %% OF A PROGRAM\CPU %% INDIVIDUAL PROCESS.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "6" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\VB_KEEP_RUNNER\VB_KEEP_RUNNER.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "7" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\EliteSpy\EliteSpy.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "8" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Tidal_Info\Tidal.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "9" /t REG_SZ /d "D:\VB6\VB-NT\00_Send_To\Send Cmd\Send_Cmd.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "10" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Clipboard Logger\ClipBoard Logger.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "11" /t REG_SZ /d "D:\VB6\VB-NT\00_Send_To\Send To Date Of File In Front FileName\#0 Send To Date Of File In Front FileName.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "12" /t REG_SZ /d "D:\VB6\VB-NT\00_Send_To\Send To Text List of Files && Sub Folders IRFAN\#0 Send To Text List of Files and Sub Folders IRFAN.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "13" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\CLIPBOARD_VIEWER\ClipBoard Viewer.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "14" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\BLUETOOTH SOUND\BLUETOOTH_LOGGER_SOUND.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "15" /t REG_SZ /d "C:\SCRIPTER\SCRIPTER CODE -- VBS\DELETE_EMPTY_FOLDER_1.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "16" /t REG_SZ /d "D:\DSC\2015-2018\2016 CyberShot HX60V\DCIM\RENAME FOLDER.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "17" /t REG_SZ /d "C:\SCRIPTER\SCRIPTER CODE -- BAT\NET_SHARE\Multiple_Thread Port Scanner 02 CON\Multiple_Port_Scanner.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "18" /t REG_SZ /d "C:\SCRIPTER\SCRIPTER CODE -- BAT\NET_SHARE\Multiple_Thread Port Scanner 02 CON\Multiple Port Scanner.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "19" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Shell Explorer Loader\Shell Explorer Loader.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "20" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Shell Excel Loader\Shell Excel Loader.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "21" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Shell Winamp Loader\Winamp Loader.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "22" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Shell VBasic 6 Loader\Shell VBasic 6 Loader.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "23" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Shell Games Loader\Shell Games Loader.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "24" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Shell Execute Loader\Shell Execute Loader.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "25" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Cid-Run-Me-Ace\Cid-RunMe.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "26" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\10 SYNCRONIZE\SYNCRONIZER.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "27" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\Batch_Compiler_Auto\BatchCompiler.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "28" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\10 SYNCRONIZE\SYNCRONIZER.BAS" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "29" /t REG_SZ /d "D:\VB6\1 S Code\# VB Web Site's\FreeVBcode.com\# Code 2009\Process Cpu Usage\prjCPUProcess.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "30" /t REG_SZ /d "D:\VB6\1 S Code\# www.freevb\http___www.freevbcode.com_\www.freevbcode.com\code\pathLogger\PathLogger.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "31" /t REG_SZ /d "D:\VB6\1 S Code\# www.freevb\http___www.freevbcode.com_\www.freevbcode.com\code\Dos_Prompt\Login.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "32" /t REG_SZ /d "D:\VB6\1 S Code\# www.freevb\http___www.freevbcode.com_\www.freevbcode.com\code\DancingBaby\shell.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "33" /t REG_SZ /d "D:\VB6\1 S Code\# www.freevb\http___www.freevbcode.com_\www.freevbcode.com\code\DancingLine\Dancing Line.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "34" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\CPU %% OF A PROGRAM\CPU INDIVIDUAL PROCESS.vbp" /f
Reg.exe add "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "35" /t REG_SZ /d "D:\VB6\VB-NT\00_Best_VB_01\CPU %% OF A PROGRAM\CPU %% INDIVIDULE PROCESS.vbp" /f
Reg.exe DELETE "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "36" /f
Reg.exe DELETE "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "37" /f
Reg.exe DELETE "HKCU\SOFTWARE\Microsoft\Visual Basic\6.0\RecentFiles" /v "38" /f

EXIT 
