C:\WINDOWS\system32\taskkill.exe /F /IM CHROME* /T


START "" /REALTIME /MAX "C:\Program Files\Google\Chrome\Application\chrome.exe"  https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij?utm_source=chrome-app-launcher-inf

REM START "" /REALTIME /MAX "C:\Program Files\Google\Chrome\Application\chrome.exe" -profile-directory="Profile 2" 

REM https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij?utm_source=chrome-app-launcher-inf

REM START "" /REALTIME /MAX "C:\Program Files\Google\Chrome\Application\chrome.exe" -profile-directory="Profile 2"

REM START "" /REALTIME /MAX "C:\Program Files\Google\Chrome\Application\chrome.exe" -profile-directory="Profile 3" =----------Person
REM START "" /REALTIME /MAX "C:\Program Files\Google\Chrome\Application\chrome.exe"

EXIT
