'====================================================================
'# __ C:\SCRIPTER\SCRIPTER CODE -- VBS\VBS 50-OUTLOOK IMAP EMAIL SAVE ATTACHMENT & DELETE AFTER DATE.VBS
'# __ 
'# __ VBS 50-OUTLOOK IMAP EMAIL SAVE ATTACHMENT & DELETE AFTER DATE.VBS
'# __ 
'# BY Matthew __ Matt.Lan@Btinternet.com
'# __ 
'# START     TIME [ Fri 22-Mar-2019 10:31:08 ]
'# END FINAL TIME [ Fri 22-Mar-2019 11:50:00 ]
'# __ 
'====================================================================

'# ------------------------------------------------------------------
' DESCRIPTION 
' -------------------------------------------------------------------
' IDEA GMAIL WITH ONLY 15 GIG KEEP FILL UP FULL WITH ATTACHMENT
' REQUIRE SAVE ATTACHMENT AND DELETE EMAIL AFTER A DATE 
' BEEN SPEND SOME TIME CHECKER SOFTWARE TO DO THIS FROM
' Fri 03-May-2019 12:01:57
' ALL VERY EXPENSIVE SOFTWARE
' EASIER WAY IS USE OUTLOOK AND VBSCRIPTOR
'#-------------------------------------------------------------------
' SESSION 001 __ CREATED
' -------------------------------------------------------------------
'# START     TIME [ Fri 03-May-2019 17:40:00 ]
'# END FINAL TIME [ Fri 03-May-2019 17:40:00 ]
'#-------------------------------------------------------------------

' -------------------------------------------------------------------
' SOURCE HERE
' -------------------------------------------------------------------
' vba - Remove email attachments after saving them and adding save location to email in Outlook - Stack Overflow
' https://stackoverflow.com/questions/26745239/remove-email-attachments-after-saving-them-and-adding-save-location-to-email-in
' -------------------------------------------------------------------