@ECHO ON
@REM START "TITLE OF PROGRAM" /D"%%G:\" /MIN /NORMAL "%%G:\CHKDSK-VAR.BAT"
'START /D"C:\" /MIN /NORMAL "C:\UTILS\T.COM" %1 %2 %3


START "" /SEPARATE "C:\UTILS\T.COM"


@REM ---------------------------
@REM 16 bit MS-DOS Subsystem
@REM ---------------------------
@REM ntvdm-1dd8.3638.a80003
@REM C:\PROGRA~1\Symantec\S32EVNT1.DLL. An installable Virtual Device Driver failed Dll initialization. Choose 'Close' to terminate the application.
@REM ---------------------------
@REM Close   Ignore   
@REM ---------------------------