@REM ----------------------------------------------------------------
@REM __ MATTHEW LANCASTER 
@REM __ MATT.LAN@BTINTERNET.COM
@REM ----------------------------------------------------------------
@REM __ FROM ---- Fri 05-Oct-2018 12:34:00 Created Time
@REM __ TO   ---- Sun 07-Oct-2018 04:45:37 Last Editor
@REM ----------------------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- 002 SESSION
@REM ----------------------------------------------------------------
@REM __ FROM  Sun 07-Oct-2018 04:40:00
@REM __ TO    Sun 07-Oct-2018 04:52:20
@REM ----------------------------------------------------------------

REM ------------------------------------------------
REM Fri 05-Oct-2018 12:34:53 P
REM C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB.BAT
REM C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB.txt
REM ------------------------------------------------

@REM ----------------------------------------------------------------
@REM -- Located in Sync Location 1.. 2..
@REM ----------------------------------------------------------------
@REM -- 1..
@REM -- C:\SCRIPTER\SCRIPTER CODE -- BAT\BAT 45-SCRIPT RUN GITHUB - BAT RUNNER.BAT
@REM ----------------------------------------------------------------
@REM -- 2..
@REM -- C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB - BAT RUNNER.BAT
@REM ----------------------------------------------------------------


START "" "C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB_BAT.BAT"

REM -----------------------------------------------------------------
REM -- USE THIS ONE TO RUN GOODSYNC WHICH ALSO RUN GITHUB THROUGH THE
REM -- BAT VERSION
REM -----------------------------------------------------------------
REM START "" "C:\SCRIPTER\SCRIPTER CODE -- GITHUB\BAT 45-SCRIPT RUN GITHUB_EXE.BAT"


EXIT
